### ISSUE TITLE
AutoFill shows inaccessible key files remembered by the main app (was: Autofill password context doesn't see files added through iTunes File Sharing)

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#1]
Sorry to have to break this section in, but I guess it will eventually have to be done.
I do feel humbled to get a chance to provide some feedback!

I love that you've enabled iTunes File Sharing to be able to copy some files direct to the app without having to go through the Files app, and/or any file sharing service in there.

For the regular app, this works great, and I'm able to login using a key file copied to the phone this way. However, when I tried using the Password Autofill functionality I was prompted with the descriptive note about it being handled basically as a separate or in a different context, meaning I had to select the database again.

When getting to the prompt about the master key for the database in this context however, the file copied through iTunes File Sharing was nowhere to be seen.

I've done a quick search to see if there's anything in the Apple's API documentation, but could not really find anything applicable describing the issue. The best I've found is a entry in Strongbox's FAQ, where a workaround for the same issue is presented for that app (https://strongboxsafe.com/faq/) - "My Key File is not Auto Detected in Auto Fill Mode". Basically, the suggestion is to tie the master key to a biometric authentication, to jump around the need for the file entirely.

**Comment by keepassium** [comment]
Thanks for opening the section! :)

The reason for the additional hassle is that the system treats app extensions (such as AutoFill) [as independent apps](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW2), constrained to their own sandboxes. 

There are two ways the main app and AutoFill extension can share files across their sandboxes: 

- **Shared container:** Apps (and extensions) signed by the same developer can have a common "[shared container](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW6)", accessible by both the main app and the extension. However, in my experiments this container was not accessible via iTunes File Sharing.
- **File-specific sandbox bypass:*** Using `UIDocumentPickerViewController`, an app can ask the system to ask the user to select a file inside another app's sandbox. For the selected file, the system creates a special security-scoped reference that allows the first app to read/write the file in the second app's sandbox. This is how KeePassium accesses cloud-based databases, for instance.

KeePassium AutoFill also uses the second approach. The database you copied via iTunes is in KeePassium main app sandbox. When you press "Add database" in Auto Fill, you can find the uploaded file in Locations - On My iPhone - KeePassium. 

The same should work for key files. In AutoFill's "Unlock Database" screen, tap the key file field, press the "+" button (Add Key File), then Browse - On My iPhone - KeePassium. All key files added to the main app via iTunes should be in that folder. Please let me know if this is not the case...

**Comment by magebarf** [comment]
Spot on!

I do believe I checked out the "On my phone" section earlier without noticing the KeePassium folder, but as this was prior to me adding the file through iTunes, it could also affected things!

Really enjoying everything I've seen so far from the app, and with this guidance it will increase the (in)direct usage (through Safari) of the app quite a bit I'm guessing!

**Comment by keepassium** [comment]
I think I found the bug that caused the confusion in the first place. 

When you open a database with a key file in the main app, the latter remembers that "keyFile.key" is associated with "database.kdbx" ("Remember key files" setting is on by default). This saves you a couple of taps when you open the database the next time.

Now, the same should work (but does not) in AutoFill. When you add "database.kdbx" to AutoFill, it discovers that there is an associated key file. So AutoFill pre-fills "keyFile.key" as part of the master key — even though this key file was never added to AutoFill (and thus is not accessible). Hence the confusion.

Will fix. 
Thanks!
