### ISSUE TITLE
Not respecting the "Hide this entry from the browser extension" flag

### ISSUE THREAD

**Issue by igorkulman** [keepassium/KeePassium#100]
**Describe the bug**
The Kepassium extension does not respect "Hide this entry from the browser extension" set by KeePassXC.

**To Reproduce**
1. Mark an entry as "Hide this entry from the browser extension" in KeePassXC
2. Invoke Kepassium extension to fill in password for the same domain as entry in step 1

**Expected behavior**
The entry marked as "Hide this entry from the browser extension" should not be offered to autofill in the Kepassium extension. It should be displayed in the actual app, maybe also displayed when searching in the extension but not autofilled or in the list the extension shows.

**User Information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5
 - App Version: 1.11

**Comment by keepassium** [comment]
Thanks, Igor. 

I don't think this qualifies as a bug. This is just a custom [KeePassXC-specific](https://github.com/keepassxreboot/keepassxc/pull/3444) flag, and while other apps *might*, they don't exactly *have* to respect such flags.

That said, it is easy to add as an enhancement, just in time for the upcoming update :)

**Comment by igorkulman** [comment]
> Thanks, Igor.
> 
> I don't think this qualifies as a bug. This is just a custom [KeePassXC-specific](https://github.com/keepassxreboot/keepassxc/pull/3444) flag, and while other apps _might_, they don't exactly _have_ to respect such flags.
> 
> That said, it is easy to add as an enhancement, just in time for the upcoming update :)

It sometimes hard to say what is a KeePassXC specific feature if you want to avoid reading the KeePass specification :)
