### ISSUE TITLE
Steam TOTP not working 

### ISSUE THREAD

**Issue by mananhiteshkataria** [keepassium/KeePassium#101]
**Describe the bug**

**To Reproduce**
1. Go to 'steam stored credentials and open TOTP
4. The totp does not match the real totp it’s a sequence of numbers instead of characters like how steam totp is 

**Expected behavior**

**Screenshots**

https://photos.app.goo.gl/Ub6YoS24g3g6qkmD9

**User Information (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS13.5]
 - App Version: [v1.11.56]

**Additional context**
The steam totp does not match the Steam guard Authenticator at all

**Comment by keepassium** [comment]
According to the screenshot, your OTP field seems to be formatted like this: `otpauth://totp/Steam%20Community:username?secret=...&period=30&digits=5&issuer=Steam%20Community&encoder=steam`

I got a similar URI generated by KeePassXC 2.5.4, but with "Steam TOTP test" instead:

`otp: otpauth://totp/Steam%20TOTP%20test:username?secret=...&period=30&digits=5&issuer=Steam%20TOTP%20test&encoder=steam`

Apparently, KeePassXC relies on the "encoder" parameter to recognize Steam URIs. However, it seems to be a [personal initiative](https://github.com/keepassxreboot/keepassxc/pull/1206/commits) of one of KPXC's contributors — the "encoder" parameter is never mentioned in the [otpauth:// format documentation](https://github.com/google/google-authenticator/wiki/Key-Uri-Format).

Instead, according to [KeeWeb](https://github.com/keeweb/keeweb/issues/564#issuecomment-535221800), [Bitwarden](https://community.bitwarden.com/t/question-about-steam-totp-codes/3513/10) — and ironically [KeePassXC](https://github.com/keepassxreboot/keepassxc/issues/1615#issuecomment-370171270) itself — it should be formatted like this:

`otpauth://totp/Steam:username?secret=...=&issuer=Steam`

And this is the format used by KeePassium: either the company name or the issuer should be "Steam".

So, if you adjust your `otp` URI to match the community-standard format above, KeePassium should show the correct TOTP.

**Comment by mananhiteshkataria** [comment]
well i did what you said and now the other clients were not working (but keepassium is ) so i have created a clone identity and kept different totp secrets as a temporary workaround thanks a lot .

**Comment by keepassium** [comment]
If you leave the `encoder=steam` parameter, KeePassXC should work properly, too. I don't know why they decided to rely on a custom parameter instead of the standard format... 

Anyway, I've added this in the parser, too, so in the next release KeePassium will recognize KPXC-configured Steam TOTPs out of the box. Thank you for reporting this!

**Comment by mananhiteshkataria** [comment]
> If you leave the `encoder=steam` parameter, KeePassXC should work properly, too. I don't know why they decided to rely on a custom parameter instead of the standard format...
> 
> Anyway, I've added this in the parser, too, so in the next release KeePassium will recognize KPXC-configured Steam TOTPs out of the box. Thank you for reporting this!

Thank you for helping me out with this was kinda confused about it but my only guess is keepassxc did it to make it easier for the end user somehow
