### ISSUE TITLE
Feature request: copy/move items between databases

### ISSUE THREAD

**Issue by chessgriffin** [keepassium/KeePassium#102]
I have multiple keepass databases and frequently need to move items between them. It would great to have this option in keepassium.  Thanks for the great app!

**Comment by keepassium** [comment]
Yeah, this feature makes sense; I've also received a few similar requests over email.

If possible, could you describe *why* you move items between databases? (Is it from main database to client DBs, or project-level DB to team members', or something else?) Also, one at a time, or several simultaneously?

More info would help me better understand the problem to be solved :) Thanks!

**Comment by chessgriffin** [comment]
For me, it’s a family use-case.  I tend to create most of the passwords for various sites and I’d like to be able to copy them to my wife’s database.  Sometimes I might copy or move one login and other times I might want to copy or move several at once.  We have two kids of different ages so I might copy some of our logins like Netflix to the older kid but not the younger kid yet.  We might also want the kids to learn to use a password manager and my wife and I might want them to share some of their passwords with us by copying them to our databases.  This would be a really important feature for us. Hope that helps!

**Comment by keepassium** [comment]
Yes, this helps. Thank you!

**Comment by jamesandariese** [comment]
I also have all these use cases except the number of kids is different.

I have one other use case which I suspect was simply forgotten but _may_ be unique to me:

Whenever I'm making a new password, I will very commonly place it in my personal database without thinking.  It would be nice if, once I've realized that, I could easily move the item to where it belonged to begin with.

**Comment by chessgriffin** [comment]
Please consider adding this feature.  It would be extremely helpful.  Thanks!

**Comment by facetheheat** [comment]
+1 
this is the key feature to switch from other major/cloud password managers

**Comment by keepassium** [comment]
Thank you for the feedback, everyone! There is still some groundwork left to make this happen, but we are getting there.

**Comment by keepassium** [comment]
Good news! Cross-database moving is implemented and heading for [beta testing](https://keepassium.com/beta/). (Apple will take a few days to approve the beta release, though.)
