### ISSUE TITLE
Chinese characters appear when exporting to OneDrive on iOS 

### ISSUE THREAD

**Issue by majijiwi** [keepassium/KeePassium#103]
When exporting a database to OneDrive on iOS, Chinese characters appear in the file type description.

![1B61F779-13C1-4905-A409-2C5E60563E30](https://user-images.githubusercontent.com/66420698/83753336-6c045e00-a6ad-11ea-9c11-da4b2a66d0d4.jpeg)

**Comment by keepassium** [comment]
For me, it's in Czech :) This seems to happen only when the system language is set to English. In other languages, the description is properly localized.

After some investigation, it looks like the system picks the description from `InfoPlist.string`. And if there is no suitable language, it picks one randomly. Adding an English-to-English translation for this file seems to fix the issue. 

I'll include the fix in the next update. Thanks for reporting!
