### ISSUE TITLE
Support for field references

### ISSUE THREAD

**Issue by robimac04** [keepassium/KeePassium#105]
**Describe a feature you'd like**
I have entries in my Keepass DB, which use an LDAP password, but have different OTPs. For this, I have an object for my LDAP account with the password. For all services using this password, I just reference to the password in the LDAP object using

`{REF:P@I:01234567890123456789012345678901}`

in the password field. This works fine in KeepassXC on the desktop, but Keepassium cannot follow the reference.

It would be great to see this feature in Keepassium.

**Additional context**
- https://keepass.info/help/base/fieldrefs.html

**Comment by keepassium** [comment]
Thanks! Yes, it is [already on the list](https://github.com/keepassium/KeePassium/issues/77).
