### ISSUE TITLE
Feature request: import passwords from Apple's KeyChain

### ISSUE THREAD

**Issue by Dragonblitz10** [keepassium/KeePassium#11]
would be useful if it's possible to transfer all passwords of the internal keychain to KeePassium saving time and effort in transferring large amounts of data.

Another great option would be able to select multiple databases on the menu to either delete or export all databases at once

**Comment by keepassium** [comment]
Thank you for the suggestions.

> would be useful if it's possible to transfer all passwords of the internal keychain to KeePassium saving time and effort in transferring large amounts of data.

I agree that import from keychain would be useful to some people. But I think this feature is out of the scope for KeePassium:

- Keychain import is a one-time procedure, that [can already be done on desktop](https://github.com/lifepillar/CSVKeychain) (although more complicated than it should be).
- If added, this will quickly avalanche into "Import passwords from _[all other password managers]_". This will become a maintenance hell, taking time from development of the core features.
- The import function will be used by only few percents of people (once), but it will occupy space for everyone (forever).

That said, this is a great idea for a separate "Keychain to KeePass" app.

> Another great option would be able to select multiple databases on the menu to either delete or export all databases at once

Can you describe your use case, please? I assume that most people have only one (or few) databases, and they are synced to some server...

Thanks!

**Comment by Dragonblitz10** [comment]
I understand clearly if it's possible to export the passwords from the Apple keychain Is there a link showing how?


For the last bit when I turned on show backups I wanted to delete all the backups as they were too manny of the old database which was useless however I had to keep swiping and deleting while clicking confirm which became tiring so I decided to ask if it's possible  to have multi selection and deletion

**Comment by keepassium** [comment]
> I understand clearly if it's possible to export the passwords from the Apple keychain Is there a link showing how?

There are a few guides that can be found by "keychain to keepass". [One of such guides](https://github.com/lifepillar/CSVKeychain) was mentioned above. I guess the issue in the title can be considered closed now.

> For the last bit when I turned on show backups I wanted to delete all the backups as they were too manny of the old database which was useless however I had to keep swiping and deleting while clicking confirm which became tiring so I decided to ask if it's possible to have multi selection and deletion

You are right, this can become very tiring very quickly!

If we look deeper, the root issue seems to be not "too many actions to delete a file", but rather "there are too many backup files". 

I just opened #12 to fix this, so nobody will ever have to delete dozens of backup files manually (sorry about that...)

Thanks for the feedback!
