### ISSUE TITLE
Folder names with a dot not shown

### ISSUE THREAD

**Issue by MBurchard** [keepassium/KeePassium#111]
**Describe the bug**
My Keepass database is synced using Synology Drive.  
On all my machines there as a folder called **.sensible** containing a folder called **.ssh**.  
Both containing sensitive information.

I have synced them to my iPhone. Now, when I want to use the folders, they are not shown in in KeePassium.

I don't know if this can be solved by the App, would be nice.

**User Information (please complete the following information):**
 - Device: iPhone 8
 - OS: 13.5.1
 - App Version: v1.13.62

**Comment by keepassium** [comment]
Thanks for the feedback!

This is not a KeePassium bug — it's a feature (or limitation?) of the iOS file system. 

If you open the Files app and try to create a folder with a leading dot, the app will show:

> You can't use a name that begins with a dot because these names are reserved for the system. Please choose another name.
