### ISSUE TITLE
Error occured while adding a database for the iOS AutoFill feature

### ISSUE THREAD

**Issue by robot-from-outer-space** [keepassium/KeePassium#115]
I've recently changed the database from using a local copy to directly using the cloud storage provider (pcloud) which seems to have broken my formerly working AutoFill feature. When I want to use the AutoFill feature e.g. within Safari it redirects me to KeePassium. It then prompts me to add the database again because of the containerization of AutoFill. However, as soon as I press the button to add the database it says that an error occurred while displaying the documents. I never get the chance to actually select a database file or a cloud storage provider.

Screenshot showing the button which triggers the error message:
![IMG_1880](https://user-images.githubusercontent.com/59934363/88701305-204cbe80-d10a-11ea-813e-c7880a921eed.PNG)

Screenshot of the error message:
![IMG_1881](https://user-images.githubusercontent.com/59934363/88701312-217deb80-d10a-11ea-9a2a-3fbe89ed81f9.PNG)

I'm using an iPhone 11 with iOS 13.6. Re-adding the database or resetting the AutoFill settings were not helping to prevent the issue.

Thanks in advance!

**Comment by keepassium** [comment]
Thank you for the feedback! 

As I already mentioned on Reddit, this seems to be an iOS bug: #96
