### ISSUE TITLE
Support Inputstick key

### ISSUE THREAD

**Issue by samsam-rolon** [keepassium/KeePassium#116]
As an Ex-Android user, I was using [InputStick Key](http://inputstick.com/) with [KP2A Plugin](http://inputstick.com/kp2a-plugin/).

Main Feature : Auto-typing on a computer your password from your phone with the device InputStick.
The InputStick emulate a perfect keyboard for the computer. The connection between Phone and InputStick is secured through bluetooth AES-128 (CBC mode).

It's a good way to type password when you're not on YOUR computer and to avoid : to type manally a very long password and compromise your entire DB in opening it on a unknow computer.

Note : As Yubikey, probably a premium feature ....

**Comment by samsam-rolon** [comment]
Okay so "my bad"
- Using the [InputStickUtility App](http://inputstick.com/inputstickutility-ios/) and auto-fill function, it can works !

**Comment by keepassium** [comment]
The thing is, Android has much better support for multi-app collaboration. On iOS, the possibilities are much more limited. 

For example, KeePassium could launch InputStickAutofill with prefilled fields, but the app would open in full screen (replacing KeePassium), and you would need to take another step to return back to KeePassium.

A more seamless alternative is to tap on an entry field in KeePassium → tap the "Share" button → USB Remote (another InputStick app) → tap Type in the popup. This way, you can use InputStick without switching between apps, but this takes 4 taps which is way too much for every single field.
