### ISSUE TITLE
Make the search diacritic insensitive

### ISSUE THREAD

**Issue by hunhejj** [keepassium/KeePassium#118]
Would it be possible to make the search diacritic insensitive, i.e. ignore accents?

A few examples:
- searching for `OBB` should find `ÖBB`
- searching for `Exupery` should find `Antoine de Saint-Exupéry`
...

**Comment by keepassium** [comment]
Good point, thanks, will do.

**Comment by hunhejj** [comment]
Great, thank you!

**Comment by keepassium** [comment]
Already in the App Store :) 

The search will be diacritic-insensitive now, unless you use diacritics in the search query.

**Comment by hunhejj** [comment]
Awesome, thank you for the quick improvement!
