### ISSUE TITLE
Feature request: Port to Make App Compatible with iPadOS

### ISSUE THREAD

**Issue by aaaaamir** [keepassium/KeePassium#120]
**Describe a feature you'd like**
A clear and concise description of what you want to be added.

**Additional context**
Add any other context or screenshots about the feature request here, or what make you request said feature.

I tried downloading and running it on iPad and the app doesn’t open!

**Comment by keepassium** [comment]
The app is already compatible with iPadOS. 

If something does not work, please create a bug report with all the details in the template (what you do, what happens, what should happen instead, what is your device and iPadOS version). Or email me your iPadOS version and what exactly happens (support@keepassium.com). Thanks!

**Comment by aaaaamir** [comment]
Thanks so much, will do!
