### ISSUE TITLE
App Hangs on Startup (iPad 6th Generation, iPadOS 13.5.1)

### ISSUE THREAD

**Issue by aaaaamir** [keepassium/KeePassium#121]
**Bug Description**
When trying to open the app, the UI is shown (snowflake background) but then no options open up to choose a database to open as in the iOS version with expected behaviour 

**To Reproduce**
1. Start up app — no UI is brought into view.

**User Information (please complete the following information):**
 - Device: iPad 6th Generation
 - OS: iPadOS 13.5.1
 - App Version: 1.16

**Comment by keepassium** [comment]
Thanks! Is the app just installed, or you already added a database there?

**Comment by aaaaamir** [comment]
Yep I just downloaded the app, no database added yet

**Comment by keepassium** [comment]
@aaaaamir, does it crash after ~20 seconds, or just hangs on the screen?

**Comment by aaaaamir** [comment]
My iPad just automatically updated to 13.6.1 and now I no longer have the problem! I don’t think anyone else will be running 13.5.1 unless they explicitly refuse the OTA update so it may be fine to close the issue! 👍🏼 (Sorry for slow response ... my initial email response didn't go through)
