### ISSUE TITLE
Autofill not working on iOS14

### ISSUE THREAD

**Issue by swa72** [keepassium/KeePassium#122]
KeePassium used to work flawlessly under iOS13. Now with the latest iOS14 Beta it complains that it cannot find the file. File is still on iCloud.

**Comment by swa72** [comment]
-0.000 (I) 	MainCoordinator.swift:54 	init(rootController:) 	KeePassium AutoFill v1.16.73 (iPhone, iOS 14.0)
0.539 (I) 	PremiumManager.swift:204 	updateStatus(allowSubscriptionExpiration:) 	Premium subscription status changed [was: initialGracePeriod, now: freeLightUse]
0.543 (I) 	Watchdog.swift:248 	engageAppLock() 	Engaging App Lock
0.573 (D) 	MainCoordinator.swift:821 	showBiometricAuth() 	Biometric auth: showing request
0.582 (D) 	FileKeeper.swift:870 	deleteExpiredBackupFiles() 	Will perform backup maintenance
0.585 (I) 	FileKeeper.swift:872 	deleteExpiredBackupFiles() 	Backup maintenance completed
0.591 (I) 	DatabaseManager.swift:172 	_loadDatabase(dbRef:compositeKey:) 	Will load database
0.648 (E) 	FileAccessError.swift:118 	make(from:fileProvider:) 	Failed to access the file [fileProvider: com.apple.CloudDocs.MobileDocumentsFileProvider, systemError: Error Domain=NSCocoaErrorDomain Code=4 "The file doesn’t exist."]
0.651 (E) 	DatabaseManager.swift:723 	onDatabaseURLResolveError(_:) 	Failed to resolve database URL reference [error: The file doesn’t exist.]
0.653 (E) 	DatabaseUnlockerVC.swift:98 	showErrorMessage(_:reason:suggestion:haptics:) 	Cannot find database file
The file doesn’t exist.
1.511 (I) 	MainCoordinator.swift:826 	showBiometricAuth() 	Biometric auth successful
44.385 (I) 	DatabaseManager.swift:172 	_loadDatabase(dbRef:compositeKey:) 	Will load database
44.387 (E) 	FileAccessError.swift:118 	make(from:fileProvider:) 	Failed to access the file [fileProvider: com.apple.CloudDocs.MobileDocumentsFileProvider, systemError: Error Domain=NSCocoaErrorDomain Code=4 "The file doesn’t exist."]
44.402 (E) 	DatabaseManager.swift:723 	onDatabaseURLResolveError(_:) 	Failed to resolve database URL reference [error: The file doesn’t exist.]
44.407 (E) 	DatabaseUnlockerVC.swift:98 	showErrorMessage(_:reason:suggestion:haptics:) 	Cannot find database file
The file doesn’t exist.

**Comment by swa72** [comment]
I have to add that I can open KeePassium and the file manually without problems.

**Comment by keepassium** [comment]
Hey! If the database is accessible from the main app but not the AutoFill, you just need to re-add the file to AutoFill.

The reason is that the main app and its AutoFill extension have independent file lists. (This is due to a technical limitation on iOS.) So when you add or remove a database in the main app, the AutoFill does not know anything about it and keeps using the old database reference. 

The solution is to open AutoFill, navigate back to the list of databases, remove the broken one and add your database again.

**Comment by swa72** [comment]
Thanks for the hint. In AutoFill you can only select apps, not files. I removed KeePassium from my iPhone, installed it again and voila ... it works. Oddly, the kdbx file is/was/remained at the same place. Oh well, ...

**Comment by keepassium** [comment]
> In AutoFill you can only select apps, not files.

It seems you are referring to the AutoFill section in device settings. What I meant was opening the KeePassium AutoFill itself (by pressing the "Passwords" button above the keyboard), and checking the list of databases there.

Reinstalling KeePassium resets all the settings and empties the file lists, so you had to re-add the database to the main app and to AutoFill as well. It's just another (longer :) way of re-adding the database :)
