### ISSUE TITLE
App icon names shift after changing once

### ISSUE THREAD

**Issue by dragonblitz10** [keepassium/KeePassium#123]
**Describe the bug**
App Icon names shift towards the left after changing once

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on App Icon
3. Select an App Icon
4. See the classic you have changed icon but notice how first half of each name is inside the icons

**Expected behaviour**
I would expect to see the names as they were before 
**Screenshots**
[before](https://i.imgur.com/ZLhXy9u.jpg)
[after](https://i.imgur.com/vfOBMDz.jpg)

**User Information (please complete the following information):**
 - Device: Iphone 6s
 - OS: 12.4
 - App Version: 1.16.73

**Additional context**

**Comment by keepassium** [comment]
Yep, I can reproduce this on iOS 12.2 simulator (iOS 13+ seems to work as intended).

I will look into this, thanks!
