### ISSUE TITLE
Password not remembered when updating the file

### ISSUE THREAD

**Issue by rderensy** [keepassium/KeePassium#125]
**Describe the bug**
When updating the database locally (in "On my iPhone"), the app asks for the password/keyfile again even though the file name is the same. I didn't have the problem before you changed something in 1.15/1.16, the app remembered the master password for this database.

**To Reproduce**
1. Update the database file in "On my iPhone"
2. Launch Keepassium (it will say the database file doesn't exist)
3. Select the "new one"
4. Reselect keyfile and write password 

**Expected behavior**
The password/keyfile should be remembered when updating the file especially when it has the same name and is in the same location.

**User Information (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.7 and iOS 14
 - App Version: 1.16 and 1.17 (and perhaps 1.15)

**Comment by keepassium** [comment]
What is your Database Timeout (app settings → Data Protection)?

**Comment by keepassium** [comment]
Hmm, I cannot reproduce this.

> 2. Launch Keepassium (it will say the database file doesn't exist)

When I tap the missing database, it shows the "File doesn't exist" message, an Unlock button, and the "Will use the remembered master key" prompt. After tapping "Unlock", this remains the same. So the master key is properly stored, even thought the database is missing.

> 3. Select the "new one"

When I add a database with the same name, KeePassium replaces the "missing" database with the new one and proceeds to unlock it using the stored key... 

Can you please confirm you are not removing the "missing" database between steps 2 and 3?

**Comment by rderensy** [comment]
I might add that it would be even better if I didn't have the "database missing" message, since the new file has the same name and is in the same location.

**Comment by keepassium** [comment]
> I might add that it would be even better if I didn't have the "database missing" message, since the new file has the same name and is in the same location.

This is the specifics of iOS file system: files are identified not just by their path/name, but also by an ID. So when you remove the old database and copy a new file to the same folder, with the same name — for iOS it is a different file. KeePassium's reference resolves to the old file, which has been deleted.

By the way, none of this would be an issue if you copy the database to On My iPhone / KeePassium. This folder is in the app's sandbox, so it is treated a bit differently: there is no need to use references, KeePassium can read this folder and access its files directly. So if you replace a database in On My iPhone / KeePassium, it would be updated in KeePassium automatically.

> since the database isn't recognized in the app (I can't "update" the location or whatever), I have to remove it from the app and then search the new one.

That's exactly what I meant by removing the missing database. When you remove a database from KeePassium, all the associated settings and keys are cleared as well. 

Unfortunately, the free version won't allow adding the database without removing the old one first. The full version makes it a bit easier: the user can simply add the same database (without removing the "missing" one), and KeePassium will replace the "missing" entry with the correct reference, preserving all the DB setting and keys.

**Comment by rderensy** [comment]
> but also by an ID.

That's what I thought 

> none of this would be an issue if you copy the database to On My iPhone / KeePassium.

That's good to know, might be the solution here! 

> When you remove a database from KeePassium, all the associated settings and keys are cleared as well.

This wasn't the case before 1.15/1.16, I've always done like this and it has always worked, since the beta IIRC

**Comment by keepassium** [comment]
> This wasn't the case before 1.15/1.16, I've always done like this and it has always worked, since the beta IIRC

You are right, it worked before. Ironically, it was not a feature :)

The thing is, a broken file reference cannot be resolved using standard system API. As a result, KeePassium cannot even get the name of the file that went missing. So broken references were shown with just a question mark instead of file name. And without knowing which file is gone, KeePassium could not properly clean up the associated settings and keys.

Starting from 1.14, KeePassium uses a bit of black magic to analyze file references. As a result, the app can recognize the storage location of the file (local storage, Dropbox, etc), and extract the original file path — even if the file no longer exists. So now it became possible to keep more robust associations between database file and its settings/keys. And, correspondingly, erase associated data even if the database is gone.

**Comment by rderensy** [comment]
Problem is: because of that "file ID", when I copy the .kdbx from my server (only accessible when connected to my wifi network at home) to my iPhone, the .kdbx on my phone is basically linked to the .kdbx on the server.

Now if I disconnect from the wifi, Keepassium can't load the database because the .kdbx on my phone can't be linked to (can't "contact") the .kdbx on the server anymore. I am guessing this issue is related to the Files app from Apple but ... again, it worked flawlessly before :/

**Comment by keepassium** [comment]
> Problem is: because of that "file ID", when I copy the .kdbx from my server (only accessible when connected to my wifi network at home) to my iPhone, the .kdbx on my phone is basically linked to the .kdbx on the server.

This does not sound right. A file copied to local storage should be available regardless of its original source. Do you copy the file using the Files app, or simply adding it to KeePassium?

**Comment by rderensy** [comment]
I copy the .kdbx using the Files app, into the Keepassium folder as you suggested to. If I try to open the .kdbx from the server directly, it's added to Keepassium with a "server" icon next to it and, of course, doesn't work without having connection to the server.

**Comment by rderensy** [comment]
When I copy the file in the Keepassium folder, the auto-fill doesn't find the new file automatically, whereas the app does.

**Comment by keepassium** [comment]
> When I copy the file in the Keepassium folder, the auto-fill doesn't find the new file automatically, whereas the app does.

Yes, this is a technical limitation of iOS. The app itself and its AutoFill extension run in separate processes, so the AutoFill is not allowed to access KeePassium's local folder. That's why you need to link these files to AutoFill explicitly, like any other external file. This is mentioned in the AutoFill setup screen, but few people read the small print :)

![IMG_0391](https://user-images.githubusercontent.com/38399598/95024685-09d05f80-0685-11eb-894d-eaf77c27822e.PNG)

(Also, we are deviating from the original issue.)

**Comment by rderensy** [comment]
> (Also, we are deviating from the original issue.)

Well .... before 1.15 I could just delete the database, add it back and the password was still remembered, even in auto-fill. So you solution was to add the .kdbx to the Keepassium folder, but then that doesn't solve this problem when using auto-fill

**Comment by keepassium** [comment]
> Well .... before 1.15 I could just delete the database, add it back and the password was still remembered, even in auto-fill. So your solution was to add the .kdbx to the Keepassium folder, but then that doesn't solve this problem when using auto-fill

Fair enough. This should be addressed by the [changes made in v1.18](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#11875---2020-10-01):

- If the existing database link is broken (file missing or has a permission error), you can add the database again. The free version will not show a premium paywall as before.
- When there are two databases with the same name, and you delete one, KeePassium will preserve the settings (and stored keys).

So while I cannot make AutoFill pick up the changed file automatically, re-adding the broken link should be as easy as adding the database again and removing the old/broken link.

**Comment by rderensy** [comment]
> So while I cannot make AutoFill pick up the changed file automatically, re-adding the broken link should be as easy as adding the database again and removing the old/broken link.

When I try to add a new one (because "file doesn't exist") while AutoFill, it asks me to upgrade to premium. I am running 1.19.76

**Comment by keepassium** [comment]
> When I try to add a new one (because "file doesn't exist") while AutoFill, it asks me to upgrade to premium. I am running 1.19.76

Hmm, you are right... The single-DB limit should ignore missing files, but this does not quite work as designed. I'll fix this in the next update. Thanks!
