### ISSUE TITLE
Keepass file isn't updated anymore (NextCloud Backend) since beta-25

### ISSUE THREAD

**Issue by noudAndi** [keepassium/KeePassium#13]
Hi,

since the last release, keepass files are not updated anymore. Even trying to reload has not effect. File is up to date in FilesApp and NextCloud app.

Any ideas?

**Comment by keepassium** [comment]
Seems related to #10. I will revert the change that caused this regression. 
Sorry about that...

**Comment by noudAndi** [comment]
No worries! It‘s still beta 😉

**Comment by keepassium** [comment]
Please check if the issue remains in beta 26. Thanks!

**Comment by noudAndi** [comment]
Hi,
thanks for fixing. The issue didn't not come up again! :)

**Comment by keepassium** [comment]
Happy to hear that, thanks! :)
