### ISSUE TITLE
KeePassium Creates and Uses Duplicate Databases Instead of the Proper One on iOS 14.0.1

### ISSUE THREAD

**Issue by aaaaamir** [keepassium/KeePassium#131]
From time to time, instead of opening my KeePass database, KeePassium will duplicate it, creating a new database with the same data and same master key, entitled “databaseName 2” and use it instead of the original.

This leads to issues with synchronization, since I don’t want to add new entries to a duplicate database, then having it not show up in the original one that other devices use. 

I’m not sure what triggers the bug, but I now have around 5 duplicate databases! 

Device: iPhone 11
OS: iOS 14.0.1
App Version: 1.17.74

**Comment by keepassium** [comment]
Thanks. I could use some more detail:

- Where do you store the database?
- Where do the duplicates appear?
- Do you open it simultaneously on different devices?

**Comment by aaaaamir** [comment]
The database is stored in an iCloud folder and the duplicates are made in the same folder! 

Ah, perhaps it occurs since I sometimes have keepassxc on MacOS and keepassium on iOS open simultaneously, both working on that same database, and keepassxc kicks out the other app from access. 

Maybe instead of providing a duplicate though it could generate a temporary duplicate read-only copy of the database, to be deleted afterwards? And a warning of multiple apps accessing the database could be shown to tell the user to close one of the two apps if they want to make changes to the database 🤔

**Comment by keepassium** [comment]
Thank you for the details. 

This looks like a typical [sync conflict](https://help.dropbox.com/files-folders/share/conflicted-copy). When the same database is modified from two different devices simultaneously, iCloud Drive has to decide which of the two files to keep:

- If it chooses device A, then changes made on device B would be lost. 
- If it chooses device B, the changes made on device A would be lost. 

So iCloud Drive (as well as Dropbox, OneDrive, and some other cloud providers) choose a third strategy. They save one database (lets say, A)  in place of the original file, and save the other database revision (say, B) in the same folder, with a number in file name. This way, the user can later decide how to merge the conflicting edits.

Ideally, KeePassium should check the online database before saving and merge changes automatically. However, this is a massive technical task that will take some time to implement.

In the meanwhile, try to avoid opening the database on several devices simultaneously. To merge the already created conflicted copies, you can use KeePassXC (open your main database → Database → Merge from database... → select the numbered database).

**Comment by aaaaamir** [comment]
Thanks! Sounds great :)

**Comment by keepassium** [comment]
Happy to help! I'll close this, then :)

**Comment by plesastapevka** [comment]
Has this issue been resolved?

**Comment by keepassium** [comment]
> Has this issue been resolved?

Well, it is closed, so yes.

Since 2020, KeePassium has [learned to detect and handle sync conflicts](https://keepassium.com/blog/2021/09/keepassium-1.26/#multi-device). But in multi-device environment sync conflicts can still occur outside the app:
- The user opens a database on device A and B, then both devices go offline.
- The user modifies the database on device A, then does some other change on device B. (Being offline, they cannot detect anything suspicious).
- Once both devices go online, they upload two different versions of the database, both claiming to be the latest. Hence the sync conflict.

The best approach is to open the database on one device at a time.
