### ISSUE TITLE
"database timeout: never" is not a premium option (but should be)

### ISSUE THREAD

**Issue by cryptosteve2** [keepassium/KeePassium#136]
Hi,
I'm completely new to Keepass and KeePassium. If this is a "feature" and not a bug, please close this issue. 

**Describe the bug**
The option "close database after: never" is marked as a premium option but works for me in the free version of KeePassium.

**To Reproduce**
Sorry, I have the german version of KeePassium and translate the steps on the fly. If it's unclear, I switch my phone to english language 
1. Go to Data Protection
2. Click on Database timeout
3. Scroll down to NEVER
4. Activate this option in free version works 

**Expected behavior**
This shall be a premium option

**Screenshots**
sorry for german language, please let's me know if you need an english one ... 
Screenshot -> [CE0E0FE4-25BE-40CF-8771-70F114EEC1D4_1_105_c](https://user-images.githubusercontent.com/6260784/103016804-f07fd680-4542-11eb-990e-dcd9a87cb8fd.jpeg)

**User Information (please complete the following information):**
 - Device: iPhone X
 - OS: iOS14.3
 - App Version: 1.20.78

**Comment by keepassium** [comment]
Hi @cryptosteve2 , thank you for the feedback!

You are right, the "Never" timeout is advertised as premium-only, but is also available in the free version (used casually). It is a known unofficial loophole.

In my initial plan, there were two groups of users:

- Novice and casual users who use the app rarely. They understand that entering the master password is the cost of the free version.
- Expert users who use the app often. They would quickly get tired of entering their (long) master password, and would update to the premium version.

In reality, however, most users expected the database would always open after a Touch ID/Face ID scan. With the 1-hour timeout, this was impossible. In the first months, this mismatch caused many negative reviews that the app is "broken". As one might guess, explaining this was a limitation of a free version did not work.

To fix this, I had to disable database timeout by default, also in the free version. To avoid abuse, KeePassium still enforces a 5-minute database timeout if the app is used heavily.

This loophole is not advertised anywhere, so it can be considered a "useful bug"/"easter egg". This way, it can change in the future — if I ever find a way to limit database timeout without breaking biometric auth...

There is also a (way too long) [discussion](https://www.reddit.com/r/KeePassium/comments/iclsm4/update_114_from_august_19th_removes_previously/) about this on Reddit.
