### ISSUE TITLE
Instead of deleting move entry to Recycle Bin

### ISSUE THREAD

**Issue by richarddribeiro** [keepassium/KeePassium#137]
**Move entry to Recycle Bin instead of deleting it**
IMHO it would be nice if we have in the settings a (kind of) switch to choose between two options when the user ask to delete an entry in KeePassium: to **move** it to the Recycle Bin folder or really to **delete** it.

**Additional context**
I am using KeePassXC in my computer and when I delete an entry KeePassXC moves it to the Recycle Bin instead of deleting it. That gives me peace of mind because I know that if I make a mistake I can recover it later. However, I understand that not everybody would be happy with this behaviour, so I thought that a switch it would allow one to choose what he/she would prefer.

I am currently testing Keepassium and I am linking it a lot. Thank you for this fantastic software.

Cheers

**Comment by keepassium** [comment]
Hi Richard,

There is a checkbox in database settings (KeePassXC → Database → Database Settings → General → History Settings → Use recycle bin). 

KeePassium does not expose this option in the UI yet, but respects its value. If "Use recycle bin" is on, deleted items are moved to Recycle Bin group. If it's off, deleted items are deleted forever. 

(Unless there is a bug and this does not work as intended, of course :)

**Comment by richarddribeiro** [comment]
Hi Andrei!

Thank you for your quick reply.

In fact, my KeePassXC has already that option "on", but KeePassium unfortunately is not respecting its value. Can you have a look on that when possible?

Cheers!

**Comment by richarddribeiro** [comment]
Sorry Andrei! It is working! My fault... I am sorry!

I've tested deleting a entry, but failed to find it in the several items inside the Recycle Bin! Sorry!

As that was the only thing holding me back, I already signed for a subscription.

Cheers!

**Comment by keepassium** [comment]
No worries, Richard. I am glad it works as intended :)
