### ISSUE TITLE
Logon without keyfile field

### ISSUE THREAD

**Issue by Svadokan** [keepassium/KeePassium#145]
By opening Keypassium on my iPad, i can only fill in the masterpassword, but there is no field for the keyfile the database is configured for. So the login failes.
On my iPhone i start Keypassium and i have two fields, one for the masterpassword and one to specify the keyfile. There the logon works...

**Comment by keepassium** [comment]
KeePassium has two types of passwords: an app protection passcode, and an encryption password for each database. It sounds like your iPad shows the app protection screen. Once you unlock it (with the app protection passcode), you will see your database and the corresponding two-field unlock screen.

Please check here for more detail and screenshots: https://keepassium.com/articles/invalid-password/
