### ISSUE TITLE
WebAuthn

### ISSUE THREAD

**Issue by mkwiecinski** [keepassium/KeePassium#146]
First of all - KeePassium is a really convenient product, keep up the good job!

**Describe a feature you'd like**
Support for WebAuthn.

**Additional context**
Some reference regarding WebAuthn and Yubikey: https://developers.yubico.com/Mobile/iOS/WebAuthn_iOS_Demo_Walkthrough.html

**Comment by keepassium** [comment]
> First of all - KeePassium is a really convenient product, keep up the good job!

Thank you!

> Support for WebAuthn.

I'm afraid I need some more detail here... Do you mean using WebAuthn for database protection? But how is this different from the existing challenge-response scheme?

**Comment by mkwiecinski** [comment]
Well, not really DB.

There are at least two ways: use WebAuthn locally (also CTAP is an acronym that corresponds to this scenario, see https://github.com/w3c/webauthn/issues/954)

But from UX perspective, I was wondering if it can be used more in a manner that Google Prompt works. But I am not sure that in Google Prompt WebAuthn is actually used behind the curtain.

**Comment by keepassium** [comment]
(Sorry for the delay.)

Having only a vague idea about WebAuthn, I took some time to read about CTAP. If I understand correctly, you want KeePassium to become a roaming authenticator. Unfortunately, there are several obstacles:

- Communication:
  - Google prompts seem to involve direct app-to-server communication. For KeePassium, this would go against one of the key design principles: being an offline app.
  - CTAP2 implies communication via BLE, NFC or USB. Each of them is uniquely [problematic](https://stackoverflow.com/questions/57379495/mobile-authenticator-using-ctap2-specifications?rq=1) on iOS... 
- Scope: KeePassium is a password manager. Passwordless authentication via BLE (most likely option) would require quite a lot of code that has nothing to do with password management. Too much code for a feature that most users won't use. I would say "CTAP authenticator" is a good function for a dedicated app, but for today's KeePassium it is out of scope. (This might evolve in the future, though.)

**Comment by mkwiecinski** [comment]
Thanks for digging deeper and providing product perspective. This was just an idea, I can agree that it would be hard and not significsntly impactful for your users. I think you should monitor this from time to time though! :)

**Comment by keepassium** [comment]
Thank you for understanding :) In the meanwhile, I'll close this issue.
