### ISSUE TITLE
Autofill on macOS

### ISSUE THREAD

**Issue by jeinwag** [keepassium/KeePassium#147]
I tried KeePassium on a new M1 Mac mini and successfully registered it as an autofill provider.
But actually using it in Safari doesn't work: When I choose KeePassium on some field, a white windows appears for a split second but nothing else happens. I don't know if this can be fixed within KeePassium or if it's some kind of general issue when running iOS apps on macOS.

**To Reproduce**
1. Install KeePassium on M1 Mac
2. Register it as an autofill provider in system preferences
3. Try to actually use KeePassium autofill in Safari

**Expected behavior**
The KeePassium window should appear, allowing me to choose which credentials to use.

**User Information (please complete the following information):**
 - Device: Mac mini (M1, 2020)
 - OS: macOS 11.2.1
 - App Version: 1.2.1 (81)

**Comment by keepassium** [comment]
Thanks! I am aware of this issue, and checked if it can be fixed quickly. Unfortunately, a quick attack did not solve it. According to the debugger, the view controller appears, no errors, but then the system notifies that the view is about to be hidden. No problems, no warnings, everything behaves as if that's how it is supposed to be.

So I'll need some time to take a closer look and analyze this properly.
