### ISSUE TITLE
KeePassium AutoFill should check if the file was deleted or auto delete if not found

### ISSUE THREAD

**Issue by Dragonblitz10** [keepassium/KeePassium#15]
steps to replicate 
1: crate a new database 
2: add it to the auto fill 
3: delete the database (including the bin)
4: check auto fill 

(The option to copy diagnostic data doesn't seem to allow me to copy and paste so maybe display it as a text to allow users to manually copy and paste for future issues)

**Comment by keepassium** [comment]
Thank you for the suggestion.

On my phone, these steps make the AutoFill show the file as "? / The file doesn't exist". Is it different on your device?

This is the intended behavior. I think it would be much more confusing if the file simply disappeared. (Especially given that some storage providers may return "file not found" in offline state). 

Of course, it would be convenient to save an extra swipe for removing obsolete file references. However, avoiding the risk of "aah, my database is gone without a trace!" seems more important.

**Comment by Dragonblitz10** [comment]
Fair enough on my device it just generated the "plugIn error" which doesn't seem to replicate and I could not copy the diagnostic log so hence I suggested that option

**Comment by keepassium** [comment]
Ok, so this issue can be closed, it seems. The diagnostic copying bug is moved into a separate issue #16. Thanks for reporting!
