### ISSUE TITLE
Unreliable sync via Synology Drive

### ISSUE THREAD

**Issue by leochras** [keepassium/KeePassium#154]
**Description**
Everytime I change my file on another device and it gets synced to my iPhone, all the TOTP entries are gone. I don't know if it's KeePassium, but it certainly could be.

**How to reproduce**
1.  I set up a TOTP in Keepassium 
2. I changed my Keepass File (.kdbx) in KeePassXC on Windows 10 and my Synology Drive Client syncs it to my NAS.
2. My Phone syncs to the local file, I open it in KeePassium and see that the TOTP entries are gone.

**Expected behavior**
TOTP is something I really don't want to set up everytime I change my KeePass file,

**Screenshots**

**Environment:**
 - Device: iPhone XR
 - OS: iOS 14.4.2
 - App Version: 1.23.85
 
**Additional context**

**Comment by keepassium** [comment]
TOTP parameters are saved in custom fields. Are these fields still there?

**Comment by leochras** [comment]
I don't think so, because when I edit an entry, where I know there was a TOTP setup before, it says: "Setup one-time password (OTP)". I also can't see costum fields anywhere in KeePassXC.

**Comment by keepassium** [comment]
> I also can't see costum fields anywhere in KeePassXC.

When you set up TOTP in KeePassXC, it adds a custom field named `otp`. To see it, start editing the entry → Advanced → Additional attributes.

**Comment by leochras** [comment]
I set up the TOTP in KeePassium. There is no field called otp in this entry.

**Comment by keepassium** [comment]
Ok, I am confused... 

In "Steps to reproduce" you wrote that TOTP entries are gone after the database is edited in KeePassXC. 

Now you write that `otp` field does not appear after you set up TOTP in KeePassium. 
- Do you mean it did not appear in KeePassium? (That is, TOTP setup is broken.) 
- Or do you mean it did not appear in KeePassXC? (That is, synchronization is broken.)

Also, if you edit an entry manually (add a note or something) — do you see these changes in KeePassXC?

**Comment by leochras** [comment]
I set up a TOTP in Keepassium a while ago. I synced it to my NAS.  Then I edited the password for that entry in KeePassXC and synced it again. When I opened it in Keepassium, the password changed but the OTP field was gone. I did not bother to look at the fields in KeePassXC until now but there are no custom fields or anything if that is what you mean:
![image](https://user-images.githubusercontent.com/16163571/113928718-6f95d380-97ef-11eb-9f7e-30f6b26b0648.png)

**Comment by keepassium** [comment]
Thanks, it is clearer now.

I guess this is a sync issue. Once you set up TOTP in KeePassium and saved the database, Synology Drive app failed to upload the updated database to the NAS. So the file you opened in KeePassXC was an old version. When you edited the database in KeePassXC, it saved the file to the NAS. And apparently this time Synology Drive did download the server's copy (and overwrote the changes made by KeePassium). 

Unfortunately, after the full round (KeePassium→ KeePassXC → KeePassium) it is impossible to figure out which link is broken.

I would suggest to check the database when you open it in KeePassXC (at the start of step 2). Does file modification date/size match those shown in KeePassium? If yes, does the database contain the `otp` field _before_ you edit it with KeePassXC?

**Comment by leochras** [comment]
I think I found the problem. KeePassium reads changes made to the file but doesn't (or can't) really write them. When I change something in KeePassXC, it syncs, at least after a while. When I change something in KeePassium. the last changes made date is correct, but when I look into my Files app and the Synology Drive app, it doesn't. 

![WhatsApp Image 2021-04-08 at 08 30 27](https://user-images.githubusercontent.com/16163571/113978931-e01b0f80-9844-11eb-838b-0222e6ba462a.jpeg)

![WhatsApp Image 2021-04-08 at 08 30 49](https://user-images.githubusercontent.com/16163571/113978938-e3160000-9844-11eb-8a08-d5061b53a774.jpeg)

![WhatsApp Image 2021-04-08 at 08 31 08](https://user-images.githubusercontent.com/16163571/113978942-e5785a00-9844-11eb-8c34-58c35fdf4f2d.jpeg)

**Comment by keepassium** [comment]
Ok, so this is just another issue with Synology Drive. There was a [known issue](https://keepassium.com/articles/sync-ios-keepass-with-synology-nas/#known-issues) with Synology Drive's caching, where it uploaded mobile changes but did not refresh the cached file it served to KeePassium. Apparently, the problem can go both ways. 

As a solution, use DS File instead of Synology Drive. Or better avoid Synology apps altogether and [integrate your NAS via WebDAV protocol](https://keepassium.com/articles/sync-ios-keepass-with-webdav/).

**Comment by leochras** [comment]
I now changed to WebDAV and it works great! Sorry for bothering you, it really is Synology's fault it didn't work.
