### ISSUE TITLE
Password generator in menu and/or for additional fields

### ISSUE THREAD

**Issue by loeffelpan** [keepassium/KeePassium#155]
I just wanted to create a PIN (4 numeric digits) in addition to my passwort.
There is no way to generate that PIN in KeePassium, is it? Password generator is only available when filling password field.

Other password clients offer the password generator entry-independent in menu. Maybe you will make it available (as for passwords) for additional fields.

**Comment by keepassium** [comment]
Good point, thanks!

**Comment by martinsstuff** [comment]
Just wanted to voice my support for a "standalone" password generation menu, I occasionally have to generate stuff like PINs or passwords that I don't need to save where I wish this was an option.

**Comment by loeffelpan** [comment]
I like!

**Comment by keepassium** [comment]
Just cleaning up… I guess we can consider this done :)
