### ISSUE TITLE
Synology DS file (v 5.15.0) fails to provide files

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#156]
**Description**

When you add a database from Synology DS file app, the file either fails to open immediately or after a few seconds. KeePassium shows "Synology DS file does not respond".

This started with DS file v 5.15.0 (released on 2021-04-13), previous versions work ok.

**Steps to reproduce**
1. Open KeePassium
2. Tap `Add Existing Database`
3. Select database from DS File
4. Wait 10 seconds
5. Try to unlock the database
6. KeePassium immediately shows "Synology DS file does not respond"

**Expected behavior**
KeePassium should open the database.

**Environment:**
 - DS file version: 5.15.0
 - Device: all iPhones and iPads
 - OS: iOS 14.4.2
 - App Version: 1.23.85

**Error logs**

<details>
<summary>Error info returned by iOS to KeePassium</summary>

    Error Domain=NSCocoaErrorDomain 
    Code=4099 
    "Error while sending URLForItemID:creatingPlaceholderIfMissing:ignoreAlternateContentsURL:completionHandler:" 
    UserInfo={
        NSDebugDescription=Error while sending URLForItemID:creatingPlaceholderIfMissing:ignoreAlternateContentsURL:completionHandler:,
        NSUnderlyingError=0x283d53360 {
            Error Domain=NSCocoaErrorDomain 
            Code=4099 
            "The connection on anonymousListener or serviceListener from pid 32259 was invalidated from this process." 
            UserInfo={
                NSDebugDescription=The connection on anonymousListener or serviceListener from pid 32259 was invalidated from this process.
            }
        }
    }

</details>

<details>
<summary>DS file exception info recorded by the Console app</summary>

    fault   21:52:14.173615+0200    com.synology.DSfile.ExtFileProvider <NSXPCConnection: 0x1044c0ed0> connection to service on pid 201 created from an endpoint: Warning: Exception caught during invocation of selector startProvidingItemAtURL:readingOptions:completionHandler:, dropping incoming message and invalidating the connection.
    Exception: -[ExtBackgroundTaskManager presenter]: unrecognized selector sent to instance 0x10451c240
    -[ExtBackgroundTaskManager presenter]: unrecognized selector sent to instance 0x10451c240
    (
        0   CoreFoundation                      0x00000001ad1f59ec F3021642-E3C0-33F8-9911-DD303A6056D0 + 1157612
        1   libobjc.A.dylib                     0x00000001c1578b54 objc_exception_throw + 56
        2   CoreFoundation                      0x00000001ad105bbc F3021642-E3C0-33F8-9911-DD303A6056D0 + 175036
        3   CoreFoundation                      0x00000001ad1f7d58 F3021642-E3C0-33F8-9911-DD303A6056D0 + 1166680
        4   CoreFoundation                      0x00000001ad1f9f8c _CF_forwarding_prep_0 + 92
        5   com.synology.DSfile.ExtFileProvider 0x00000001001d4a28 com.synology.DSfile.ExtFileProvider + 51752
        6   com.synology.DSfile.ExtFileProvider 0x00000001001d82c0 com.synology.DSfile.ExtFileProvider + 66240
        7   com.synology.DSfile.ExtFileProvider 0x00000001001eae20 com.synology.DSfile.ExtFileProvider + 142880
        8   com.synology.DSfile.ExtFileProvider 0x00000001001ea98c com.synology.DSfile.ExtFileProvider + 141708
        9   com.synology.DSfile.ExtFileProvider 0x00000001001ed2c8 com.synology.DSfile.ExtFileProvider + 152264
        10  FileProvider                        0x00000001c1f0d5a0 9FCA752E-2E8F-3A52-BEF8-65ACD263D21C + 21920
        11  CoreFoundation                      0x00000001ad1fa130 F3021642-E3C0-33F8-9911-DD303A6056D0 + 1175856
        12  CoreFoundation                      0x00000001ad0dd1d0 F3021642-E3C0-33F8-9911-DD303A6056D0 + 8656
        13  Foundation                          0x00000001ae594a00 712A564E-5058-3EAC-AF3A-43BBD43D0D7E + 2152960
        14  Foundation                          0x00000001ae3d1dec 712A564E-5058-3EAC-AF3A-43BBD43D0D7E + 306668
        15  Foundation                          0x00000001ae594b54 712A564E-5058-3EAC-AF3A-43BBD43D0D7E + 2153300
        16  libxpc.dylib                        0x00000001f59fa128 9B754030-D4B6-3814-8840-D3DAC9C54212 + 53544
        17  libxpc.dylib                        0x00000001f59fa4a4 9B754030-D4B6-3814-8840-D3DAC9C54212 + 54436
        18  libdispatch.dylib                   0x00000001ace2e340 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 398144
        19  libdispatch.dylib                   0x00000001acde7c30 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 109616
        20  libdispatch.dylib                   0x00000001acdd6c94 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 40084
        21  libdispatch.dylib                   0x00000001acde8838 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 112696
        22  libdispatch.dylib                   0x00000001acdd6c94 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 40084
        23  libdispatch.dylib                   0x00000001acdd78d8 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 43224
        24  libdispatch.dylib                   0x00000001acde1338 AF27E74C-BE4A-3364-BB27-AED9916CE02D + 82744
        25  libsystem_pthread.dylib             0x00000001f59d95a4 _pthread_wqthread + 272
        26  libsystem_pthread.dylib             0x00000001f59dc874 start_wqthread + 8
    )

</details>

**Additional context**

This is a Synology bug, it cannot be fixed on KeePassium's side. The bug was reported to Synology (ticket 2781532)

As a workaround, you can connect your NAS to iOS using one of the alternative methods:
- As a network drive: 
  - [Enable SMB protocol on the server](https://www.synology.com/en-uk/knowledgebase/DSM/help/DSM/AdminCenter/file_winmacnfs_win)
  - Open iOS Files app → tap "..." in top-right corner → Connect to Server → enter your NAS address and access credentials
- As WebDAV server:
  - [Enable WebDAV protocol on the server](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/File_Sharing/How_to_access_files_on_Synology_NAS_with_WebDAV)
  - Install [Boxcryptor](https://apps.apple.com/app/boxcryptor/id649940870) app — it is free for two devices and encryption is optional. You would have to create a Boxcryptor account, though... 
  - Add your NAS to Boxcryptor
  - Open iOS Files app and [make Boxcryptor visible](https://support.apple.com/en-us/HT206481#thirdparty) as a storage location

**Comment by keepassium** [comment]
After some experiments, there is an interesting detail.

Files served by `DS file` are accessible only during a short 10-second interval (5 seconds before and 5 seconds after the time the file was selected in the file dialog). During this period, the file can be opened normally. Before or after that period, `DS file`'s file provider extension crashes as described above.

Steps to reproduce:
- Add a database from `DS file` to KeePassium. Note the exact time _T<sub>0</sub>_, including seconds.
- Once KeePassium starts showing the error, rewind system time
- Refresh the database list repeatedly. 
  - Test file will become accessible at _T<sub>0</sub>_-5 and remain accessible until _T<sub>0</sub>_+5.

**Comment by keepassium** [comment]
Synology acknowledged the issue:

> After our development team investigated this behavior, they found that this problem might be caused by the open function of the Document Provider.
>
> When the file is accessed through DS File by other APPs, it will have two modes which are Open and Export and the problem will occur only in the Open mode of the APP.
>
> So, there is no solution for this problem now, but here is a solution to avoid it:
>
> [1] Access the file from Synology Drive app instead of DS File.
> [2] Access DS file as local file：
> Step 1. Download the document from DS file
> Step 2. Open the APP, open my iPhone> choose the documents from DS File Folder.  
> Step 3. After editing the documents on the APP, open DS file to upload the edited document to NAS. (Choose upload from the local file).
>
>This known issue will be analyzed and fixed in future updates.

Solution 1 won't work because Synology Drive has been [broken](https://keepassium.com/articles/sync-ios-keepass-with-synology-nas/#known-issues) for a couple of years now — it does not update on-device cached copy once the file has changed on the server. This was confirmed by Synology devs on 2020-09-01, in ticket 2604475:
> Upon further inspection, our developer confirmed that on some occasions, when using the iOS Files app to browse files on Drive, it does not show the latest version of the files.
> They are currently working on a fix that will be released on a later date.

Solution 2 means downloading and uploading files manually via DS File app. Which is quite a step down from the automatic sync in the previous version of DS File. 

At this stage, the fix is up to Synology. Feel free to [contact them](https://www.synology.com/en-global/support) and ask them to prioritize the issue (ticket 2781532).

**Comment by keepassium** [comment]
According to several reports, the bug is fixed in DS File 5.15.1 beta.

**Comment by mmtffm** [comment]
Any ideas when 5.15.1 will be released?

**Comment by keepassium** [comment]
@mmtffm , I believe Synology is better equipped to answer this question.

**Comment by keepassium** [comment]
Good news! DS file 5.15.1 works properly again. It was released on 31 Aug 2021.

**Comment by mmtffm** [comment]
Thanks for the information.
Synology wasn't able to tell when the update will be released....
Finally the did.

Regads

**Comment by keepassium** [comment]
> Synology wasn't able to tell when the update will be released.... Finally the did.

If only... Synology did not bother to follow up on bug report, I received an email from a user (thanks, Michael!)
