### ISSUE TITLE
Ability to search database for an entry

### ISSUE THREAD

**Issue by fgimian** [keepassium/KeePassium#157]
**Describe the feature you'd like**
Hey there, Strongbox offers the ability to search for any entry in your database using a search box.  I have close to 400 entries in my database so this comes in very handy when I'm logging into an app where iOS doesn't detect the right entry.

This would greatly speed me up when trying to find the item I'm after 😄

**Comment by fgimian** [comment]
I totally missed the fact you can pull down from the top to reveal a Search box.  Oopsies!

I'll close this issue now and just pretend that never happened 😄 
Fotis

**Comment by keepassium** [comment]
Yeah, it’s pretty much a standard iOS gesture :)

**Comment by fgimian** [comment]
> 
> 
> Yeah, it’s pretty much a standard iOS gesture :)

I have no idea why I didn't to try it, so sorry about that 😄
