### ISSUE TITLE
Additional Face ID prompts after a failed attempt

### ISSUE THREAD

**Issue by fgimian** [keepassium/KeePassium#158]
**Description**
When using Face ID for authentication and auth fails (e.g. if you're not looking at the camera properly), the app then tries to check Face ID multiple times in order to successfully let you in.

**How to reproduce**
1. Enable Face ID in Keepassium
2. Lock your database
3. When prompted to authenticate with Face ID, put a hand in front of your face or similar to force it to fail
4. You will now be prompted to try again which you should do normally
5. Notice that the app performs a Face ID authentication TWICE after a failed attempt

**Expected behavior**
After a failed Face ID attempt, only a single successful further attempt should be required to unlock the app.

**Screenshots**
N/A

**Environment:**
 - Device: iPhone XR
 - OS: iOS 14.4.2
 - App Version: 1.23.85

**Additional context**
N/A

**Comment by keepassium** [comment]
Thanks! 

Yes, it's a known issue... Over three iOS versions, Face ID prompt behaves slightly differently. I have been patching the most outrageous issues, and now App Protection logic is a plate of spaghetti. In the current app architecture, fixing a minor issue like this would likely introduce a few larger ones. 

I am refactoring the app now. It will take some time, but it will also make it easier to improve the app further. Once done, I will make sure to address this issue as well.

**Comment by fgimian** [comment]
Thanks a lot, looking forward to it 😄

**Comment by fgimian** [comment]
Hey there, sorry to be a bother but was just wondering if you've had any luck with this issue? 😄

**Comment by keepassium** [comment]
Still in that refactoring...

**Comment by fgimian** [comment]
> 
> 
> Still in that refactoring :(

No worries at all, good luck! 😄

**Comment by fgimian** [comment]
Thanks so much for fixing this one! 😄
