### ISSUE TITLE
Feature Request: Download website icon (favicon) for entries

### ISSUE THREAD

**Issue by gtdm** [keepassium/KeePassium#164]
**Describe the feature you'd like**
Download a website's favicon and add it as a custom icon of that entry. KeePassXC has this functionality and it's a massive QoL improvement.

**Comment by keepassium** [comment]
Thank you for the suggestion! I am afraid, this would not be possible, though.

KeePassium is an [offline app](https://keepassium.com/articles/can-i-trust-keepassium/). This was one of the key design decisions, and this is critically important for some users. That’s why KeePassium itself does not perform any network communications directly (synchronization is [delegated](https://keepassium.com/articles/cloud-sync-sandboxing/) to specialized apps).

This way, KeePassium does not have any network traffic — but more importantly, it does not have any plausible excuses either. (“Oh, this unexplained connection to 50 different websites? The app accidentally tried to download their favicons. Nothing else.”) The only exception is the connection to the AppStore in the freemium app, to handle in-app purchases. KeePassium Pro does not do that, so it stays offline in any case.

As a result, KeePassium cannot have any network-dependent feature, such as favicon downloader.

**Comment by telroy** [comment]
Whoops! That's right, I didn't consider that at all before creating this request.

**Comment by keepassium** [comment]
No worries :) I'll close this then.

**Comment by SlowNicoFish** [comment]
Could this be possible now considering the new internet access setting?

**Comment by keepassium** [comment]
Yes!
