### ISSUE TITLE
Add a search option

### ISSUE THREAD

**Issue by alexvas** [keepassium/KeePassium#165]
It would be nice to add a search option, because password entries are actually a large hierarchical structure. It is not possible to remember the entry placement.![image](https://user-images.githubusercontent.com/152694/119217350-dc490100-bb03-11eb-89bb-f7828d4f0c6c.jpeg)

**Comment by cryptosteve2** [comment]
Just swipe down ...

**Comment by alexvas** [comment]
FAQ entry would be nice then. Thanks!

**Comment by keepassium** [comment]
@alexvas , "swipe down to search" is a standard iOS gesture. It works in Mail, Settings and even [in the Home screen](https://support.apple.com/HT201285). So adding it to the FAQ would have been excessive.

That said, you are not alone asking about it (#157, plus a few emails). Which means there are many more people who never asked and simply think there is no search. Which makes it a valid UX problem. I will make the search field visible by default, to make this feature more prominent.

In the meanwhile, you might want to check KeePassium settings → Search → Start with Search ;)

**Comment by alexvas** [comment]
Yep. Just bought my first iPad yesterday.
