### ISSUE TITLE
Ability to exclude entries from AutoFill search results

### ISSUE THREAD

**Issue by azfar** [keepassium/KeePassium#166]
Is there any way to exclude some entries from auto search results, I have some credentials applicable to same domain but only one of them is primary which I want to appear in autosearch.

**Comment by keepassium** [comment]
At the moment, such an ability exists but almost as a side effect: KeePassium respects the "Hide this entry from the extension" flag set in KeePassXC (#100).

But it would be nice to set this flag directly in KeePassium, so I would keep this open. Thanks!

**Comment by keepassium** [comment]
Done in 1.48.142 in Dec 2023, forgot to close back then…
