### ISSUE TITLE
Edit Entry Form Discombobulation

### ISSUE THREAD

**Issue by NormanJDavisJr** [keepassium/KeePassium#167]
I was editing an entry. Everything looked normal at first, but then several fields showed up as deep red, and when adding a field it showed up above URL field. Pressing Done did not work, neither did cancel. Had to close app and restart it.  

This was an entry in a Google Drive database created with KeePassium.

Have not been able to reproduce. This was my first time using KeePassium. I regularly use KeePass 2 on Windows.

![image](https://user-images.githubusercontent.com/40545553/122121208-375ad480-cde0-11eb-8c2e-3d3a5fded7f0.png)

**Environment:**
 - Device: iPhone 12 Pro Max
 - OS: ios 14.6
 - App Version: v1.24.87 (That is version as of today, This problem happened 4 days ago, so maybe it was different then.)

**Comment by keepassium** [comment]
Thank you, @NormanJDavisJr . Yes, this does not seem right... I will look into it.

**Comment by keepassium** [comment]
There were no other reports, so probably it got accidentally fixed somewhere during these three years. Closing.
