### ISSUE TITLE
Having problem accessing google drive shared files when offline

### ISSUE THREAD

**Issue by Thunder33345** [keepassium/KeePassium#17]
repro:
pre conditions:
- have google drive, enable file sharing and has it as your file storage

other notes:
- i have marked this file as available offline in gdrive
- make sure it's the file sharing system, and to open the file from gdrive, NOT THE share to system(the file location should be "Another App/Cloud Storage"

repro steps:
- (assume normal successful usage before this)
- disconnect from internet
- open app
- try to unlock the database
- get error "Cannot open database file, The plug-in returned an error."

expected result:
- the file opens normally

diag logs:
- DatabaseManager.swift:742 load()
Failed to open database document [error:The plug-in returned an error]

**I am not sure if this is fault on keepassium or google drive**
probably worth investigating, and if it's google drive fault, if possible add a note that tell user to use another cloud storage app

**Comment by anmipo** [comment]
Yep, files marked as "Available offline" are only available offline from the GDrive app itself. In the Files app, GDrive appears as "Content unavailable". KeePassium also cannot access it.

I have already [documented](https://keepassium.com/articles/sync-ios-keepass-with-google-drive/) this in the FAQ. Given that it's a GDrive issue, there is not much I can do here...
