### ISSUE TITLE
New Feature: Password Quality Indicator

### ISSUE THREAD

**Issue by FlightMS** [keepassium/KeePassium#170]
I would like to create new passwords and see directly, if the new password is too weak for normal all day use.

Can you implement a Password Quality Indicator to show that the new password is secure enough or even not?

![An-example-of-password-strength-indicators](https://user-images.githubusercontent.com/82420268/123432323-8cf66480-d5ca-11eb-8144-96344279a024.png)

This would help to get stronger passwords.

**Comment by keepassium** [comment]
Good point, thanks!

**Comment by vit9696** [comment]
I would also like this to make its way into sorting, so that one can sort by 'password quality' and/or 'password age'.

**Comment by aashrithh** [comment]
+1
It’d would be really great to have this feature implemented.
