### ISSUE TITLE
Can't open existing database file in Dropbox (iOS 14.6)

### ISSUE THREAD

**Issue by lucianodinapoli** [keepassium/KeePassium#171]
**Description**
Keepassium can't open or add files from Dropbox.

**How to reproduce**
If I open Keepassium, the existing database is not accessible. It gives me a "Couldn't communicate with a helper application" error.
I also tried:
1- Removing existing database in Keepassium 
2- "Open Database"
3- Tap on Dropbox in the "Locations".
4- I get "Content Unavailable - The folder contents could not be displayed because of an unknown error."
5- Tapping "Try Again" does nothing.

**Expected behavior**
The existing file should've opened normally, and it should be possible to re-add it from Dropbox. It worked just a day ago.

**Environment:**
 - Device: [iPhone 12]
 - OS: [iOS14.6]
 - App Version: [1.24.87]

**Additional context**
This was a database that I use all the time, never had any issues with it. I have been opening this file exclusively on the iPhone for the past couple of months.

**Comment by keepassium** [comment]
Hi, thanks for the report. The error message sounds like a [known system glitch](https://keepassium.com/articles/file-picker-content-unavailable-error/). Try to restart your phone and it should work again.

**Comment by lucianodinapoli** [comment]
Oh I didn't find that glitch when I searched for a solution. Restarting worked, thanks!
I'll close the issue since it also happens with other apps (Google Drive)
