### ISSUE TITLE
Feature Request: Mac Version should support file export and/or file preview  

### ISSUE THREAD

**Issue by layandreas** [keepassium/KeePassium#174]
**Describe the feature you'd like**

On Mac, files can only be airdropped: 

![image](https://user-images.githubusercontent.com/79149948/128836363-45e1ccb3-8cd6-418c-84ac-d6a92f26f74a.png)

Add support for file download and file preview for text files / pictures.

**Comment by keepassium** [comment]
Yes, macOS' standard export sheet is rather minimalistic... I will look into it. Thanks!
