### ISSUE TITLE
MacOS: no entries found

### ISSUE THREAD

**Issue by cryptosteve2** [keepassium/KeePassium#176]
**Description**
I'm using the newest version on MacOS Big Sur. When I try to log in to a website, the best result is not automatically shown to me. 

Only when I search for it, the matching hit is displayed.

**How to reproduce**
1. try to insert credentials via keepassium at the twitter login page
2. no entries shown -> search for site name
3. credentials found ...

see attachments ... sorry for german language, please let me know if you need english language settings ..

**Environment:**
 - Device: MBP M1 16gb
 - OS: MacOS Big Sur v11.5.2
 - App Version: 1.25.90
 
<img width="416" alt="20210819@114908_screenshot_KeePassium" src="https://user-images.githubusercontent.com/6260784/130048605-d8ba3d78-8555-4c46-8b7e-0dcf19172ed3.png">
<img width="422" alt="20210819@114728_screenshot_Safari" src="https://user-images.githubusercontent.com/6260784/130048635-dd1e8e87-9359-4b41-b022-0bb51da312a2.png">
<img width="417" alt="20210819@114750_screenshot_Safari" src="https://user-images.githubusercontent.com/6260784/130048656-e2003fd6-e8fd-4b7a-a793-831572ec7784.png">

**Comment by keepassium** [comment]
Yep, it's a regression in the recent beta. I will upload the fix later today.

**Comment by keepassium** [comment]
Done! Fixed in [1.25.91](https://github.com/keepassium/KeePassium/releases/tag/1.25.91). Thank you for the report!
