### ISSUE TITLE
"Onboarding flow" gets you "stuck" in a loop (unintuitive UI)

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#18]
Sorry for slacking off for a while, but switching jobs and transitioning to a new phone took its time! :)

The good thing is that this meant that I went through the process of setting the app up from scratch again, where I found a slight hickup in the UX.

On the welcome page you get a good description of what you need to do, but when going through the "Add Existing Database" process and selecting the database file, you end up on the same Welcome page, without any indication of success or failure, or suggestion on the way forward. I performed the same procedure twice, and was just about to do it a third, before realizing I was stuck in a loop.

I guess before proper release the onboarding process will be polished a bit, so this may not be applicable for the long term, but a small suggestion meanwhile could be instead of going back to the welcome screen make the user go to the database selection screen, maybe with a "overlay" pointing to the top right plus sign for adding more databases to the app?

**Comment by keepassium** [comment]
Absolutely! This is a very annoying glitch that will be solved by better onboarding process.

Thanks for reporting!
