### ISSUE TITLE
Bottom bar icons cannot be accessed from the keyboard

### ISSUE THREAD

**Issue by vit9696** [keepassium/KeePassium#183]
**Description**
Bottom bar icons like sorting or settings can be selected with `TAB` but cannot be triggered with the keyboard (e.g. with `Enter` or `Space`).

**How to reproduce**

1. Enable keyboard navigation over all elements (System Preferences → Keyboard → Shortcuts → set the tick to use keyboard navigation to move focus between controls).
2. Open KeePassium.
3. Press `TAB` to access settings icon in the bottom left corner.
4. Pressing `Space` or `Enter` will not open settings.

**Expected behavior**
Settings should open.

**Screenshots**
<img width="706" alt="Screenshot 2021-08-22 at 18 30 52" src="https://user-images.githubusercontent.com/4348897/130360961-10c1407f-80a8-47a9-ba7a-76e8cbde102e.png">

**Environment:**
 - Device: Mac
 - OS: macOS 11.5.1
 - App Version: master

**Additional context**
I wonder if it is a bug in Mac Catalyst. Might require reworking the buttons in this case.

**Comment by keepassium** [comment]
Thanks! I would argue this is a Catalyst ~bug~ shortcoming. Apple is introducing [focus-based keyboard navigation](https://developer.apple.com/documentation/uikit/uikeycommand/navigating_an_app_s_user_interface_using_a_keyboard) in iOS/MacCatalyst 15, so there is a good chance it will just start working on the upcoming macOS 12.

I will revise after macOS update.
