### ISSUE TITLE
Cannot save files on macOS

### ISSUE THREAD

**Issue by vit9696** [keepassium/KeePassium#189]
**Description**
I have binary attachments in the database in some entries, yet I cannot save them. KeePassium allows me to preview these files with quick look, but there is no save as button anywhere.

**How to reproduce**
1. Have a database with an entry containing 1.bin file.
2. Double click on the file, quick look will show with a suggestion to open file in Notes, but no way to save.
3. Open context menu for the file, only rename and delete will be suggested without save as.

**Expected behavior**
Both quick look and context menu should suggest saving files on the file system.

**Screenshots**
Rather self-explanatory.

**Environment:**
 - Device: Mac
 - OS: macOS 11.5.2
 - App Version: master

**Additional context**
Perhaps it will be harder to modify quick look, but for the context menu it should be rather doable. Feels like a bug to me as there is literally no sane way to get to the file.

**Comment by keepassium** [comment]
Hmm, indeed...  I thought I already fixed this in #174, because file preview panel shows "Open in *AppName*". Apparently, this works only for most common file types (images, documents, archives).

I'll get this fixed, thanks!
