### ISSUE TITLE
View all items at once

### ISSUE THREAD

**Issue by vit9696** [keepassium/KeePassium#190]
**What can be improved?**
Currently you can only view the items from each category separately, however, when sorting by creation date it may be very useful to have a single list that will show all the items regardless of their group and type.

**The solution you'd like**
It will be nice to have an `All items` view that would show all the items from all the groups in one list.

**Alternatives you've considered**
There is search, but it requires extra steps to use.

**Additional context**
This feature may be related to grouping as explained in https://github.com/keepassium/KeePassium/issues/186.

**Comment by keepassium** [comment]
Thanks. I will consider this alongside #186 but with rather low priority, I'm afraid...

**Comment by keepassium** [comment]
Added in 1.53.154 (now in beta) via [smart group](https://support.keepassium.com/docs/smart-groups/) with `is:entry` condition (de939932cf7c3b28f8877d283510245ed9f2d979). 
Also, this is one of the standard smart group presets :)
