### ISSUE TITLE
Text replacement works in password fields in macOS

### ISSUE THREAD

**Issue by mitchellchan** [keepassium/KeePassium#191]
**Description**
When entered the password to unlock the database, system text replacement occurred if you have it. For example, if your password is "omy", the text will be replaced with "On my way!" 

**How to reproduce**
1. Go to 'Password field' to unlock database
2. Tap on 'eye' to reveal password
3. Enter 'omw'

**Expected behaviour**
Enter password without text replacement.

**Screenshots**
![CleanShot 2021-09-06 at 13 16 17@2x](https://user-images.githubusercontent.com/143933/132164389-466f7db8-bd5c-45ec-8194-675cc26c73f7.png)

**Environment:**
 - Device: [M1 Mac mini]
 - OS: [12.0 Beta (21A5304g)]
 - App Version: [v1.25.93]

**Comment by keepassium** [comment]
Thank you for the feedback.

This is the standard system behavior:
- With the password hidden, text replacement does not work, and you can only paste from clipboard.
- With the password shown, the input field is no different to any other text input in the system: text replacement, all clipboard operations, spelling/grammar — all the standard text functionality.

**Comment by mitchellchan** [comment]
With the password hidden, text replacement still show up.
![CleanShot 2021-09-06 at 17 39 59](https://user-images.githubusercontent.com/143933/132196927-ef12faea-4e59-44a6-a383-0a2fd4e0607d.gif)

If the password has charaters like @ and #, it will expand automatically.
![CleanShot 2021-09-06 at 17 41 54](https://user-images.githubusercontent.com/143933/132196978-7a4cc49e-27da-4c25-b2ed-d65e10f618b1.gif)
Sorry for the poor quality of second gif, I have tried several times but the quality cannot be as good as gif 1.

**Comment by keepassium** [comment]
Thanks for the gifs! You are right, there's something wrong.. 

I could not reproduce this on 11.4, so was almost ready to dismiss as a macOS 12 beta bug. However, the issue does happen on macOS 11.5.2 — and only in KeePassium. So yes, seems like a bug. Thank you for insisting! :)

**Comment by keepassium** [comment]
After various fix attempts on KeePassium's side, I believe this is a Mac Catalyst bug. Reported it to Apple: [rdar://FB9821716](http://www.openradar.me/radar?id=4984370167283712)
