### ISSUE TITLE
Can’t unlock auto fill panel with TouchID 

### ISSUE THREAD

**Issue by martinsstuff** [keepassium/KeePassium#192]
**Description**
Presumably since the last update (it just started happening, worked fine before) I can’t unlock the autofill panel using TouchID

**How to reproduce**
1. Attempt to use the autofill feature with App Lock enabled.

**Expected behavior**

I should just work™

**Screenshots**

Video of the bug: https://streamable.com/tuwkjc

Note that me entering the password is “invisible” in the recording, only he keypresses can be heard, presumably a safety measure from Apple’s side.

**Environment:**
 - Device: [e.g. iPhone 12] iPad 7th gen.
 - OS: [e.g. iOS14.4] iPad OS 14.7.1
 - App Version: [e.g. 1.23.45] v1.25

**Additional context**

I tried removing the database and reinstalling the app without success.

**Comment by martinsstuff** [comment]
Whoops, I accidentally hit send… I will edit in the details in a moment.

**Comment by keepassium** [comment]
Yep, this came up after I released 1.25... I have paused the phased rollout, but this only affects automatic updates... 

This bug is already [fixed](https://github.com/keepassium/KeePassium/commit/edeab54b0908db70c7d737f8a728426f31e9e154) and the update is waiting for Apple's approval.

**Comment by martinsstuff** [comment]
As a workaround, setting the App Lock timeout to 3 seconds seems to work.

**Comment by keepassium** [comment]
Good point, Martin, thanks for sharing!

**Comment by keepassium** [comment]
The update with the fix is now available in the App Store. Hopefully won't need to reopen :)
