### ISSUE TITLE
Unable to use iOS keychain to input master password

### ISSUE THREAD

**Issue by VictorSu000** [keepassium/KeePassium#198]
**Description**
I saved my master password in iOS keychain. In a previous app version, I can input that password via keychain, no need to enter a long password myself. But after updating KeePassium and iOS, I can't do so.

**Expected behavior**
![image](https://user-images.githubusercontent.com/18596923/135045482-ce073ef2-4a7b-47c0-ab26-f78306509c92.png)

**Environment:**
 - Device: iPhone 8 Plus
 - OS: iOS 15.0
 - App Version: 1.26.94

**Additional context**
This problem happens after I update both KeePassium and iOS, so I'm not sure which causes it.

I have a very long master password and rely on iOS keychain. I would be really appreciate it if this problem can be fixed. Thank you so much!

**Comment by keepassium** [comment]
Hi, thank you for the feedback. The integration with Keychain AutoFill was blocked intentionally, for several reasons. 

The main reason is that it was dangerously confusing for beginners. When they created their first database, Keychain conveniently suggested to generate and save a password. So their database was encrypted with the password the user did not know. Many even did not realize their database had a password. Later on, Keychain sometimes "updated" the saved database password with data from a random DB entry. (Keychain does not keep any history.)

So the unsuspecting user eventually discovered that 1) they don't know database password, 2) don't even know there was one, 3) that password was overwritten by the keychain. Understandably, this caused a lot of pain.

Another reason is that I could not find any useful reason to accept input from the Keychain AutoFill. KeePassium can already store database password (app settings → Data Protection → Remember Master Keys).

Could you please tell me why you need to store database password in iOS Keychain?

**Comment by VictorSu000** [comment]
Thanks for your explanation.

I store my database file in a WebDav service, so that I can sync my file from different devices. But I can't figure out a good way to use WebDav+KeePassium in iOS, so I finally save a backup of my db file in iCloud. Each time I update my database via other platform, I will also update it in iCloud. 

Now the problem comes. Because the file in iCloud is changed, I need to remove the database saved in KeePassium and add it again, which causes me to retype master password.

Maybe there's a more elegant way to use WebDav+KeePassium? Or, is it possible to update database without re-entering master password?

**Comment by keepassium** [comment]
Oh, and accepting AutoFill input will return in the next update as an option (buried at the bottom of the About screen, though)
