### ISSUE TITLE
downward compatibility: macOS High Sierra 10.13

### ISSUE THREAD

**Issue by senilius** [keepassium/KeePassium#199]
Hi Andrei,

How are chances to compile KP macOS for High Sierra 10.13? Any show stoppers in the code?

I thought I ask first before diving into the code.

Thank you very much for your kind help.

Best regards,
Ramon

**Comment by keepassium** [comment]
Hi Ramon,

Yes, I'm afraid there is a major show stopper… 
KeePassium for macOS is based on [Mac Catalyst](https://developer.apple.com/documentation/uikit/mac_catalyst), which was introduced in macOS Catalina (10.15). So theoretically one can compile KeePassium for Catalina (although with some visual defects). For High Sierra, however, you might want to consider [MacPass](https://macpassapp.org) or [KeePassXC](https://keepassxc.org) instead.
