### ISSUE TITLE
Locking while using autofill leads to issues next invokation

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#2]
I've run across another issue when using the Autofill integration within an app (CheapCharts in this case).

I'll start with steps for reproduction:
1. Start app and go to login screen/dialog
2. Start the entry, and push the iOS Passwords bar that shows up
3. Select KeePassium and unlock database (everything so far works as expected)
4. Lock screen
5. Unlock screen, now back at the login dialog of the app
6. Push the Passwords bar again (this is where things starts looking odd)
7. Instead of being prompted for source of password, KeePassium now seems preselected and prompts me for my Touch ID (assuming this is because I've got it enabled as App Lock, with a very short timeout of 15 seconds). As soon as I provide my TouchID login, now I'm prompted whether to use iCloud Keychain or KeePassium.
8. Selecting KeePassium I now arrive at the database unlock screen. Enter master key and unlock.
9. Instead of getting a list in KeePassium I'm now returned to the login dialog inside the app again.

At this stage, everything seems to have "reset", so if you repeat steps 1-3 you will be back in a good state. KeePassium does consider this an  unexpected shutdown, and erroneously points its fingers to the encryption algorithm, which I do not really think had any involvement in the shutdown.

**Comment by magebarf** [comment]
For me, this is reproducible with 100% rate, but I believe there may be some configuration related parameters to this as well, let me know if there's any config-export or log entries you want me to attach/send you.

**Comment by keepassium** [comment]
Yep, I can reproduce this, too. I will take a closer look once I’m back at my dev machine on Monday. Thanks!

**Comment by magebarf** [comment]
I'm not ruling Apple's code out here, as it seems a bit strange to me that the KeePassium prompt for TouchID shows up before even being asked what source to use (iCloud/KeePassium).

I did however try with the only other app autofill enabled app I have, Saaspass, and it does not show the same behavior, working fine repeatedly even when locking the screen after unlocking the database. Saaspass does use TouchID for its main app, but it does not show up when used in the autofill context.

**Comment by keepassium** [comment]
It was a combination of me and Apple :) 

I usually test AutoFill in Safari. There, as soon as AutoFill UI closes, the system kills its process. Apparently, when AutoFill is used in an app, the AutoFill process lives longer. So when you re-open AutoFill and it tries to load the last used database — there is already an open database! This triggered one of the failsafes, and the extension crashed.

@magebarf please let me know if the issue remains in beta 23 and I will reopen. Thanks!

**Comment by magebarf** [comment]
A-OK here!

Issue no longer seen with beta 23!

**Comment by keepassium** [comment]
Great, thanks!
