### ISSUE TITLE
Add support for AutoOpen

### ISSUE THREAD

**Issue by shbach** [keepassium/KeePassium#202]
Would it be possible to add support for AutoOpen? It is sort of similar to [KeeShare](https://github.com/keepassium/KeePassium/issues/138) but seems more widely supported in various clients and has different use cases. Adding support for this would allow easy sharing of passwords between people.

Example implementations:
- [KeePassXC](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening)
- [KeePass](https://keepass.info/plugins.html#keeautoexec)

**Comment by keepassium** [comment]
Yes, a similar feature is already on my list. 

However, the original concept ("open a database and several others would open up as well") might be a bit excessive for mobile use. The screen and memory fit only one DB at a time (two at most). So decrypting several files would be just a waste of battery.

Instead, I see a more manual workflow: select a "special" entry and KeePassium would open a database instead. This way, all the heavy lifting happens on user request only and there is only one DB on the screen at all times. 

Would this work for you?

P.S. Sorry for the delay, I must have missed GitHub's notification…

**Comment by shbach** [comment]
Yeah I think that could work. The main point is streamlining the process of opening another database referenced inside the main database. I don't want to have to manually navigate to the location of the child database as well as manually copy and paste the password from the main database to open it.

**Comment by keepassium** [comment]
Thanks, I am glad this could work. 
While this feature awaits its turn, there's a workaround that might simplify the process:

- Add your "root" database to AutoFill
- Make KeePassium accept input from AutoFill (app settings → About → scroll to the end → Accept input from AutoFill providers → make sure it is checked)
- Now when you open one of your "secondary" databases, you can use AutoFill to enter their credentials.

Admittedly, the workaround is still clunky, but might save a few taps.

**Comment by keepassium** [comment]
Done in 1.53.154 (now in beta) via b6df88422e1ba3e05d52601b86f70a744caa552c
