### ISSUE TITLE
Cannot name new entries on macOS

### ISSUE THREAD

**Issue by fazzer4x** [keepassium/KeePassium#205]
**Description**
When creating a new entry on macOS, it is hard to name the entry. The field cannot be edited at first, but 

**How to reproduce**
Steps to reproduce the behavior (as seen in attached GIF):
1. Click on create new entry
2. Name entry.. upon failure enter username
3. With luck, rename entry at this point.  
4. Otherwise, save the entry and reopen to rename 

**Expected behavior**
Create a new entry and name it. 

**Screenshots**
![failure naming an entry](https://user-images.githubusercontent.com/64558956/143413521-664329c0-5cfd-4b9a-b567-f89c1ef89d0d.gif)

**Environment:**
 Using MacOS 12.0.1
and Keepassium macOS beta 1.28.97

.

**Comment by keepassium** [comment]
Thanks! Ironically, that field is supposed to get focused by default when the dialog opens. I wonder if mouse cursor's hovering nearby has any effect on the focus.

Overall, this seems to be a Monterey thing: I cannot reproduce this on 11.6. I will update my spare machine and look into this.

**Comment by keepassium** [comment]
Hmm, interesting… I have just tested on 12.0.1 and got an exactly opposite behavior: the whole row got selected initially, but then input focus quickly switched to the input field. Mouse cursor did not affect this at all.

https://user-images.githubusercontent.com/38399598/143721974-7911fbbf-4320-4073-a1b9-279aeb6c1a27.mov

Will investigate further.

**Comment by fazzer4x** [comment]
When following your method by using the down key to select new entry, I cannot replicate the behaviour of the input field being selected. Also won't work when pressing cmd + N.

**Comment by fazzer4x** [comment]
Sadly still a bug in Release 1.30.101

**Comment by keepassium** [comment]
@fazzer4x , thanks! Have you tried this on macOS 12.1, by any chance? I suspect this is a Mac Catalyst issue, so macOS update might just magically resolve this…

**Comment by fazzer4x** [comment]
I am on 12.1 atm. The issue seems fixed on 1.30.102. I cannot replicate the erroneous behaviour anymore.

**Comment by keepassium** [comment]
Thanks! On my side, 1.30.101→1.30.102 did not change anything remotely related to this. So I guess the solution should be attributed to 12.0.1 → 12.1 instead :)
