### ISSUE TITLE
Feature request: An option to lock databases after device restart

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#209]
Add an option to lock up the database after device restart, regardless of database timeout.

This would be similar to "Lock on App Launch" in App Protection timeout, but would apply to databases and only on device restart.

[Thanks, Jared]

**Comment by nippar** [comment]
A few months late but, KeePassium monitoring reboots and lock up the database(s) on restarts would be a great option.

**Comment by rghedin** [comment]
I just submitted a refinement request (#231) that goes beyond: to lock the vault/Keepassium when the macOS session is locked.
