### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by martin-bussieres** [keepassium/KeePassium#21]
Search appears to be case sensitive, it makes difficult to find entries particularly with ios auto-caps on.

**Comment by keepassium** [comment]
Yep, there is something strange with the search, especially when there are spaces in the query. I will look into this. Thanks!

**Comment by grrttedwards** [comment]
https://github.com/keepassium/KeePassium/blob/master/KeePassium%20AutoFill/util/SearchHelper.swift#L64

Perhaps this is why? Compare to the way that partial matches are collected above.

**Comment by keepassium** [comment]
@grrttedwards , I am flattered someone actually reads the code 👍 

I guess @martin-bussieres was referring to search in the main app. At the moment the main app does not use `SearchHelper`, but relies on legacy code brought from KeePassB.

One of the causes I found is that the search inside entry fields uses the full query, not separate words (see [EntryField.matches()](https://github.com/keepassium/KeePassium/blob/dd551eb2b384530bf33fd970ab3c8ce93fb98ec5/KeePassiumLib/KeePassiumLib/db/Entry.swift#L50))

@martin-bussieres , I struggle to reproduce the case sensitivity part of the issue, maybe you can give an example? (for example, query "Test" does not find entry titled "MyTest")

**Comment by martin-bussieres** [comment]
Good morning. Yes i was referring to the main search bar.
Test case:
Search for Gmail capital G it leads to 1-2 results
Search for gmail get 100's of result.

Good to know, my keepass format is kdb which is shared through multiple os
linux, windows, android and ios.

Thanks.

**Comment by grrttedwards** [comment]
@keepassium , 

I just took a stab at it 😎

I’m here because KeePassXC now silently upgrades databases to 4.x format... which MiniKeePass can not understand. And, that project is certainly dead by the looks of it.
