### ISSUE TITLE
Mac Autofill on non safari browser

### ISSUE THREAD

**Issue by Churator** [keepassium/KeePassium#210]
Hi,

Love your apps for phone and Mac.
In Mac, I'm using KeePassXC, with browser integration.
I saw Auto-full capability, and loved it, but only supported in Safari AFAIK.

Can it be integrated to Chromium based Microsoft Edge ?

**Comment by keepassium** [comment]
Hi, thanks for reaching out! 

KeePassium already does its part and integrates with macOS as AutoFill provider, the rest is up to Chromium.

But Chromium team [needs convincing](https://bugs.chromium.org/p/chromium/issues/detail?id=1170065):
> I agree that such integration makes sense for a portion of our users. It's not a priority for the team though at the moment.

**Comment by Churator** [comment]
And chrome plug-in is not an option ? Also, auto-type could be a solution.

**Comment by keepassium** [comment]
> And chrome plug-in is not an option ? Also, auto-type could be a solution.

I'm afraid not; these would take too much time and affect only few users. As a one-man-band, I would rather focus on improving KeePassium than making workarounds for Chromium…

**Comment by keepassium** [comment]
Fixed by [AutoType feature](https://keepassium.com/blog/2025/11/keepassium-2.4/#macos-autotype-enter-credentials-to-any-app) introduced in v2.4.
