### ISSUE TITLE
Multiple entrys with same URL

### ISSUE THREAD

**Issue by loeffelpan** [keepassium/KeePassium#212]
**Description**
I share one KeePass-db with my wife and there are several services where we both have accounts. Though two entrys have the same URL.
Usually I use „auto-fill perfect match automatically“-feature. But in that case KeePassium fills the first perfect match, even if there is another perfect match.

**How to reproduce**
1. Create two entrys with same URL
2. Navigate to the above URL
3. Try to Auto-Fill the second of above entrys
4. There will be no selection dialog

**Expected behavior**
Bring up the selection dialog for matching entrys when there is more than one perfect match - as described in the settings.

**Environment:**
 - Device: iPhone 11
 - OS: iOS 15.2
 - App Version: 1.29.100

**Comment by keepassium** [comment]
Thanks for the report! I cannot reproduce this, though… 

https://user-images.githubusercontent.com/38399598/147166302-666706db-3e48-48cb-851c-1817f45f3033.mp4

 Do you refer to Quick AutoFill, by any chance? (The one that shows credentials directly above the keyboard.)

**Comment by loeffelpan** [comment]
No I‘m using the same way like in your video. And I can reproduce this with two different entrys. Take a look at my videos.

https://user-images.githubusercontent.com/34661317/147370353-36f05b12-f590-48b3-8d18-06c8cccaeef7.MP4


https://user-images.githubusercontent.com/34661317/147370356-98578b2c-8a61-456d-96d7-95235f21aac5.MP4

**Comment by keepassium** [comment]
Found it. Thank you!
