### ISSUE TITLE
Delete additional/custon fields

### ISSUE THREAD

**Issue by loeffelpan** [keepassium/KeePassium#213]
Please add a button/control to delete custom fields when editing entrys.

For now I have to use another KeePass client to remove those fields.

**Comment by keepassium** [comment]
You can already delete custom fields by swiping them left. (Pretty much like emails in the Mail app.)

**Comment by loeffelpan** [comment]
Sorry for missing that. Never thought about swiping the whole block of two text input fields and one switch. Thank you for that info

**Comment by keepassium** [comment]
No worries. I agree this is not the most intuitive gesture in that context… There will be another way once there is manual reordering of custom fields.
