### ISSUE TITLE
Safari on Macbook crashes on Autofill

### ISSUE THREAD

**Issue by layandreas** [keepassium/KeePassium#216]
**Description**
Safari crashes on using Quick AutoFill in Safari on MacOS **only when app lock is disabled**. 

**How to reproduce**
Try logging in on any website using Safari and Quick Autofill with app lock disabled.

**Expected behavior**
Successfull login without crash.

**Environment:**
 - Device: Macbook Air M1 2020
 - OS: MacOS Monterey 12.2
 - App Version: v1.30.103
 - Safari Version: 15.3

**Additional context**
Safari crash report:
[safari_crash_log.txt](https://github.com/keepassium/KeePassium/files/8028106/safari_crash_log.txt)

Login example:
![image](https://user-images.githubusercontent.com/79149948/153088056-a0807ba3-5f04-4a6d-9f69-433fdcc65d30.png)

Keepassium settings:

App lock disabled - no crashes when enabled.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/79149948/153089670-e61dcaed-7701-42e0-a6df-2d8230391e4e.png">

![image](https://user-images.githubusercontent.com/79149948/153088150-06507d25-e128-45f0-9378-807ffcccd326.png)

2 databases are added in Keepassium, app lock disabled.

**Comment by keepassium** [comment]
Thanks, Andreas. Does this happen every time/on other websites?

I do get occasional Safari crashes with AutoFill on Big Sure, but they look like some Safari bug...

**Comment by layandreas** [comment]
> Thanks, Andreas. Does this happen every time/on other websites?
> 
> I do get occasional Safari crashes with AutoFill on Big Sure, but they look like some Safari bug...

Every website and every time. Restarting the system did not help, seems directly related to disabled app lock.

**Comment by keepassium** [comment]
> seems directly related to disabled app lock

Interesting... Thanks for emphasizing, I've overlooked this detail. 

Cannot reproduce on 11.6.2, though. Will try later with Monterey.

**Comment by layandreas** [comment]
> I have tested this on Intel macOS 12.2 + Safari 15.3, but could not reproduce. I suspect this might be something Touch ID related (which I don't have on the test machine).
> 
> Can you try [1.31.104](https://github.com/keepassium/KeePassium/releases/download/1.31.104/KeePassium-1.31.104.dmg)? There was a Touch ID fix specifically for Quick AutoFill on macOS.

1.31.104 appears to have solved the issues, no crash but Touch ID is promted and password filled in!
