### ISSUE TITLE
Yubikey not working on macOS

### ISSUE THREAD

**Issue by silas229** [keepassium/KeePassium#217]
**Description**
Please add support for hardware keys with Challenge-Response mode in macOS just like in #25 for iOS and iPadOS. I've tried both "lightning" slots and none of them worked.

**How to reproduce**
1. Open database
2. Click "Unlock"
3. Select one of the Yubikey slots under "Hardware Keys"
4. Try to unlock the database

**Expected behavior**
Use the Yubikey to decrypt the database

**Environment:**
 - Device: MacBook Pro 14" 2021
 - OS: macOS Monterey 12.2.1
 - App Version: v1.31.104

**Comment by keepassium** [comment]
Yes, this is the main reason why KeePassium for macOS is still "beta"…

KeePassium uses [YubiKit for iOS](https://github.com/Yubico/yubikit-ios/), which depends on low-level details of iOS and cannot be easily ported by Mac Catalyst. I did some research but could not find a quick replacement. It seems, macOS apps have to communicate with YubiKey at much lower level, which will be a substantial task by itself. So it still lingers in the queue…

**Comment by keepassium** [comment]
Just added in 1.36.116!
