### ISSUE TITLE
Unable to open database files in iPadOS 13 Public Beta 2

### ISSUE THREAD

**Issue by ankurkotwal** [keepassium/KeePassium#22]
I installed iPadOS 13 PB2 this morning (up from 12.3) and I can no longer open files with Keepassium - I keep getting an error saying that I don't have permission to view it. I've tried the following:

- Open the file from Google Drive (through the iOS file picker, not the Google Drive app)
- Open the file from iCloud Driver (through the iOS file picker)
- Open the file from the new iOS 13 "On My iPad" location (through the iOS file picker)

None of these work. The only solution I've found to making it work is to open the Google Drive app, select the file, tap "Open in" and select "Copy to Keepassium". This will open the file in Keepassium but I lose the ability to sync changes automatically to the Google Drive.

Unfortunately that still results in the AutoFill feature not working. With the AutoFill database selection, no matter what I do, I can't get Keepassium to open the file. When I select "Add Database" (in AutoFill Setup) and pick a file, the file picker goes away and I'm returned back to the AutoFill Setup dialog.

Happy to provide any additional diagnostic info if you need it.

**Comment by keepassium** [comment]
Thanks, Ankur. I have received two more reports about the same issue on iPadOS 13 (not iOS 13), while everything worked well on iOS 12. The other two issues both happen with OneDrive.

For now, I am inclined to blame this on iPadOS 13 beta. They seem to be strengthening permissions system, and file providers will need to catch up. 

I understand this issues is annoying for you. However, chasing this bug at the app level does not seem the best time investment until iPadOS 13 matures (and the bug likely disappears). Let's keep this open for now, and see if the issue remains in iPadOS 13 release candidate.

> When I select "Add Database" (in AutoFill Setup) and pick a file, the file picker goes away and I'm returned back to the AutoFill Setup dialog.

Hmm, yes, there is not much you can do from this state... I will add a "Diagnostics" button somewhere discreet on the AutoFill Setup dialog, so we could get more details.

**Comment by ankurkotwal** [comment]
Thanks for the quick response.

My gut feel is that if it were just a file provider issue, that the iCloud Drive and "On My iPad" providers wouldn't have the issue. Hence I expect the issue is elsewhere but I do take your point that this is what we should expect from an early beta.

Regarding the AutoFill Setup dialog, if you could let me know when you've added the additional diagnostic info, I'd be happy to grab it for you.

Thanks again for making the best keepass client on iOS!

**Comment by keepassium** [comment]
Now also reported to happen on iOS 13 / iPhone X*...

**Comment by benjibobs** [comment]
I was the one who reported it on iOS 13 / iPhone X* - I would agree with the suspicion that the fault lies in the iOS 13 beta. There’s no point trying to address it until GM is out because it might just change anyway. This beta is a little unstable (not for me, but I’ve seen reports) so it is quite possible that it’s a bug in the beta. 

The same workaround described in the issue works for me. 

Seeing as we are discussing auto fill I’m just going to mention (as I’m unsure if it’s documented) - the auto fill setup is allocated less memory, so databases can cause the “ran out of memory” error while opening perfectly fine in the app. Obviously it’s an OS limitation but I thought it was worth raising in case it isn’t a documented quirk.

**Comment by keepassium** [comment]
Thanks for understanding!

> Seeing as we are discussing auto fill I’m just going to mention (as I’m unsure if it’s documented) - the auto fill setup is allocated less memory, so databases can cause the “ran out of memory” error while opening perfectly fine in the app.

Yep, this had caused a lot of crashes and was the [first candidate for the FAQ](http://localhost:1313/articles/autofill-memory-limits/) :) Then I started monitoring the low memory warnings (not without an [issue](https://github.com/keepassium/KeePassium/issues/4)). 

Nowadays, trying to open a memory-hungry database in AutoFill shows an nice error message — a big step from the initial vanishing from the screen :) Given that there are no more emails about AutoFill crashing in Argon2, this solution seems to work.

**Comment by keepassium** [comment]
@ankurkotwal, if you long-press the Cancel button in the AutoFill Setup dialog, it should show you a menu to view the diagnostic log. (Yep, this is a very Easter-egg-like debug feature. I just did not want to distract the 99% of people who will never need it.)

I assume that AutoFill Setup also gets a "you don't have permission to access the file" from the system, but can you please double-check this, just in case? 
Thanks!

**Comment by ankurkotwal** [comment]
I've had to rollback to iOS 12  because I had other critical issues with the iOS 13 Beta. I probably will give it another shot at a later, more stable beta release and will be happy to try this then.

**Comment by keepassium** [comment]
No worries, Ankur. Apparently, quite a few of KeePassium users are also testing the beta iOS. So this week I am getting a dedicated dev phone to install iOS 13 and look into this issue. 
(Dev phone = pink-gold iPhone SE off eBay :)

**Comment by UVClay** [comment]
Can confirm that iOS 13 Beta 4 fixes this issue.  Doesn't seem to mention anything about it in the changelog, but I'm able to access my DB from OneDrive without issue now.

**Comment by keepassium** [comment]
Hooray! Thanks, @UVClay!

(I got an iOS 13 phone to debug this, but Xcode 10.2 refuses to work with the beta iOS. Switching to a beta Xcode few days before the release is a very questionable idea. So I am very relieved to see the issue resolved itself :)

**Comment by NKYAggie** [comment]
I just updated to the latest public Beta and was able to open my database file from the iCloud storage provider. I had to remove the database entry in the list first, and then go through the "add an existing database" process first. Once I did that, I was able to open my database successfully.

**Comment by ravemir** [comment]
Updated to the latest bets today (#6) and re-adding worked, with a catch: doing it on the app will not update it on the “Passwords“ field; once you open that pop-up, you’ll also need to re-add it there.

Good job with the app, though! I was going to try my hand at compiling it, but don’t have a USB-C to USB cable :/

**Comment by ankurkotwal** [comment]
Ok I've done a bunch more testing.
- iPadOS 13.1 Beta 4 - all working fine
- iOS 13.0 - all working fine.
By "all working fine", I mean that I'm able to add an existing database from Google Drive and it works regardless of whether I open the app directly or whether I use Autofill from the Keyboard. This issue can be closed now. Any objections?

**Comment by keepassium** [comment]
Thanks for the update, Ankur.

Yeah, it seems to work now and I have not received emails about this one for a while... So it's safe to consider this issue solved (or rather evolved into #63...)
