### ISSUE TITLE
Easy entry of TOTP token by using "otp" or "verification code" as the field name

### ISSUE THREAD

**Issue by plus-or-minus** [keepassium/KeePassium#220]
**Describe the feature you'd like**
Allow "otp" and "verification code" to be alternative one-time password field labels. Or make a field with one of those labels automatically create the "TOTP Seed" and "TOTP Setting" fields (that must be entered with the exact case) with defaults for "TOTP Setting".

I'm trying to migrate from 1Password KeePassium by placing the apps side-by-side and manually copying items over. It's tedious to have to type and define both TOTP Seed and TOTP Settings fields.

**Comment by plus-or-minus** [comment]
Related to #153

**Comment by plus-or-minus** [comment]
I can work on this if the feature is accepted.

**Comment by keepassium** [comment]
Not sure why you closed it... 

>I'm trying to migrate from 1Password KeePassium by placing the apps side-by-side and manually copying items over. It's tedious to have to type and define both TOTP Seed and TOTP Settings fields.

Yeah, that does sound tedious. However, bulk manual entry is not a typical use case. If it was, I would have invested more time to drag-and-drop... 

By the way, there is also an [automated migration procedure from 1Password to KeePass](https://keepassium.com/articles/migrating-from-1password-to-keepass-keepassxc-keepassium/). It handles one-time passwords correctly (I just checked).

**Comment by plus-or-minus** [comment]
Thanks for the migration tip! I wanted to clean up the couple hundred items I had and it didn't take too long to copy them over.
