### ISSUE TITLE
The TOTP text fields on the edit form should be only 1 row

### ISSUE THREAD

**Issue by plus-or-minus** [keepassium/KeePassium#221]
**What can be improved?**
When editing an item, the TOTP fields take up the entire viewport.

**The solution you'd like**
The height of the text fields should be only 1 or 2 lines to allow more item data to be viewed on the page.

**Alternatives you've considered**
No

**Additional context**
None

**Comment by keepassium** [comment]
_(Again, not sure why you closed this, but I wanted to comment anyway.)_

Indeed, ideally TOTP config fields should be less prominent in entry editor (#218 suggests the same for the view mode). 

But there is also a factor of interoperability. TOTP config fields are just custom fields, with editable name. This is the case in other apps, so an expert user can even (though unlikely to) repurpose the field to store something else. Making these field special (single-line, fixed name, but deletable) feels redundant to me. 

> When editing an item, the TOTP fields take up the entire viewport.

Its height is limited to 150 px. It does indeed take up the entire viewport on iPhone SE 2016 with keyboard visible — but this is largely the effect of the small screen. Even if this field was limited to a single line, there would be screen estate for maybe 30% of the following custom field — not too useful anyway...

**Comment by plus-or-minus** [comment]
That makes sense. I was adding new entries on macOS but after using the app for a week I realized the size of the custom fields on new/edit item form aren't a concern since I'm not in there editing details often. Once I create an item I hardly ever change or update it.
