### ISSUE TITLE
Save / Sync error using cloud provider Seafile pro

### ISSUE THREAD

**Issue by thejoker8814** [keepassium/KeePassium#222]
**Description**
I've created a new Passwords.kdbx (for testing purposes) on my PC using KeePassXC and stored it on Seafile (SeaDrive for Windows). Opening it in KeePassium via iOS Files (Seafile Pro) is no problem. The bug/ issue occurs once I made changes to the .kdbx, for example creating a new entry and submitting the change via "done". KeePassium throws an error.

The most curious part is, the changes are saved and are synchronized properly to the seafile server, once you select "Save as..." in the error dialog. You don't even need to save it, just opening the dialog is enough to get it properly saved and synchronized!

**How to reproduce**
- have Seafile Pro app installed, log into your server and add a library (root folder in seafile) where your .kdbx should be sync-ed to/ from
1. Open KeePassium
2. Use "Open Databse" or select "Add existing database" on Welcome screen
3. Open "Seafile Pro" in File Browser and navigate to .kdbx
4. Enter master key
5. Create new entry / group
6. Submit changes with "Done"
--> Error "Cannot save file (Seafile Pro)"
7. Tab "Save as..." in the error dialog
8. When the file browser opens and expands to the current .kdbx path, select "cancel"
Result: .kdbx is stored properly, changes are reflected on the server and can be viewed in KeePassXC almost immediately.

**Expected behavior**
Save and Sync utilizing Seafile pro without error, because it seems to be possible without issues on the file provider side.

**Environment:**
 - Device: iPhone Xs 
 - OS: iOS 15.3.1
 - App Version: 1.30.103
 - Seafile Pro version: 2.9.17 (Seafile server 8.0.8 CE)

**Additional context**
Found issue #144 which seems similar, but was never really resolved. All the linked issues do not apply, Seafile is properly configured and works without any issues.

All entries in the test Passwords.kdbx (see screenshot "KeepassXC_results") have been created within KeePassium using the same steps/ procedure.

**Attachments**
Step 6. result/ error dialog
[KeePassium_Error_Dialog.img](https://user-images.githubusercontent.com/16109493/160228225-4e82c05d-e560-405b-ae48-aaeb8d13d618.JPG)

Step 8. [Save_as_dialog](https://user-images.githubusercontent.com/16109493/160229119-2dbcecc0-2416-440e-928a-04a3a3b0537b.png)

Result in KeePassXC on PC
[KeepassXC_results](https://user-images.githubusercontent.com/16109493/160229190-8b7078f4-1a73-45fb-a8ea-d11b15fbfacb.png)

[KeePassium_log.txt](https://github.com/keepassium/KeePassium/files/8354834/KeePassium_log.txt)

**Comment by keepassium** [comment]
Thank you for the detailed report! 

> systemError: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “Passwords.kdbx” in the folder “https%3A%2F%2Fmy.domain.com_tim.tester@my.domain.com_e7fff4b1-ba50-4006-b438-9b933c22f811_%2F”.

The error returned by the system is the same in your case and in #144, this is the same issue. As mentioned in #144, the problem is reproducible with other iOS apps working with Seafile iOS file provider. So it looks like this belongs to https://github.com/haiwen/seafile-iOS/issues/314 — there is not much I can do to resolve it on KeePassium's side…

**Comment by thejoker8814** [comment]
@keepassium -
Just a feedback for you, and anyone interested in a similar setup - Keepassium now works with Seafile(Pro) App on iOS!

I’m not sure which change of the App, either Keepassium or Seafile introduced the change. Since I opened the issue, the only changes have been the iOS and App versions, everything else in the infrastructure, i.e. server hasn’t changed.

I have been using it to sync my Keepass .kdbx between IPhone, IPad, Ubuntu & Windows (both SeaDrive and KeePassXC). Even over WAN using Wireguard. 
And it’s stable and reliable (read, write & snyc)!

Only had an issue once, the current status (re-read before write/update) from file API could not be determined by Keepassium (just happened once in 2 months). .kdbx file integrity was never at risk.

**Comment by keepassium** [comment]
@thejoker8814 , thank you for the update!

> What are the criteria to add it to your “supported/ tested” list?

It's rather vaguely defined as someone confirming it works, and nobody stating otherwise :) I have added Seafile Pro to the list now.

Thanks again!

**Comment by thejoker8814** [comment]
@keepassium - been my pleasure (keepassium is the best iOS App for using Keepass! The least I can do is giving you a quick feedback.

To be thorough, the working environment ( and as I said been using it for months with auto-app updates):

Device: iPhone Xs
OS: iOS 16.5.1 (20F75)
App Version: 1.44.143
Seafile Pro version: 2.9.23 (Seafile server 8.0.8 CE)
