### ISSUE TITLE
Disable Text Replacement (spelling correction) on macOS

### ISSUE THREAD

**Issue by plus-or-minus** [keepassium/KeePassium#223]
**Description**
When trying to enter text in login items on MacOS words get replaced by the Text Replacement feature of macOS.

**How to reproduce**
1. Create a new entry
2. Enter "keepass" as the title or as a custom field label or in a note
3. "keepass" gets replaced with another word

**Expected behavior**
What you type doesn't get altered
Text Replacement is disabled

**Environment:**
 - Device: MacBook Pro
 - OS: macOS Monterey
 - App Version: 1.30.103

**Comment by plus-or-minus** [comment]
Edit > Substitutions > Text Replacement is checked but grayed out. The setting cannot be disabled.

**Comment by plus-or-minus** [comment]
This also affects notes. If you try to type "The password for this app is keepass" you will lose your data.

**Comment by plus-or-minus** [comment]
Other than this Text Replacement issue the app is working wonderfully well on macOS. I purchased a subscription and I'm using the app on my iPhone, iPad, and macOS.

**Comment by keepassium** [comment]
I would argue this is the expected behavior. 

System-wide spelling correction is intended to fix typos in manual input. If the user has it enabled, they expect it to work in text fields. Of course, password fields are an exception, but everything else is fair game: manually typed title, notes, field names. If the user wants typing assistance, who am I to force-block it?

(Fun fact: my system-wide "Correct spelling automatically" was disabled a long time ago, so I could not reproduce the  issue first :)

> Edit > Substitutions > Text Replacement is checked but grayed out. The setting cannot be disabled.

Cannot reproduce on macOS 12.3, maybe it depends on some other setting?
![Screen Shot 2022-03-29 at 12 36 26](https://user-images.githubusercontent.com/38399598/160593339-2e0eb021-9774-486d-8ba1-b69bcd96293c.png)

**Comment by cappert** [comment]
> I would argue this is the expected behavior.
> 
> System-wide spelling correction is intended to fix typos in manual input

Does it trigger in e.g name fields in Contacts.app? or Keychain.app ?

**Comment by piercefaulkner** [comment]
The Contacts app on macOS didn't replace text for first name, last name, address, note, or any other fields I tried.

KeeWeb desktop (which is electron) also didn't replace text. The "Spelling and Grammar" menu isn't available under Edit.

**Comment by piercefaulkner** [comment]
I may have had a different application focused because the "Spelling and Grammer" and "Substitutions" options are changeable from the Edit menu.

**Comment by piercefaulkner** [comment]
The "Spelling and Grammar" and "Substitution" menus only seem to be available when you're in a text field.

When you open the app and no item is selected the settings can't be changed until you click on the search field or edit an item and click on a text field.

**Comment by piercefaulkner** [comment]
Keepass respects (or inherits) the system-wide "Correct Spelling Automatically" setting ("Correct spelling automatically" in System Preferences).

**Comment by keepassium** [comment]
Thanks, everyone! After spending a few days trying to find a refined solution (saving and respecting the app-level editing settings), I decided it was probably overthinking. So I went ahead and:

1) Removed the Spelling/Substitutions/Tranformations from the main menu (leaving them in context menus, though)
2) Disabled autocorrection in the entry editor altogether (leaving the spellchecking, though)

Just published the [1.31.107 release](https://github.com/keepassium/KeePassium/releases/tag/1.31.107), please let me know how it works for you. Thanks!
