### ISSUE TITLE
Typing app passcode automatically when app is opened

### ISSUE THREAD

**Issue by aarontorres0** [keepassium/KeePassium#227]
**What can be improved?**
 I'm always frustrated when I open the app and start typing my app passcode and see that it wasn’t typed in the Passcode input box. I press on the box and type in my passcode. It will unlock the app and I am prompted to input my password for the database and I see that my passcode is typed in the database password box.

**The solution you'd like**
When the user opens the app, the cursor is set on the Passcode input box, and not on the database password input box

**Alternatives you've considered**
Enabling Face ID for app protection, but I don’t like using Face ID.

**Additional context**
None

**Comment by keepassium** [comment]
Yep, this has already been fixed in the [latest beta](https://keepassium.com/beta). Give it a try and let me know should the issue remain. Thanks!

**Comment by aarontorres0** [comment]
I can confirm that it is fixed, thank you
