### ISSUE TITLE
App settings should be properly formatted as title case to be consistent 

### ISSUE THREAD

**Issue by Taxyovio** [keepassium/KeePassium#228]
**What can be improved?**
App settings, “Auto-open the Previous Database”, “Fill-in the perfect result automatically”, and “Copy OTP to clipboard” should be formatted properly to title case, to be consistent with iOS system settings. For example, look at the system keyboard settings. Besides capitalisation, articles should be omitted.

**The solution you'd like**
- “Auto-open the Previous Database” -> “Auto-Open Previous Database”,
- “Fill-in the perfect result automatically” -> “Fill-In Perfect Result Automatically”, 
- “Copy OTP to clipboard” -> “Copy OTP to Clipboard”, (Not “Copy One-time password (TOTP) to clipboard” please. 😂 )

**Alternatives you've considered**
Do nothing as nobody else would care.

**Additional context**
Some recent changes in TF induced intense OCD from me. I have tried to ignore these for a long time. But it’s time to write them out.

![7FF98717-3E77-4BC5-97B6-56D437310AF8](https://user-images.githubusercontent.com/38234151/164895718-38c72e34-3e99-499d-b0e7-cef6f3665252.jpeg)
![702B58EE-47C6-487B-9705-084CBDF75417](https://user-images.githubusercontent.com/38234151/164895719-235bb2ac-435c-423d-a6c2-abadc551ce98.jpeg)
![B3C7C62F-EF01-41E3-921E-8C4B07955185](https://user-images.githubusercontent.com/38234151/164895721-1f412aa1-09f2-41ec-8c56-a6cd22fcf652.jpeg)

**Comment by keepassium** [comment]
Thank you! 

I agree that capitalization needs fixing.

> Besides capitalisation, articles should be omitted.

In my defense, dropping the articles is not mentioned in the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/terminology/). Moreover, the [guidelines about menus](https://developer.apple.com/design/human-interface-guidelines/ios/controls/edit-menus/) imply that articles can be present:

> Use title-style capitalization—capitalize every word except articles, coordinating conjunctions, and prepositions of four or fewer letters.

That said, I agree that your suggestions look cleaner and more Apple-like.

> Some recent changes in TF induced intense OCD from me. 

Hello from my non-native-speaker impostor syndrome :)

Fixing the texts in the code would break the existing translations, so I have added an [English-to-English translation pair](https://crowdin.com/project/keepassium/en) to refine the wording more easily.

**Comment by Taxyovio** [comment]
Articles are often omitted in titles as long as the meaning remains clear [^https://english.stackexchange.com/questions/38759/whats-the-general-rule-for-dropping-articles-in-article-section-titles-or-in]. At least there’re all omitted in iOS settings. For example, it could have been “Slide on *the* Floating Keyboard to Type” if articles are not intentionally omitted.

As for translation, I don’t think these changes would have any impacts on them. I’m not familiar with crowdin. Is it supposed to be crowd sourced translation? I might be able to contribute some jp and cn translations.

**Comment by keepassium** [comment]
Thank you for the link.

> As for translation, I don’t think these changes would have any impacts on them. 

Roughly speaking, translation files consist of pairs "English_phrase = Translated_phrase". Changing the translation is easy. Changing the English phrase implies updating all 20 or so translations (plus the standard overhead of cleaning/exporting/importing/verifying the strings).

> I’m not familiar with crowdin. Is it supposed to be crowd sourced translation? I might be able to contribute some jp and cn translations.

Yes, it is a crowd-sourced translation service. Contributions are welcome!

**Comment by keepassium** [comment]
At the end I decided to go without the English-to-English pair and update the original strings directly. Adding 300k worth of resource files seemed an overkill for fixing 4 strings :)
