### ISSUE TITLE
Tab key does not switch input fields

### ISSUE THREAD

**Issue by x-Felix** [keepassium/KeePassium#233]
**Description**
Keepassium macOS v1.32.100
When editing or add a new entry, press keyboard 'Tab' cannot switch between fields. Instead, it just leaves couple spaces in the same field. Not sure if it is designed on purpose or a bug. 

**How to reproduce**
Open Keepassium macOS version, choose a database, add a new entry. 
type the new entry name. Press 'Tab' try to navigate to username field. But it just add a few spaces in the same entry name field, not toggle to username field or password field. 

**Expected behavior**
Expected behavior is like a table entry. When press tab key, it should toggle between different entry fields. 

**Screenshots**
N/A

**Environment:**
 - Device: macbookpro
 - OS: macOS 12.4
 - App Version: v1.32.100

**Comment by keepassium** [comment]
> So this seems to be a Mac Catalyst bug that will magically disappear in a future macOS version.

And so it did. Just checked with macOS 12.5.1 (KeePassium 1.36.116): Tab navigation works correctly, at least in the entry editor.
