### ISSUE TITLE
Keepasium and failed authentications over Nextcloud storage

### ISSUE THREAD

**Issue by fuzunspm** [keepassium/KeePassium#234]
**Description**
I have fail2ban configured for Nextcloud authentication and Keepassium keeps making failed authentication attempts and gets IP blocked 

**Environment:**
 - Device: iPhone 13 Pro Max/iPad Pro (they both have the same issue)
 - OS: iOS 15.5/iPadOS 15.5
 - App Version: 1.32

Here is the Nextcloud logs triggered by Keepassium. I have 3 others apps that use Nextcloud storage and they don't have this problem. I tried to re-login/re-install both apps but it didn't fix the problem

```
{"reqId":"someID","level":2,"time":"2022-05-15T13:22:50+03:00",
"remoteAddr":"MY_IP_ADDRESS","user":"--","app":"core","method":"PUT",
"url":"/nextcloud/remote.php/dav/files/username/Pass/Passwords.kdbx",
"message":"Login failed: '' (Remote IP: MY_IP_ADDRESS')","userAgent":"File%20Provider%20Extension/0 CFNetwork/1331.0.7 Darwin/21.4.0","version":"24.0.0.12"}
```

**Comment by keepassium** [comment]
KeePassium does not store your Nextcloud credentials and does not send network requests to your server. The app [delegates synchronization](https://keepassium.com/articles/cloud-sync-sandboxing/) to the original cloud provider's app. (Or, more precisely, its File Provider module which handles Nextcloud integration with the standard iOS Files app.) 

So this is purely a Nextcloud issue that has nothing to do with KeePassium. You can try to replicate the issue by opening Nextcloud-stored PDF files in the standard Files app, and editing them using Markup feature (still in the Files PDF preview). Requests received by your server in this scenario should be very similar to KeePassium's workflow.

> I have 3 others apps that use Nextcloud storage and they don't have this problem.

I assume these apps communicate with your server directly, not via the Files/Nextcloud integration.

**Comment by ann0see** [comment]
Is there any follow up issue in the Nextcloud app? I'm facing the same issue

**Comment by ann0see** [comment]
Thank you for your answer. I've updated the regular expression for the Nextcloud fail2ban jail. Let's wait and see.
