### ISSUE TITLE
Add option to hide "Notes" field

### ISSUE THREAD

**Issue by cdrehner** [keepassium/KeePassium#236]
I'd love to have the option to also hide the "Notes" field by default. I know I could use a protected custom field, but since KeePassXC can hide the notes, I've already stored several sensitive information in this field.
Thank you very much!

**Comment by keepassium** [comment]
Thank you for the suggestion! To be honest, I am rather divided about this…

On the one hand, "Notes" is just a field. So it would make sense to be uniform and make it possible to hide the notes, like any other custom field.

On the other hand, "Notes" is a bit special: it is one of the few predefined fields, its "protected/unprotected" state is defined at the database level (not per entry, like custom fields). Plus, I've heard from people who use it for long-form texts (personal journal) and adding as little as an "eye" button would interfere with their experience.

After some more thinking, I believe sensitive pieces of data do belong in custom fields, they are both safer **and** easier to use. Imagine copying a credit card number:
- From the Notes field: reveal Notes → find the CC number among other info → select its text → tap Copy → hide the Notes again.
- From a custom field: tap the custom field, done. Without even revealing it.

Making it possible to hide Notes would encourage the first approach, which is ultimately not in users' interest…

**Comment by cdrehner** [comment]
Thank you very much for your detailed consideration on this! I totally agree with you that storing sensitive data such as CC number in a custom field makes much more sense.
However, on my desktop I use the Notes field to quickly write down stuff from registration processes like security Q&As:

"First pet's name? -> Snoopy"
"Mum's place of birth? -> Paris"
"Backup Mail address -> ..."   and so on.

Pasting this into customs field(s) means a lot more clicks here. Can you see this use case and why not being able to hide this field in keepassium when using an existing database feels like a little downside? 

If users do not wish to hide the Notes field by default and thus don't enable this in the settings, I hope the feature wouldn't annoy them?

Appreciate your great work, no matter the outcome on this! ;-)

**Comment by keepassium** [comment]
> Can you see this use case and why not being able to hide this field in keepassium when using an existing database feels like a little downside?

I do understand the use case; my older entries are exactly like this :)

> "First pet's name? -> Snoopy"
> "Mum's place of birth? -> Paris"
> "Backup Mail address -> ..." and so on.
> 
> Pasting this into customs field(s) means a lot more clicks here.

Ok, this will sound like "[Just avoid holding it in this way](https://www.theguardian.com/technology/blog/2010/jun/25/iphone-reception-problems-solved)"… 

Yes, it takes more clicks to enter that info in custom fields. It is much quicker to dump everything into Notes. But quicker is not always better. 

- How many times you will enter that info? Once.
- How many times you will copy-paste that info? Multiple.

So any clicks saved at the first stage will cost you more clicks wasted in the future. 

An analogy, if I may. Storing new accounts in a text file (even an encrypted one) would be quick and easy. But searching that file without any structure would be difficult. Adding an account to a password manager takes some discipline and a lot of clicks. Yet here we are :)

**Comment by keepassium** [comment]
Ok, I guess this can be closed now.
