### ISSUE TITLE
Prevent AppUnlock fingerprint prompt

### ISSUE THREAD

**Issue by xrisk** [keepassium/KeePassium#237]
Often when switching spaces, I am presented with this prompt.

<img width="370" alt="Screen Shot 2022-05-28 at 7 07 51 AM" src="https://user-images.githubusercontent.com/10669859/170804864-4d9f11a0-b182-4551-a8d8-268492361dd4.png">

This happens even though I haven’t clicked on the app in the dock. These are my AppLock settings.

<img width="643" alt="Screen Shot 2022-05-28 at 7 12 26 AM" src="https://user-images.githubusercontent.com/10669859/170804887-47f3d4bd-c25a-4d82-9f28-023962692cee.png">

Keepasium version 1.32.110
macOS 12.4

**Comment by keepassium** [comment]
Thanks! 

Yes, this is one of the side effects of mobile assumptions misfiring on a desktop system. The Touch ID prompt is shown whenever the system tells KeePassium the app became active. On iOS, this means KeePassium became **the** current app. On macOS, this means KeePassium became **one of** the apps visible on the screen.

Handling the state transitions across the platforms is non-trivial (not a five-minute fix), but I will get this fixed eventually.

**Comment by keepassium** [comment]
Sorry, I forgot to mention this issue in the commit. Should be fixed in 1.36.116.

**Comment by xrisk** [comment]
thanks for your work!
