### ISSUE TITLE
macOS: Any way to mute Safari's "Would you like to save this password?" prompt when using KeePassium?

### ISSUE THREAD

**Issue by martinsstuff** [keepassium/KeePassium#239]
**Describe the feature you'd like**
I am using KeePassium exclusively so this prompt is a bit annoying, unfortunately turning off password autofill also turns off KeePassium integration. I can totally imagine this being an Apple thing that can't be disabled but maybe there is something that can be done?
<img width="960" alt="Screen Shot 2022-06-01 at 05 57 41" src="https://user-images.githubusercontent.com/29005772/171326750-cafdeb4f-574e-43c5-a19c-7f50c7857719.png">

**Edit:** I just noticed... The Mozilla website is just coincidence from when I took the screenshot. To clarify: it's actually in Safari.

**Comment by keepassium** [comment]
None that I know of, unfortunately. Apple's Keychain is really intrusive on macOS :(

**Comment by keepassium** [comment]
Closing since this cannot be fixed on KeePassium's side.
