### ISSUE TITLE
AutoFill and OTP

### ISSUE THREAD

**Issue by ixs** [keepassium/KeePassium#242]
**Description**
I seem to remember that there was a feature that would load a TOTP token into the clipboard to be pasted after a the autofill extension filled in username and password.

This seems not to work anymore?

**How to reproduce**
1. Go to any website that is autofillable and uses MFA.
2. Complete autofill, try to paste the TOTP token into the MFA field.
3. ???
4. Disappointment

**Expected behavior**
1. Go to any website that is autofillable and uses MFA.
2. Complete autofill, try to paste the TOTP token into the MFA field.
3. ???
4. Profit

**Environment:**
 - Device: iPhone 13
 - OS: iOS 15.5
 - App Version: v1.35.114 Pro

**Comment by keepassium** [comment]
Yep, it seems AutoFill can modify the clipboard only when AutoFill is in non-quick mode (with some UI visible). I will try to work around it using a notification — as much as I hate to add the notification permission to KeePassium...

**Comment by keepassium** [comment]
@hkaancaliskan , the original issue remains but the workaround is implemented. You might need to activate the permissions, though: open KeePassium settings → AutoFill Passwords → Copy OTP to Clipboard → turn it off → turn it back on. The app will ask permission to show notifications. 

After this, if AutoFill cannot copy the OTP to clipboard (in quick mode), it will at least show a notification with the code to simplify manual input.
