### ISSUE TITLE
Password Generator App

### ISSUE THREAD

**Issue by yacob841** [keepassium/KeePassium#243]
I love your work, been with you since the beginning, but sadly I'm starting to get pulled more towards Apples Password Management. It's definitely not your fault, Apple just makes there stuff have more compatibility with their stuff than 3rd party but as time passes they seem to be opening up more and your project keeps getting better so I hope to return eventually.

In the mean time, something Apple is failing at IMO and you are excelling at, is the password generation. Apples auto-generated password follows a pattern and that is obviously not ideal as well as limits characters. I planned on solving this by making a Password Generator Siri Shortcut, which works but I have to choose between a ton of menus and clicking or not having many features, while your password generator looks so nice with so many options in a single screen.

So my thought is, you should make an additional separate app that is just the password generator. Just shows the same screen as the current one, you generate password, it auto copies to clipboard, and done. Real simple, but really convenient for those not using KeePassium.

**Comment by keepassium** [comment]
Thank you, @yacob841 . I remember and appreciate your feedback in the early days! (Actually, one of your feature requests is in the queue…)

> In the mean time, something Apple is failing at IMO and you are excelling at, is the password generation.

Yeah, only a month ago KeePassium's password generator was so primitive and now it's a whole different level. I am glad you like it too!

That said, I don't think a specialized "spin-off" app is worth it. 
1) There are already [quite a few](https://fnd.io/#/us/search?mediaType=ios&term=password%20generator) password generator apps.
2) Chances are, Apple would reject it as not unique enough. 
3) Even if approved, it will need additional marketing to make it visible. (I don't imagine KeePassium showing "Hey, there is a new pass gen app, you already have it in KeePassium but still check it out!")
4) Even if it becomes any popular (which is a big "if") — what's next? Users will start requesting features: templates, list of recently generated passwords, batch generation, customizable font, large-text mode, printable results, different color themes... (This is a brief description of [Cryptical](https://apps.apple.com/us/app/cryptical/id385464875)'s screenshots) 

So I would rather focus on the main app…
