### ISSUE TITLE
Automatically generate password when creating an entry

### ISSUE THREAD

**Issue by kstlv** [keepassium/KeePassium#245]
When creating an entry, automatically generate a password.

In this case of use, the process of creating an account is simplified.

**Comment by keepassium** [comment]
Thank you for the suggestion! (and sorry for the slow response)

I'm not sure this would be universally useful, though:

- Some entries don't need a password (e.g. a license key, a note)
- Some entries need a predefined password (e.g. credit card PIN)
- Finally, entries that do need a new password often have specific password rules. Chances are, any pre-generated password will be rejected by the target service.

So in the end, the user would likely spend their time erasing the pre-generated password and getting annoyed…

**Comment by kstlv** [comment]
@keepassium Thanks for the detailed answer. I understand that you gave an example of different use cases. You're right. But I think that it would be possible to give the user a choice (for example, a switch in the settings — turn on/off auto passgen for new entry). This functionality is already implemented in the original KeePass for Windows. This is just my suggestion and the choice is yours.

I also want to say that I really like this app and am glad that it is open source. Thanks! ❤️

**Comment by keepassium** [comment]
@kstlv , thank you for the follow-up! 

> But I think that it would be possible to give the user a choice (for example, a switch in the settings — turn on/off auto passgen for new entry).

Yeah, I don't mind to add this as an option deep in the settings, in a second- or third-level section. But, oddly enough, currently there is no suitable section… The most suitable one is "Appearance" — and it's not that relevant, to be honest. Adding a new top-level section only for "Generate password for new entries" seems… excessive.

That said, auto-generating the passwords for new entries would be a logical part of AutoFill (#87). Would this work for you, or you need this behavior in the main app itself?

**Comment by kstlv** [comment]
@keepassium I want it to work like the original KeePass in the app itself, not on AutoFill (although that might be something to think about). In the original program, the checkbox (switch) is located in the parameters of the password generator (for more details, see the [last paragraph on the official website](https://keepass.info/help/base/pwgenerator.html)). In KeePassium switch may be located in approximately the same place (in Password Generator screen).

**Comment by kstlv** [comment]
@keepassium I'm sorry, the original KeePass has a special template for passgen when creating an entry, and not just a checkbox.

**Comment by keepassium** [comment]
Wow, time flies by… Sorry I got carried away and did not follow up on this one.

Pre-generated passwords will likely show up in AutoFill one day as part of #87. In the main app, a new entry can be created for a variety of reasons and prefilled passwords can create more trouble than they solve. In the AutoFill, however, we can be fairly certain the user wants to create a username/password pair (plus there is some info about website's password rules, if we are lucky). 

Eventually this AutoFill functionality might spill out to the main app as well, but for now it is indeed safer to close as not planned.

**Comment by kstlv** [comment]
@keepassium I agree, this functionality should be added to the most logical part of the app — AutoFill. I respect your opinion.
