### ISSUE TITLE
Feature: implement Tags, adding, editing, searching

### ISSUE THREAD

**Issue by chriswayg** [keepassium/KeePassium#249]
Implement Tags like in KeePassXC or other mobile KeePass clients like Keepass2Android. Ability to display existing tags, add and edit tags and search for tags.

**From the KeePassXC documentation:**
> Tags - Dynamic groups of entries that can be quickly displayed with one click. Any number of custom tags can be added when editing an entry. Add tags to the entry to quickly search for it using the tags panel on the main database view. You can easily add new tags or select existing ones from the drop-down list.

And *why* you need it — that is, how it would make your life better.

Tags are vastly superior to folders (groups). I think in 2022 I don't need to explain the advantage of tags when organizing a large set of data, as this has been covered by many developers over the years. Below are some quotes relating to other password managers:

> As someone who manages passwords for a large family household, I want the ability to add a custom tag to each entry so that I can apply multiple identifiers to each entry and better organize my vault. For example, I want the the ability to add a custom “address” tag to entries that require an address update. This way I know which entries to change when I move to a new location.

> **Learn how to use tags to organize your items and find them easily.**
> You can ... use tags to keep everything organized. There’s no limit the number of tags you can create:
 >   - a finance tag for your bank accounts and credit cards
 >   - a health tag for your health insurance, gym memberships, and fitness apps
 >   - an insurance tag for all your insurance policies
 >   - anything that will help find related items when you need them
>
> You can use multiple tags on a single item, like health and insurance, to help narrow down your search later.

**Comment by keepassium** [comment]
Thanks! This is on my list, but with a rather low priority at the moment.
