### ISSUE TITLE
Feature request: YubiKey support

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#25]
YubiKey support is a frequently requested feature, especially since both desktop and Android apps have it. I am opening this feature request to collect relevant info on the topic and to keep track of updates.

YubiKey support in KeePass ecosystem is a wild zoo of formats and methods. 

KeePass itself [supports YubiKey](https://keepass.info/help/kb/yubikey.html) in static mode (YK simulates a keyboard and types your master password), as well as HOTP and challenge-response modes (with the [OtpKeyProv](https://keepass.info/plugins.html#otpkeyprov) and [KeeChallenge](https://keepass.info/plugins.html#keechl) plugin, respectively).

KeePassXC, in turn, also [supports YubiKey](https://keepassxc.org/docs/#faq-yubikey-2fa) in challenge-response mode. In contrast to KeePass plugins, KeePassXC's implementation does not need any additional files (that would need to be synced), keeping the database self-sufficient. Well, with a YubiKey :)

Since KeePassXC is available on more platforms and needs only the database itself, their approach seems the best candidate for implementation.

**Comment by keepassium** [comment]
Now the feasibility part.

[Yubico Mobile iOS SDK](https://github.com/YubicoLabs/yubikit-ios) does not seem to support the challenge-response mode. Yubico support confirmed this:

> Definitely not on NFC, since IOS does not permit us to "write" over NFC, so cannot send the challenge to the YubiKey over NFC.
> As for the lightning port, the firmware supports it, but it has not yet been exposed in the SDK, but this should be coming in upcoming releases of the SDK (probably after the summer though)

**The bad news**: unfortunately, Yubikey challenge-response is impossible in iOS at the moment, due to the system-imposed NFC limitations. 

**The good news**: Yubico are planning to provide this mode with the upcoming Lightning-enabled keys.

**Comment by dotWee** [comment]
Any updates about this feature? Yubico recently released their first key using a lightning connector and the corresponding iOS SDK received a major update to [v2.0.0](https://github.com/Yubico/yubikit-ios/releases/tag/2.0.0).

**Comment by keepassium** [comment]
Yeah, I saw the announcement and have ordered the 5Ci key yesterday. Unfortunately, the challenge-response mode is still not supported by the SDK 2.0. 

The good news is that there is a [raw mode](https://github.com/Yubico/yubikit-ios#integration_steps_3_5) that might be used as a workaround (basically, implementing the challenge-response exchange at the app side). I plan to explore this once I receive the hardware.

**Comment by Janhouse** [comment]
You should look at the NFC capabilities in the new iOS version as well. Apple will enable sending and receving of NDEF messages which should allow using NFC enabled Yubikey in any mode.

**Comment by keepassium** [comment]
Good point, @Janhouse. I have [opened an issue](https://github.com/Yubico/yubikit-ios/issues/3) in Yubico's repository, let's see what they say.

**Comment by imakhalova** [comment]
Does KeyPass Android supports YubiKey challenge-response mode ?

**Comment by keepassium** [comment]
@imakhalova, keepass2android [does](https://github.com/pp3345/ykDroid), KeePassDX is [ planning to](https://github.com/Kunzisoft/KeePassDX/issues/8). I could not find anything specific about KeePassDroid, though.

**Comment by keepassium** [comment]
I've received the new YubiKey 5Ci (with Lightning connector) today and got some proof-of-the-concept code working. There are no news about the NFC keys, though... 

Stay tuned and upgrade to 5Ci :)

**Comment by keepassium** [comment]
YubiKey integration is now [ready](https://keepassium.com/blog/keepassium-1.10-yubikey-beta/) for your beta feedback! 

I'm sorry it took way longer than expected (mainly thanks to the minefield they call "iOS 13"). Nevertheless, KeePassium seems to be the first KeePass iOS app with YubiKey support, yay!

**Comment by keepassium** [comment]
Already in the App Store :)

**Comment by samsam-rolon** [comment]
Hello,

Auto-fill feature isn't working with DB protected by Yubikey.

Any idea why ?

**Comment by keepassium** [comment]
@samsam-rolon , it's the other way round: YubiKey does not work in AutoFill feature. This is because Apple wants AutoFill modules to be lightweight, so AutoFill is not allowed to access NFC or Lightning port. So there is no way to communicate with YubiKey from AutoFill...

**Comment by keepassium** [comment]
Well, it took four years to get YubiKey working in AutoFill… It is still limited to Lightning only (YubiKey 5Ci), but as of v1.51 it does work in YubiKey.
