### ISSUE TITLE
"Add the file again" unclickable

### ISSUE THREAD

**Issue by psifertex** [keepassium/KeePassium#250]
**Description**
I'm using the latest KeePassium XC on ios and it's somehow losing track of a database stored in iCloud. When the popup to "add this file again" comes up, it disappears almost immediately and is unclickable. Does that mean the database was found? I still am told that I'm on an uncached copy. 

How do I recover this? Last time I just had to totally remove and re-add which is a pain especially if I have made recent changes.

**Comment by psifertex** [comment]
Trying to paste correct images again, preview selected the wrong one apparently. 
![0B01240A-1F65-476B-ACDC-A1F071F67EFD](https://user-images.githubusercontent.com/140215/187448896-c26698a0-b9b2-4da8-850d-7095dd626e81.jpeg)

**Comment by psifertex** [comment]
I think I resolved it by opening the files app and re-opening the database but it would be great if this button either worked or was removed to not confuse people!

**Comment by keepassium** [comment]
Thanks! Yeah, this is certainly unpleasant… 

Historically, this popup was added when KeePassium simply stopped loading databases after encountering any error. So you would end up back in the unlock screen, with the popup and no progress bar.

But later on, KeePassium learned to fall back to opening a backup file in case of trouble, and this message becomes a distraction now (and disappears too quickly anyway). Perhaps it will make more sense to show it after loading the fallback file. I will look into this.

> I'm using the latest KeePassium XC on ios and it's somehow losing track of a database stored in iCloud. 

Yeah, this is a common issue with iCloud Drive, pCloud and some others. [The solution](https://keepassium.com/articles/sync-troubleshooting/#does-not-exist) is to disable multi-step saving in the desktop app's settings (through a temporary file).

**Comment by psifertex** [comment]
Thanks for the tip about the XC setting. Updated.
