### ISSUE TITLE
Keepassium returns expired password

### ISSUE THREAD

**Issue by cryptosteve2** [keepassium/KeePassium#252]
**Description**
I have two different credentials for a website. One is expired and keepassium always returns the expired one first.

**How to reproduce**
Open Safari on MacOS, open website and activate username/password fields ... 

**Expected behavior**
Only return the actual password and not the expired one

**Environment:**
 - Device: MacBook Pro M1 2020
 - OS: MacOS Monterey (v 12.5.1)
 - App Version: v1.35.114

**Comment by anmipo** [comment]
Good point, thank you!

**Comment by keepassium** [comment]
Good point, thank you!
