### ISSUE TITLE
Pressing enter with an empty password should open the Touch ID dialog

### ISSUE THREAD

**Issue by moenodedev** [keepassium/KeePassium#253]
When the MacOS app opens, pressing enter with an empty password should open the Touch ID dialog so that you don't have to use the mouse (to click the Touch ID button). The tab key doesn't switch inputs therefore you're forced to use the mouse to use the app.

<img width="910" alt="Screenshot 2022-09-17 at 9 42 47 PM" src="https://user-images.githubusercontent.com/113457600/190866223-9d26ac0b-872b-46a0-8d54-fe223eeb34b8.png">

**Comment by keepassium** [comment]
Good point, thanks!

**Comment by moenodedev** [comment]
Why escape instead of enter like KeeWeb or 1Password?

**Comment by keepassium** [comment]
> Why escape instead of enter like KeeWeb or 1Password?

Enter did not feel right in terms of UX. Basically, Enter in that context means "here's my passcode" — and it felt like sending an empty passcode using the disabled Unlock button. This would give the user a confusing impression that disabled buttons are not always really disabled, but sometimes do something useful.

In the meanwhile, Escape generally means "I don't like this dialog, get me out". This seems more intuitive than Enter, although not perfect still. Perhaps I should add a "Press Esc for Touch ID" underneath the buttons…
