### ISSUE TITLE
Autofill credit cards in Safari

### ISSUE THREAD

**Issue by moenodedev** [keepassium/KeePassium#254]
Support credit card autofill in Safari.

Safari needs description, full name, card number, expiration, and security code. Entries would also need a designated field or flag to signify the entry type is a credit card.

https://support.apple.com/en-in/guide/safari/ibrw1103/mac

Autofill can be tested at https://mozilla.github.io/form-fill-examples/basic_cc.html

<img width="1044" alt="Screenshot 2022-09-17 at 10 29 02 PM" src="https://user-images.githubusercontent.com/113457600/190868216-564fa9fd-2371-49da-ba66-f7e398986b0b.png">
<img width="1044" alt="Screenshot 2022-09-17 at 10 28 55 PM" src="https://user-images.githubusercontent.com/113457600/190868221-c14a462f-117a-4e99-83ff-4669abfd9fc1.png">

**Comment by keepassium** [comment]
Unfortunately, Apple does not expose the required API, so this is impossible to implement for the moment.

**Comment by moenodedev** [comment]
I added the credit card directly to Safari.
