### ISSUE TITLE
Export to CSV format

### ISSUE THREAD

**Issue by moenodedev** [keepassium/KeePassium#262]
Support export to CSV since it's unlikely Firefox will support MacOS AutoFill soon and it doesn't like a KeePassium addon for Firefox is on the roadmap. Also, Safari Auto Fill is broken when Touch ID is enabled (#259). Adding CSV export would make it easier for desktop users to use autofill functionality built into browsers.

#### Fields
* Title
* URL
* Username
* Password
* Notes
* OTPAuth

#### Example CSV

```csv
Title,URL,Username,Password,Notes,OTPAuth
"Apple","https://apple.com","user@example.com","password","","0000000000"
```

Safari also supports the Firefox CSV format.

### Limitations of `about:logins`
* Does not have a Notes field
* Does not allow extra fields
* Does not support TOTP or two factor tokens
 
#### Fields

* url
* username
* password
* httpRealm
* formActionOrigin
* guid
* timeCreated
* timeLastUsed
* timePasswordChanged

`url`, `username`, and `password` values must be present (not blank "" or null) otherwise the row will not be imported.

#### Example CSV

```csv
"url","username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"
"https://apple.com/","user@example.com","password","Apple","","00000000-0000-0000-0000-000000000001","","",""
```

|url               |username        |password|httpRealm|formActionOrigin|guid                                |timeCreated|timeLastUsed|timePasswordChanged|
|------------------|----------------|--------|---------|----------------|------------------------------------|-----------|------------|-------------------|
|https://apple.com/|user@example.com|password|Apple    |                |00000000-0000-0000-0000-000000000001|           |            |                   |

The columns can be in any order and they will be matched.

### Enable CSV import in Firefox
1. Open `about:config`
2. Set `security.allow_eval_in_parent_process` to `true`
3. Set `signon.management.page.fileImport.enabled` to `true`
4. Set those options back to `false` after importing the CSV

#### Import the CSV
1. Open `about:logins`
2. Click the dropdown button in the top right corner
3. Click `Import from a File...`
4. Select the CSV file and click the Import button
5. Review the import summary at `about:loginsimportreport`

Any existing entries will be updated.

### Documentation
* https://support.mozilla.org/en-US/kb/autofill-logins-firefox
* https://support.mozilla.org/en-US/kb/password-manager-remember-delete-edit-logins
* [Import logins from Firefox login export CSV files](https://bugzilla.mozilla.org/show_bug.cgi?id=1641777)

**Comment by moenodedev** [comment]
Safari on MacOS will also import logins in this CSV format. If the two factor token value is included in a OTPAuth column the "Verification Code" will be imported.

The Safari CSV export from the Password tab in the settings window exports these fields:
Title,URL,Username,Password,Notes,OTPAuth

**Comment by keepassium** [comment]
Thank you for the detailed description. 

I would generalize this as "CSV export from the Mac version", with specific format variations for Firefox and Safari. This would be redundant for the mobile app, but totally makes sense for the desktop version.

**Comment by moenodedev** [comment]
This functionality may be better as a separate program specifically for converting kdbx to csv because that would allow you to perform the export in a script or an [xbar](https://github.com/matryer/xbar) command.

**Comment by keepassium** [comment]
@moenodedev , there is already `keepassxc-cli export` for that :)

**Comment by moenodedev** [comment]
On desktop I already have KeeWeb since it has a clean and intuitive UI. I see that it has XML and HTML export. I don't want to install a mess of apps so  I decided to resubscribe to 1Password for now. I hope #259 can be resolved soon and that MacOS Auto Fill will be implemented in Firefox eventually.

**Comment by keepassium** [comment]
In the wide perspective, CSV export still makes sense for desktop KeePassium, so I will reopen this to keep it on the list.

**Comment by FreedomIsAChoice** [comment]
Hello,
can someone please explain to me what the guid means when exporting from FF? Is it relevant for the import?
Thank you in advance!

**Comment by keepassium** [comment]
@FreedomIsAChoice , KeePassium does not import/export data from/to other formats. You will get a more informed answer from Firefox team and that of the importing app.

**Comment by moenodedev** [comment]
Thank you!

**Comment by moenodedev** [comment]
https://github.com/keepassium/KeePassium/releases/tag/1.54.157
