### ISSUE TITLE
Add password generator options

### ISSUE THREAD

**Issue by tberta** [keepassium/KeePassium#263]
**What can be improved?**
i like to use passwords composed of several different words when I register on web sites. But I need also to match the sites requirements for password, that often include :
- Mixed case
- Numbers
- Special characters 
- A password length limit

The actual secret phrase generator 
- only include lower case / UPPERCASE and First Letter Upper Case. 
- Size can be only set as a number of words
- i need to add numbers and special chars manually

**The solution you'd like**
I’d like to have more choice for this password generator based on wordlist :
- a fourth case option, with alternating WORD case. Eg : MY example PASSWORD 
- Add padding digits (before and/or after words)
- Add some padding symbols (before and/or after words)
- Set the size as a number of characters instead of number of words.

**Alternatives you've considered**
Currently I use https://xkpasswd.net/s/ in the default config and am fully inspired by it for this suggestion / refinement request. 

Thanks for reading.

**Comment by keepassium** [comment]
Thank you for the suggestion.

I think I understand the rationale: passphrases are easier to type when required, but they are often rejected by too rigid password rules (numbers, special characters, max-length, etc). So it would be useful to throw in a random digit and a special character just to satisfy the checker.

That said, I don't quite see the point of overcomplicating this.

> Set the size as a number of characters instead of number of words.

The strength of passphrases is their long length. If a website restricts the maximum input length, it would be much safer to ~avoid it~ use a standard random password. If we have only 10 characters to fill, why waste them on a weak `4duckling%` if we could use a `Kf*q8aH#[6` instead?

> - a fourth case option, with alternating WORD case. Eg : MY example PASSWORD
> - Add padding digits (before and/or after words)
> - Add some padding symbols (before and/or after words)

Yes, these additions would increase the entropy of the generated password (no longer a phrase as such). At the cost of more complicated UI and more complicated typing.

A 7-word phrase from EFF long list is [7776^7](https://www.wolframalpha.com/input?i=7776%5E7) ~ 10^27 combinations. With random padding and alternating case, we can bump it up a bit. Is it worth the trouble, though? Why not just add another word or two?

**Comment by moenodedev** [comment]
Can you use an external program to generate passwords? [xbar](https://github.com/matryer/xbar) is a MacOS menu bar icon app with a [plugin for generating passwords](https://xbarapp.com/docs/plugins/Tools/password_bar.5m.php.html).

**Comment by keepassium** [comment]
@tberta , do you want to comment on the above? Without further feedback, I would have to close this…

**Comment by tberta** [comment]
@keepassium I understand your will to not over-complicate the UI. On this topic, Instead of modifying the UI of the passphrase mode, it could be an additional password mode.

The fact is that numerous web sites requires multiple categories of characters and very often limit the length of passwords. And I like yo use pronuncable (or easy to type if I need to) passwords. 

So I'm falling back to « pass phrase » mode of KeePassium, that I customize each time to add numbers.

Anyway it’s not a big deal. I close my suggestion. And if others find this suggestion relevant, they can vote or comment 😉

**Comment by keepassium** [comment]
@tberta , (a very late) thank you for the details. Considering that there were no similar requests so far, we can probably agree this would have been a very, very niche feature. So I'm afraid this won't be worked on.

**Comment by Doc-Steve** [comment]
@keepassium, I think @tberta has a point that these requirements (Mixed case, Numbers, Special characters, A password length limit) are necessary for a huge anount of sites.

You could use the extended password generator to fullfill this. The huge disadvantage is that if you ever have to type in your password on a mobile device or with an on screen keyboard on your TV with your remote you wish you wouldn't have used it 😀

So for some passwords I also like to use the passphrase generator. You could call it a niche - but nearly everyone has passwords that fit in that category, like Netflix etc.

Ofcourse there are very sophisticated solutions possible, but to not overcomplicate things I propose a small change to the passphrase generator:

- Adding an optional custom word field, which will be appened to the end of the generated passphrase. This custom defined word could contain special characters, numbers, mixed caps and the added passphrase would add additional security.
- If the custom word is used the minimum words for passphrases should be 1

I completely agree that these passwords would sometimes not have the same entropy as a  generated passphrase with many words, but for some usecases (e.g. Netflix) some people may consider the achieved security level enough for the risk profile of the given account. At the end, security and convenience is always a trade off.

Thanks in advance for considering to maybe reopen this feature request.

**Comment by freppair** [comment]
Apologies, I hadn't noticed this feature being mentioned in this issue before raising my own (#518). 

Personally I'd like to chip in and say that this feature (even if it's cut down to be closer to just adding numbers to the passphrase) would be useful for me too. Almost all the sites and services I interact with require the use of numbers and having to manually add a random number to a passphrase is not ideal.

Bitwardens passphrase generator has the option to add a number and it's a feature I miss. Here is their implementation on their website, but it's the same in all their applications too:

<img width="2844" height="1112" alt="Image" src="https://github.com/user-attachments/assets/f13c045c-71cc-409a-a2b6-c1d66c9271ff" />

Thanks for considering potentially re-opening this feature request.
