### ISSUE TITLE
List of favorite password entries

### ISSUE THREAD

**Issue by krehberger** [keepassium/KeePassium#264]
It would be helpful if passwords could be marked as "favorite" and that all favorite password entries can be shown in a list or as favorite group.

**Comment by keepassium** [comment]
Thank you for the suggestion! (And sorry for such a slow response.) 

Yes, this would be useful. Implementation-wise, however, this is a particular case of entry tags. So this will be implemented as part of #249. In the meanwhile, I would close this as a duplicate.

Thanks again!
