### ISSUE TITLE
Face ID loop on iPhone 14 Pro (Pro Max) running iOS 16.2

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#266]
Starting with iOS 16.2, iPhones with the "dynamic island" get stuck in Face ID loop: after a successful Face ID scan you get an animated checkmark, followed by another Face ID scan, over and over.

**Environment:**
 - Devices: only iPhone 14 Pro and Pro Max
 - OS: iOS 16.2 (earlier versions not affected)
 - App Version: 1.38.118 and earlier

**Additional context**

There are [multiple reports](https://www.reddit.com/r/iOSBeta/comments/zityun/ios162_rc_lingering_faceid_prompt/) that on affected devices the Face ID prompt stays visible a few seconds longer than usual, in all apps. Hypothetically, by the time the system returns control from Face ID to KeePassium, the app already locks up again. 

The issue does not reproduce on earlier iPhone models nor in iOS simulator. To debug this on device, I have ordered an iPhone 14 Pro, but it won't arrive before Friday. (Physical stores are out of stock due to the season.) In the meanwhile, I will try a few "blind" solutions via KeePassium beta and hopefully fix the issue before receiving the device.

**Temporary Workaround**

- If you see repeated Face ID prompts, cover the Face ID scanner with a hand.
- Wait a couple of seconds or simply tap the Face ID prompt to cancel it.
- You will see a passcode input screen, so you can unlock KeePassium with your passcode. (It is likely different from your database password.)
- Open KeePassium settings → App Protection → turn off the `Use Face ID` option. This way, KeePassium won't attempt Face ID scans and will show passcode input instead.

**Comment by keepassium** [comment]
Found, fixed and tested on device. Submitting to beta to confirm, then fast track to the App Store.

**Comment by keepassium** [comment]
The update was just approved by Apple and is already in the App Store.

**Comment by MikeCardiff** [comment]
I've just downloaded the latest version for iOS from the App Store (v1.38)

It's fixed the Face ID loop when launching the app from the homescreen (Thanks!) but it still happens when using the app to AutoFill passwords.

**Comment by keepassium** [comment]
Yep, can reproduce. I will look into it.

**Comment by keepassium** [comment]
As a workaround for the Face ID loop in AutoFill, increase the app protection timeout to 3 seconds.
