### ISSUE TITLE
New "Connect to OneDrive" feature - Unexpected server response format

### ISSUE THREAD

**Issue by alyssarowan** [keepassium/KeePassium#268]
**Description**
The actual signing in seems to work, but once the app gets access, it doesn't seem to be able to access the storage?

**How to reproduce**
1. Connection > OneDrive
2. Enter Username
3. Go to Authenticator, and approve sign-in
4. Approve link to the Keepassium app
5. See error.

**Expected behavior**
It should work.

**Screenshots**
![signal-2022-12-21-064602](https://user-images.githubusercontent.com/1591809/208839790-f5872f78-228a-4498-ac9a-74ee352cb049.png)

**Environment:**
 - Device: iPhone 12
 - OS: iOS 16.2
 - App Version: v1.38.121

**Additional context**
There is a caveat on the access that says only files you approve, but it seems to fail before picking files.

**Comment by keepassium** [comment]
Thanks! Yes, this is a bug. Sometimes OneDrive response is missing a field which is documented as mandatory. I got this fixed, will include in the next update. Hopefully, still this year :)

**Comment by keepassium** [comment]
The update is submitted to the App Store, now it's up to them :)
