### ISSUE TITLE
Revealing TOTP codes in folder view reveals every 16th TOTP code simultaneously

### ISSUE THREAD

**Issue by timothymhuang** [keepassium/KeePassium#277]
**Description**
Clicking the clock icon (to reveal the TOTP code) on an item in the list of your passwords reveals not just that TOTP code, but every 16th code.

**How to reproduce**
1. Open a database with at least 17 items in a single folder with TOTP added to each item, or at least every 16th item (e.g. 1,17,33,... or 5,21,37,...)
2. Click the clock icon to reveal a TOTP code.
3. Scroll down to see that other items have their TOTP code also revealed. You can also reveal multiple codes at once and they will both open every 16th code.
4. Note that if the next 16th item does not have TOTP enabled (so most normal vaults since most sites don't support TOTP), then it will appear like the bug doesn't exist, 

**Expected behavior**
Only the TOTP code of the item I select reveals itself.

**Screenshots**
Note: each item displays its own correct TOTP code, they just appear to be the same because I copied and pasted the same seed.
Video Demonstration: https://youtu.be/h8LoeHxLOJk

Images: Revealing the TOTP code for 2 also reveals the code for 18 and 34
![2FDA4333-A65B-45D9-BE0D-5011F210CE59L0001 png png](https://user-images.githubusercontent.com/59073651/222031502-88d8980c-e697-4818-ab1d-73abe853293a.jpg)
![DA5FEB0D-BEA6-49DC-B21A-AAACCC0C686EL0001 png png](https://user-images.githubusercontent.com/59073651/222031559-1f1b10f2-8431-4ed3-bc9b-a6a1f6f23e99.jpg)
![BF633059-E786-43B4-9D4A-64447D8DA7C2L0001 png png](https://user-images.githubusercontent.com/59073651/222031539-88f1d911-320f-4f48-adbb-4fc65d38d36a.jpg)

**Environment:**
 - Device: iPhone SE 2020
 - OS: iOS 16.2
 - App Version: v1.41.126

**Additional context**

**Comment by keepassium** [comment]
Wow, this is one thorough bug report! 
Thank you, Timothy. I will get this fixed.
