### ISSUE TITLE
macOS: use the Sort By icon only for Sort By and nothing else

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#282]
**What can be improved?**
It's a small detail. The Sort By icon is not only used for Sort By, but also for Entry Subtitle.

**The solution you'd like**
Replace the "Change Master Key" icon with an "Entry Subtitle" icon.
Move the "Change Master Key" option to another place in the UI. For example under File:
![Screenshot 2023-03-08 at 21 39 20](https://user-images.githubusercontent.com/86680397/223844706-f88a49bc-bc37-4b68-93b8-eacc621eb363.png)

Also you don't have to go through Sort By or Entry Subtitle when clicking on the Sort By icon.

**Additional context**
Changing the entry subtitle probably happens more than changing the master key.

![Screenshot 2023-03-08 at 21 25 35](https://user-images.githubusercontent.com/86680397/223843877-43bf0119-75e4-4411-a461-ccb84153110a.png)

**Comment by keepassium** [comment]
That button represents list/view settings. If I remember correctly, it was inspired by the earlier UI of the iOS Files app. Yes, the Mac version shows its mobile roots here again :)

I agree that "Change Master Key" needs to be buried somewhere deeper, and this will happen once there is a more appropriate feature requiring that space on the bottom toolbar. But "Entry Subtitle" is not it: it's a view option, and a rarely changed at this. So I would rather keep it where it is.
