### ISSUE TITLE
Add "clone"/"copy" suffix when creating a copy of an entry

### ISSUE THREAD

**Issue by OculiViridi** [keepassium/KeePassium#284]
### What I'd like
Like other KeePass managers do, I'm asking to add a simple suffix like "clone" or "copy" to the name of an entry when copied.

### Why
It would make the original entry distinguishable from the newly created cloned one.

**Comment by keepassium** [comment]
Thank you for the suggestion! I'm not quite sure about the rationale, though…  

As I see it, a user copying an entry either wants to 1) have an exact copy (including the title) or 2) plans to rename it. Currently, the first action is pretty much immediate; we cannot speed up the second one anyway. Automatically adding "copy" means _everyone_ will have to rename the cloned entry. So this would hinder the first action without improving the second one.

What am I missing?

**Comment by keepassium** [comment]
@OculiViridi, since there were no similar requests so far, this seems to be a rather niche case. I'm afraid this means no suffixes or popups for the time being…
