### ISSUE TITLE
Error for database missing when using iOS File app with Resilio Sync

### ISSUE THREAD

**Issue by s-kk** [keepassium/KeePassium#288]
**Description**
KeePassium prompts for missing database error when using iOS File app with Resilio Sync app.

**How to reproduce**
1. Setup KeePassium on iOS with a database synced by Resilio Sync app.
2. Make changes to the database somewhere else (e.g. add an entry on PC with KeePassXC).
3. Sync the database by opening the Resilio Sync app.
4. Open KeePassium, and sometimes (5 out of 10) the error for missing database would occur.

**Expected behavior**
The synced and updated database would open with no errors. 

**Screenshots**
None for now as I did not collect screenshots when the bug occurred, but could be provided if needed. Basically it's app complaining for missing database and request to open a previous version of database. 

**Environment:**
 - Device: iPhone 13 Pro
 - OS: 16.4
 - App Version: 1.42

**Additional context**
N/A

**Comment by keepassium** [comment]
In general, this would be the storage app's issue. I mean, KeePassium does not control the database, and if there is any problem with the file (such as the system says there is no such file) — there is not much I can do about it.

That said, a database going missing after editing on a desktop sounds familiar and has a simple solution: https://keepassium.com/articles/sync-troubleshooting/#does-not-exist

**Comment by caesarw** [comment]
Thanks for the reply. But why doesn't the bug occur every time I saved on desktop and synced to my phone? In my experience, it only does so at 50% chance.

**Comment by keepassium** [comment]
> But why doesn't the bug occur every time I saved on desktop and synced to my phone? In my experience, it only does so at 50% chance.

Good point, so maybe this is a different issue. I cannot offer a better insight here — this is an integration issue between Resilio Sync and iOS, not KeePassium's bug.
