### ISSUE TITLE
Add an option in Settings to choose which databases should be used for AutoFill

### ISSUE THREAD

**Issue by OculiViridi** [keepassium/KeePassium#289]
### What I'd like

An option in KeePassium AutoFill settings where to choose which databases have to be used for the AutoFill feature.
Something like:

AutoFill settings -> Lookup on... -> List of all existing databases with on/off switch

_Note: With AutoFill I also include the Quick AutoFill feature too, that I suppose it's already built as a sub functionality of the main one._

### Why

I've many different databases inside KeePassium (mine, my wife's, work, other stuff...). But when I use the AutoFill on the phone, I would like the credential lookup to happen only within my database and not the others.
When I need credentials stored on other databases is not for using them on my phone, but on other devices like my wife's PC, work PC, other's PC.

**Comment by keepassium** [comment]
@OculiViridi, sorry for such a slow response. I confirm this will be part of database-specific settings (#64), which is nearing the top of the list.

**Comment by OculiViridi** [comment]
@keepassium Hi! Is it still under planning for future release?

**Comment by keepassium** [comment]
@OculiViridi , yes, I have added a switch to disable Quick AutoFill for the specific database:

![db-settings-2023-09-09](https://github.com/keepassium/KeePassium/assets/38399598/3bf3d7dd-2e99-47f9-af25-8031f1ca1945)

Would this work for you?

**Comment by keepassium** [comment]
@OculiViridi , sorry, I should have been more specific. I have added the "Quick AutoFill" switch to the _development_ version which has not been published yet. Just wanted to check if this switch would work for you or you would need a more elaborate configuration.

**Comment by OculiViridi** [comment]
@keepassium Oh, ok! 😄 
Anyway, if possible, I think it would be more intuitive to find the option under the AutoFill settings and also it would be more convenient to set the option for each database all in one place (using the DB list I was originally suggesting).

**Comment by keepassium** [comment]
>  it would be more convenient to set the option for each database all in one place (using the DB list I was originally suggesting).

Bulk editing of this setting is convenient when there are _many_ databases (like in your case) or their settings change often. However, I believe a more typical setup is 1-3 databases where it's easier to apply changes to each database than dig several levels into the app settings. 

If this assumption proves wrong, I will consider a dedicated list. But for now let's stick with the individual dialog for each DB .

**Comment by OculiViridi** [comment]
> Bulk editing of this setting is convenient when there are _many_ databases (like in your case) or their settings change often. However, I believe a more typical setup is 1-3 databases...

Think about a freelance IT Administrator... he may have tens of different KeePass DBs, one for each company he works for. He may need to use AutoFill when using browser from a tablet to login into different system administration consoles (RDP or others).

**Comment by keepassium** [comment]
Once IT administrators start complaining _en masse_, we can consider the assumption proved wrong. So far this was not the case.

**Comment by keepassium** [comment]
Closing as resolved in 2023 :)
