### ISSUE TITLE
Touch ID does not unlock database

### ISSUE THREAD

**Issue by freebrowser1** [keepassium/KeePassium#291]
**Description**
Using toch ID only works for unlock app, but I still have to fill in the password.
Very inconvenient.

**How to reproduce**
1. Enable Applock with Touch ID
2. Open database and fill in password.
3. Close database by clicking on the padlock button below left
4. Open app again after a few minutes 
5. Fingering the Touch ID does open the app, but not the database so one still has to fill in the password.

**Expected behavior**
Database should open as well.

**Screenshots**

**Environment:**
 - Device: iPad Air 2022 edition
 - OS: iOS 16.4
 - App Version: 1.42

**Additional context**
Other similar apps based on Keepass (KeepassXC (macOS), KeepassDroid (Android) or Kypass (iOS)) do allow unlocking the database by fingering.

**Comment by keepassium** [comment]
> Touch ID does open the app, but not the database so one still has to fill in the password.

This is the intended behavior after pressing the "Lock database" (🔒) button. That button  _closes and locks_ the database (erasing its stored master key). 

If you want to _close_ the database without locking it (so you won't have to type in the password the next time), use the top-left `< Back` button instead.
