### ISSUE TITLE
Tap on 'Print'-button crashes app

### ISSUE THREAD

**Issue by Heiland** [keepassium/KeePassium#294]
**Description**
Pressing the 'Print'-button in the lower appbar leads to a crash of the app after about 1 second.

**How to reproduce**
1. Open KeePassium
2. Tap on 'Print'-button
3. App crashes after about 1 second

**Expected behavior**
App not crashing.

**Screenshots**
---

**Environment:**
 - Device: iPhone 11 Pro
 - OS: 16.5
 - App Version: v1.43.132

**Additional context**
---

**Comment by keepassium** [comment]
This is likely an iOS bug ([ongoing from iOS 15](https://developer.apple.com/forums/thread/689876)).

Can you please post or email me the crash log to confirm? It should be in device settings → Privacy & Security → Analytics & Improvements → Analytics Data → KeePassium *

**Comment by Heiland** [comment]
Thank you for the information - sad to hear this is an ongoing bug of iOS for over a year.

As requested please find the log below:
[KeePassium-2023-05-21-213156.zip](https://github.com/keepassium/KeePassium/files/11525388/KeePassium-2023-05-21-213156.zip)

**Comment by keepassium** [comment]
Thanks for the log. Indeed, the crash happens deep in Apple's code and is similar to [other developers' reports](https://developer.apple.com/forums/thread/718398?answerId=746800022#746800022).


    Thread 0 name:   Dispatch queue: com.apple.main-thread
    Thread 0 Crashed:
    0   CoreGraphics        0x1ba955d7c CGContextDrawPDFPageWithDrawingCallbacks + 116
    1   CoreGraphics        0x1ba8f3fbc CGContextDrawPDFPage + 36
    2   PrintKitUI          0x20252a7e4 getPageImageForPage + 1632
    3   PrintKitUI          0x20254cb44 -[UIPrintPreviewPageFetcher _drawPageContextIntoImage:] + 296
    4   PrintKitUI          0x20254c3c8 -[UIPrintPreviewPageFetcher sheetImageForItemAt:] + 112
    5   PrintKitUI          0x20251d214 -[UIPrintPreviewViewController collectionView:cellForItemAtIndexPath:] + 132
    6   UIKitCore           0x1bafefa44 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 980
    7   UIKitCore           0x1bb5a00cc -[UICollectionView _createVisibleViewsForSingleCategoryAttributes:limitCreation:fadeForBoundsChange:] + 1120
    8   UIKitCore           0x1bb5a03a4 -[UICollectionView _createVisibleViewsForAttributes:fadeForBoundsChange:notifyLayoutForVisibleCellsPass:] + 288
    9   UIKitCore           0x1baecf6dc -[UICollectionView _updateVisibleCellsNow:] + 1612
    10  UIKitCore           0x1baecefa0 -[UICollectionView layoutSubviews] + 304
    11  UIKitCore           0x1baeaabe0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1992
    12  QuartzCore          0x1ba365074 CA::Layer::layout_if_needed(CA::Transaction*) + 500
    13  QuartzCore          0x1ba3785f0 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
    14  QuartzCore          0x1ba389a1c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 444
    15  QuartzCore          0x1ba3b8ff4 CA::Transaction::commit() + 648
    16  QuartzCore          0x1ba3a2f3c CA::Transaction::flush_as_runloop_observer(bool) + 88
    17  CoreFoundation      0x1b8ec7234 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
    18  CoreFoundation      0x1b8e51410 __CFRunLoopDoObservers + 532
    19  CoreFoundation      0x1b8eb119c __CFRunLoopRun + 1028
    20  CoreFoundation      0x1b8eb63ec CFRunLoopRunSpecific + 612
    21  GraphicsServices    0x1f437b35c GSEventRunModal + 164
    22  UIKitCore           0x1bb2436e8 -[UIApplication _run] + 888
    23  UIKitCore           0x1bb24334c UIApplicationMain + 340
    24  KeePassium          0x100f354d8 main + 21720 (<compiler-generated>:0)
    25  dyld                0x1d83b6dec start + 2220
