### ISSUE TITLE
OneDrive sync not working

### ISSUE THREAD

**Issue by OculiViridi** [keepassium/KeePassium#296]
### Description

From yesterday my OneDrive sync doesn't work anymore. Whever I open the app or refresh the db list I always get the "OneDrive not responding" error.
I removed all the databases, backups and keys and then tried to re-insert them but when I select the database from the iFile app, I get back to KeePassium and nothing happens. The file is not imported.
I even tried to completly remove the app and reinstall it, but nothing changes.
From Microsoft, the status of OneDrive API seems to be ok.

From OneDrive app I can browse all my files normally and the same from the iFile app.

### Environment
- Device: iPhone XS
- OS: iOS 16.4.1 (a)
- App Version: 1.44.134

**Comment by keepassium** [comment]
Looks like duplicate of #248. Discussion there covers most of possible reasons and solutions.
