### ISSUE TITLE
[Feature Request] Add option to not hide info on the thumbnail of App Switcher

### ISSUE THREAD

**Issue by SuperTachyon** [keepassium/KeePassium#30]
Currently the thumbnail is blank on App Switcher regardless if the app is locked. It would be great if it shows normal thumbnail when unlocked.

**Comment by keepassium** [comment]
Thanks! 

Can you describe in more details why you need / how you use the "normal thumbnail"?

**Comment by SuperTachyon** [comment]
It’s probably purely cosmetic. I’m coming from 1Password which behaves like that. I feel that is more natural from the perspective of  consistency with the rest of the os.

**Comment by keepassium** [comment]
To be honest, I have mixed feelings about this. 

On one hand — why not? Another option in the settings is not a big deal.

On the other hand, however, there are a couple of considerations.

Firstly, the technical one. The thumbnail screenshot is created when you leave the app, and — as far as I know — cannot be updated while the app is in background. So if the app locks up while in background — all the sensitive data will remain visible in App Switcher. Not cool.

Secondly, the priorities. For a password manager, the main priority is to protect its content. Aesthetics is certainly nice to have, but not at the expense of security. 

KeePassium has to guarantee that no matter what, a third person won't get even a glance at the app. Currently, this is controlled by two directly related options: `AppLock Enabled` and `AppLock Timeout`. By adding a third (unrelated) option, a-la `Cover when in background`, KeePassium would increase the chances of accidental misconfiguration and data exposure. Admittedly, such cases would be rare — but with very high impact for the user. A minor aesthetic improvement does not seem to justify the risk.

For any other app, the decision would have been easy to make. Simply add the switch, wait for a month, and check in-app analytics to see how many people actually use this option. For KeePassium, this is not an option, so I would appreciate more feedback why such a feature would be important/useful. So far, it does not seem to be worth the risk it carries...

**Comment by SuperTachyon** [comment]
I’m not sure if the technical limitations are still present on the current iOS, based on some conversations with Strongbox’s developer. I do agree with your other concerns, which are definitely  problematic when the technical issues still apply now.

**Comment by keepassium** [comment]
I have taken a deeper look into the pros and cons of this feature. 

Regarding the consistency, there are [these guidelines](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background#3222195):

> Prepare Your UI for the App Snapshot
>
> (...) Your app’s UI must not contain any sensitive user information, such as passwords or credit card numbers. If your interface contains such information, remove it from your views when entering the background.

So hiding any sensitive info when in background is the recommended approach. For KeePassium, "sensitive info" is pretty much everything (except the AppLock Passcode input dialog).

The technical limitation, in contrast, might be lifted soon. The [current method](https://developer.apple.com/documentation/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva) for background app refresh might be arbitrarily delayed by the system, and thus is not reliable for a critical task. However, there will be [more options](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler) in the upcoming iOS 13.

It is very hard to say "no" to a nice feature, especially in such borderline case. But I don't think it outweighs the security concerns it brings. At least for now. Sorry about that.

I will be happy to reopen if there are more similar requests, or if the standards change with iOS 13.

**Comment by SuperTachyon** [comment]
I suggest you take a look at the behaviour of 1Password, which feels much smoother. The lack of polish of apps for KeePass is a big hurdle for adoption and growth.

**Comment by keepassium** [comment]
Will do, thanks!

> The lack of polish of apps for KeePass is a big hurdle for adoption and growth.

Touché. This is exactly the problem KeePassium is aiming to solve. 

Learning from more polished apps (such as 1Password) is of course a good way to achieve this. This will take some time, though...
