### ISSUE TITLE
Add credentials for a website right from the autofill window on iOS

### ISSUE THREAD

**Issue by ropepop** [keepassium/KeePassium#301]
I’d like to be able to add credentials for a website right from the autofill window on iOS when on a website or in app. Right now it is possible to add new credentials only via app.

I would appreciate the convenience and saving a dozen of seconds because of being able to add a new credential to the database when there are already or zero records for a website without leaving browser/app right in the autofill window.
Nice example of how it could be done is ios default keychain![image](https://github.com/keepassium/KeePassium/assets/35100425/6b17c0ef-a96c-4d70-8ef6-10ed8ef96819)

**Comment by keepassium** [comment]
Thank you! This is already discussed in #87, though.
