### ISSUE TITLE
Autofill TOTP with iOS 16+

### ISSUE THREAD

**Issue by hkaancaliskan** [keepassium/KeePassium#307]
with iOS 16, 3rd party apps can autofill TOTP. It would be great if Keepassium would do that instead of copying to clipboard.

**Comment by hkaancaliskan** [comment]
BTW, app is just great. Thank you! I've bought the yearly premium and i have a small question. As of right now, does this app financially sustainable?

**Comment by keepassium** [comment]
> with iOS 16, 3th party apps can autofill TOTP.

Can you provide a source for this statement, please?

> As of right now, does this app financially sustainable?

Yes. Earlier this year KeePassium even evolved from a personal project into a namesake company.

**Comment by hkaancaliskan** [comment]
https://www.macrumors.com/2022/06/06/ios-16-third-party-two-factor-authentication-support/

**Comment by keepassium** [comment]
Yeah... Apple being Apple, that feature is only for TOTP _setup_. Basically, it defines which app would open when you tap an `otpauth://` URL with TOTP configuration. Not related to AutoFill at all, unfortunately.

**Comment by hkaancaliskan** [comment]
oh god... thank you.

**Comment by Maasea** [comment]
In fact, the setting does support auto-fill, but it requires Apple to detect that it is a 2FA input field. 

I have added Google's TOTP in the Apple Keychain, and it can be recognized for auto-fill.

I will show you a simple screen recording.  @keepassium 


https://github.com/keepassium/KeePassium/assets/41108003/c77a376f-a180-40b6-91ae-5051e6d89136

**Comment by keepassium** [comment]
@Maasea , your AutoFill provider is Keychain, not Google Authenticator. 

Let me outline the facts:
- iCloud Keychain supports TOTP code setup ([iOS 15+](https://support.apple.com/guide/iphone/automatically-fill-in-verification-codes-ipha6173c19f/15.0/ios/15.0))
- iCloud Keychain can auto-fill TOTP codes, too ([iOS 15+](https://support.apple.com/guide/iphone/automatically-fill-in-verification-codes-ipha6173c19f/15.0/ios/15.0))
- Third-party apps can be selected for TOTP setup (iOS 16+) — this is discussed in MacRumors article above.
- Third-party apps **cannot** auto-fill TOTP codes. Not in iOS 16, nor in upcoming iOS 17. The [corresponding API](https://developer.apple.com/documentation/authenticationservices/aspasswordcredential) still includes only username and password (and a separate API for passkeys).

The settings page is also very clear about the "setup" part:
![IMG_1871](https://github.com/keepassium/KeePassium/assets/38399598/6ef0e161-e2ff-40af-ba40-685c67859df5)

So yeah, would be great to have this possible, but unfortunately Apple locked this out for everyone (but themselves).
