### ISSUE TITLE
Sync issues via Mobius Sync

### ISSUE THREAD

**Issue by Aliaksandrsen** [keepassium/KeePassium#308]
**Description**
After adding the changes to **KeePassXC** on the desktop (I used options:
Use alternative saving method → turn it on
Set it to Directly write to database file (dangerous))

After sync (I used **Mobius Sync** on ios)  my db do not updated (
And I continue to use old db with another name `myDBname~20230822-093850.kdbx`

And every time I need delete with old DB with this strange name and manualy add updated synced `myDBname.kdbx`

**Expected behavior**
I do not need delete old DB and and re-enter the database.

**Environment:**
 - Device: [e.g. iPhone 13]
 - OS: [e.g. iOS16.6]
 - App Version: [e.g. 1.45.138]

**Comment by keepassium** [comment]
> After sync (I used Mobius Sync on ios) my db do not updated (
> And I continue to use old db with another name myDBname~20230822-093850.kdbx

It sounds like Mobius Sync itself renames the original file and creates a new one in its place. Changing the KeePassXC' settings may or may not be relevant here. 

In either case, KeePassium only shows the content of the file reference it was given; it is MSync's responsibility to update that content. I would suggest to raise this issue in https://github.com/MobiusSync/MobiusSync/issues/ or, if you use MSync's experimental sync, in [this specific thread](https://github.com/MobiusSync/MobiusSync/discussions/102).

**Comment by Aliaksandrsen** [comment]
Yes thank you, I already resolve this issue main reason of that was that version control in Mobius app was turn on. When I turned it off - it become sync as expected.

**Comment by Aliaksandrsen** [comment]
resolved by turn off version control in Mobius app
