### ISSUE TITLE
AutoFill sorting

### ISSUE THREAD

**Issue by rderensy** [keepassium/KeePassium#31]
When you set the sort option for the database (in the app) to "Name (A..Z)" for example, this sorting is not applied in the AutoFill GUI, it just shows every entries sorted by default.

**Comment by keepassium** [comment]
Thanks!

**Comment by norbertc** [comment]
it seems sorting on autofill was removed. sometimes, autofill does not match any url and search auto closes so the only thing that will work is manually selecting the entry during autofill. but the option to sort on autofill was removed. on main app, sorting of entries works.
