### ISSUE TITLE
Credit card template

### ISSUE THREAD

**Issue by hkaancaliskan** [keepassium/KeePassium#311]
I want to store credit cards in keepassium and keep them safe but there is no template to store them properly.

Required fields:
- Card name (alias)
- Name surname
- Card number
- Exp. date
- CVV

Yes, i can store them as a note but that's not the proper way, i can't copy quickly that way :) 

Thanks!

**Comment by keepassium** [comment]
Unfortunately, templates are not foreseen in the database format. Even if KeePassium implements its own templating system, this won't work in other apps. So I can only suggest to create custom fields for the card details. This won't show up too pretty or customized, but it will be portable (and easy to copy :)
