### ISSUE TITLE
Option to make Notes content sensitive (hidden like the password)

### ISSUE THREAD

**Issue by moenodedev** [keepassium/KeePassium#312]
It would be helpful to have a global option to hide Notes content until it's revealed.

If you're using multiple OSes and apps to access your KeePass database then you may only be using the basic fields for portability (Title, URL, Username, Password, Notes, OTPAuth). Notes is the only freeform field of those but if you have private info in it that content is displayed when viewing a login entry.

<img width="489" alt="screenshot" src="https://github.com/keepassium/KeePassium/assets/113457600/e80eb67a-ea75-42ac-bbb1-6dc2de6b6500">

<img width="150" alt="screenshot" src="https://github.com/keepassium/KeePassium/assets/113457600/1521e6fe-7712-4114-94ab-74a6a72f61c6">

**Comment by keepassium** [comment]
Just keep sensitive info in custom fields. (This also simplifies copy-pasting, by the way.) 

Custom fields are first-class citizens of the `kdbx` format which has been around more than 10 years. In fact, today it's harder to find an app that supports the old `kdb` format. So the portability argument is very weak... 

And if someone chooses to use `kdb` for %reasons% — well, it does not support field visibility anyway…

**Comment by moenodedev** [comment]
You're right. Custom sensitive fields are easy and work in other apps. I was trying to avoid customizing the database too much.
