### ISSUE TITLE
Support official OTP field names

### ISSUE THREAD

**Issue by xtrafrancyz** [keepassium/KeePassium#314]
**Describe the feature you'd like**
Support for official format of OTP settings for entry as described https://keepass.info/help/base/placeholders.html#otp and introduced in 2.47. Here is an example implementation from android https://github.com/Kunzisoft/KeePassDX/commit/dc40b50b65f7ccb1e22857b24ef162cc996a8a57.

**Why**
I want to use the same database on all devices and it is a must to support official OTP settings.

**Comment by keepassium** [comment]
Ohh, don't get me started… 

Dominik added OTP support very late (2021), when all the other apps have already played with a zoo of custom formats and settled on the industry-standard `otpauth` URIs. Dominik ignored all that and invented his own format. Not compatible with anyone else. Some devs gave in and silently added support for this new format. However, I find this kind of behaviour unacceptable and cannot condone it, so there are no plans to add support for Dominik's `TimeOtp-*` format. 

Moreover, if you setup an OTP in virtually any mobile app, you would end up with the `otpauth` URI that KeePass won't understand anyway. You would need the KeePassOTP plugin for that.

> I want to use the same database on all devices and it is a must to support official OTP settings.

Use [KeePassXC](https://keepassxc.org), it works on all desktop OSes, uses the standard OTP field format and plays well with other apps.

Context:
- https://sourceforge.net/p/keepass/discussion/329221/thread/c60ede8b94/
- https://sourceforge.net/p/keepass/discussion/329220/thread/6127495b5d/

**Comment by keepassium** [comment]
As of today, you have several workaround options:
- Bridge the gap in everybody-to-KeePass direction using the KeePassOTP plugin. However, OTP configurations set up in KeePass won’t work in other apps.
- Bridge the gap in KeePass-to-everybody direction by creating a field named `otp` with value `otpauth://totp/?secret={S:TimeOtp-Secret-Base32}`. This reference will dynamically fetch the KeePass-specific field value, generate the standard otpauth URI, and generate the codes. However, KeePass won’t understand OTP configurations set up in other apps.
- Ask Dominik to add support for the community-standard format.
- Replace KeePass with KeePassXC, it just works™.
