### ISSUE TITLE
Define a pasteboard type on macOS to prevent clipboard managers from saving an entry

### ISSUE THREAD

**Issue by piercefaulkner** [keepassium/KeePassium#315]
**What can be improved?**
Define a pasteboard type on macOS to prevent clipboard managers from saving an entry.

**The solution you'd like**
Instead of writing to the "general" pasteboard, define an app-specific pasteboard, for example `com.keepassium`.

**Alternatives you've considered**
[Maccy](https://github.com/p0deje/Maccy) allows you to specify apps to ignore but that method is not reliable.

<img width="613" alt="maccy" src="https://github.com/keepassium/KeePassium/assets/86799892/a645945c-fb87-4f0c-9d20-7965e68f8ee5">

**Comment by keepassium** [comment]
Thank you for the feedback. 

>  Instead of writing to the "general" pasteboard, define an app-specific pasteboard

Perhaps I misunderstand your suggestion, but [according to Apple](https://developer.apple.com/documentation/uikit/uipasteboard/) it won't work:
> For sharing data with any other app, use the systemwide general pasteboard.

> You can create named pasteboards (…) for sharing data within your app, and from your app to other apps that have the same Team ID.

**Comment by piercefaulkner** [comment]
What about using transient as suggested in https://github.com/p0deje/Maccy/issues/65#issuecomment-555785043?

https://github.com/p0deje/Maccy/commit/fa83d5f163592a61c1474b2f10dee4bd356a43d8

https://github.com/p0deje/Maccy/issues/53
https://github.com/p0deje/Maccy/pull/147
https://github.com/p0deje/Maccy/issues/65
https://github.com/p0deje/Maccy/issues/79
https://github.com/p0deje/Maccy/issues/94

http://nspasteboard.org
http://nspasteboard.org/Site/Transient.html

**Comment by keepassium** [comment]
Done and will be in the next update.
Thank you, @piercefaulkner.
