### ISSUE TITLE
Make up and down keys navigate group and login entries

### ISSUE THREAD

**Issue by piercefaulkner** [keepassium/KeePassium#316]
**What can be improved?**
Make up and down keys navigate items (groups and login entries) in the left sidebar

**Alternatives you've considered**
ctrl+n and ctrl+p instead of up and down

**Comment by keepassium** [comment]
Can you elaborate on the context, please? On macOS 13.5 keyboard navigation already works (not as good as I'd like it to, but up/down arrows do traverse the list on the left).

**Comment by piercefaulkner** [comment]
up/down don't doesn't work on my MacBook on macOS 13.5.2
