### ISSUE TITLE
Tab into the search results list from the search field

### ISSUE THREAD

**Issue by piercefaulkner** [keepassium/KeePassium#317]
**What can be improved?**
Pressing tab from the search field should select the first result

**Alternatives you've considered**
Pressing up or down but those keys should be reserved for going to the beginning or end of the search query (the current functionality)

Related to #316

**Comment by piercefaulkner** [comment]
Duplicate of #281

**Comment by keepassium** [comment]
Tab order in the Mac version definitely needs some work. However, in this specific case I would argue that up/down arrows are better suited for the task. 

Navigating the text fields, such as search query, is better done with Cmd-Left (text start) / Cmd-Right (text end), with the bonus of Option-Left/Option-Right for word-by-word navigation. At least these are the [official Document navigation shortcuts](https://support.apple.com/en-us/HT201236#text).

**Comment by piercefaulkner** [comment]
up/down don't work on my MacBook on macOS 13.5.2
