### ISSUE TITLE
Favicons in SVG format are not downloaded

### ISSUE THREAD

**Issue by vit9696** [keepassium/KeePassium#319]
**Description**
Websites with SVG favicons fail to download their icons.

**How to reproduce**
1. Create an entry for some website with SVG favicons (e.g. `vseinstrumenti.ru`)
2. Try to download the icon.

**Expected behavior**
Expect a favicon to be downloaded (i.e. `vseinstrumenti.ru/favicon.svg`).

**Environment:**
 - Device: MP7,1
 - OS: macOS 13.6
 - App Version: 1.46 (from TestFlight)

**Comment by keepassium** [comment]
KeePassium uses the standard `UIImage` class which natively supports the most common formats like PNG and JPEG. Apparently, it [does not](https://developer.apple.com/forums/thread/676031) support external SVGs. Possible workarounds involve heavy frameworks like WebKit or SVGKit, which are just not worth adding for such an edge case. 

So while I can reproduce the bug, I'm afraid it won't be fixed until Apple updates `UIImage`.

**Comment by vit9696** [comment]
SVG itself does not have size and thus needs to be rendered before it can be displayed, so I am afraid `UIImage` will unlikely support it natively. Such images need to be converted to pixels first, i.e. png or bmp. I understand that using other frameworks might be complicated, but perhaps the issue should stay open till an easier to use API is found.

**Comment by keepassium** [comment]
This is too niche a case of an already niche feature. I believe that most sites adopting an SVG favicon will have the common courtesy of a raster fallback — be it for legacy devices or, ahem, for [latest Safari](https://caniuse.com/link-icon-svg). Exceptions such as the one you linked will need to be converted and imported by the user manually. 

By closing the issue I just want to be transparent this won't be worked on. It is unsustainable to keep issues opened indefinitely "just in case". (Admittedly, there are a few counter-examples to this statement in this very tracker, but I am doing my best to trim them occasionally.)
