### ISSUE TITLE
Recommend KeePassium not working

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#32]
Just gave the App Store version a spin, and when taping the “Recommend KeePassium” entry in the settings menu I arrive at the App Store with the error message “Could not connect to App Store”.

As I have no issues with navigating anywhere else in the App Store, a wild guess is the App ID or something is wrong, or maybe Apple is a bit slow to add the reference for apps that has just been released?

**Comment by magebarf** [comment]
Just noticed the same goes for the “Like KeePassium?” entry in the About KeePassium section.

**Comment by keepassium** [comment]
Ouch... Thanks!
