### ISSUE TITLE
Crash on Quick Fill

### ISSUE THREAD

**Issue by IANatCAMBIO** [keepassium/KeePassium#328]
**Description**
On Mac OS, quick fill displays a dropdown with entries. These show a "thumbprint" icon next to them. If the entry is highlighted, and I then use my fingerprint reader, then the quick fill works well. If instead of using my fingerprint reader, I simply click the entry, it will crash both Keepassium AND Safari itself.

**How to reproduce**
On MacOS, enable quickfill.
In Safari, go to a website matching an entry in your Keepass DB.
When the quick fill dropdown is shown, click an entry instead of using the fingerprint reader.

**Expected behavior**
I usually use an external Keyboard and Mouse with my Macbook Pro, so I don't have access to the fingerprint reader (laptop is closed). Anytime I see a click a touchID prompt in other apps, it will realize that the laptop is closed, and prompt my for my password instead.

**Screenshots**
<img width="1146" alt="Screenshot 2023-11-14 at 10 33 41 AM" src="https://github.com/keepassium/KeePassium/assets/52396492/921c003f-a85e-4ef0-8700-6aee5dbde34f">

**Environment:**
 - Device: M1 Macbook Pro
 - OS: Ventura 13.6
 - App Version: 1.46.140

**Additional context**
I've always just clicked "Keepassium ..." and manually selected the PW. That usually works fine, but it also has bugs sometimes.

**Comment by keepassium** [comment]
Thank you for the report!
> If instead of using my fingerprint reader, I simply click the entry, it will crash both Keepassium AND Safari itself.

I'm afraid this belongs to Apple's bug tracker… No matter how wrong things go on app extension's side (KeePassium AutoFill), this should not crash the host app (Safari). The fact that Safari crashes indicates the problem is on system's side.

On a more positive side, I cannot reproduce this on macOS 14.1 either. So probably they ultimately fixed it.
