### ISSUE TITLE
Unify the 'main' and 'autofill' processes

### ISSUE THREAD

**Issue by IANatCAMBIO** [keepassium/KeePassium#329]
**What can be improved?**
On my M1 Macbook Pro, the Safari autofill USUALLY works if I click "keepassium..." in the dropdown and select the password. BUT, occasionally (maybe once a week) the autofill process gets hung up. In the Keepassium autofill popup, no mouse or keyboard events are registered. Oddly enough, the only thing that does work is pressing ESC to go 'back' in the autofill popup.

To resolve this, I have to open Activity Monitor and forcekill the autofill Keepassium process.

**The solution you'd like**
I usually work with the "main" Keepassium process open anyway, and it never has problems. Is there anyway to simply use that running process instead of an additional process dedicated to autofill? Some clients like MacPass simply prompt you during autofill that the "main" process is not running and ask you to open it.

**Alternatives you've considered**
I like MacPass, but thier autofill is even worse than Keepassium. Plus Keepassium works on my phone too.

**Additional context**
I've opened a bug ticket for this behaviour in the past, but devs were unable to replicate it. I'm not running anything non standard with Safari, and only 1 extension (WIPR). Since killing the autofill only process seems to fix things, and I never have any problems with the 'main' keepassium process, thought maybe we could just use that one for autofill instead.

**Comment by keepassium** [comment]
> In the Keepassium autofill popup, no mouse or keyboard events are registered. Oddly enough, the only thing that does work is pressing ESC to go 'back' in the autofill popup.

This is definitely #230.

> Is there anyway to simply use that running process instead of an additional process dedicated to autofill? 

This is managed by the system. AutoFill is an app extension and they run in a separate process. This introduces some challenges, but there is nothing we can do about it...
