### ISSUE TITLE
Settings menu “squished” when returning from sub menu

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#33]
After navigating to a sub menu in the settings section, upon return to the main settings section the menu is slightly “squished”. The descriptive text under the ”Start” entry creeps up into the field itself.

Attaching screenshot to easier understand.
![4FD6C75B-2BFD-4970-BED3-5A1ABEA31FCF](https://user-images.githubusercontent.com/3879511/62212835-e5eafd00-b3a1-11e9-8a16-f44594231aff.png)

**Comment by keepassium** [comment]
That's odd... Is this the App Store version with the "Premium" section scrolled off screen?

**Comment by magebarf** [comment]
Yes, that’s correct. Premium is just on top.

I did not see any change in the topmost section, but the offset for the text under start may align well with the size of the premium text height.

**Comment by keepassium** [comment]
Yep, in iPhone XR simulator this footer text briefly appears as in your screenshot and instantly jumps to the correct position. Probably has something to do with the custom table cell right above it :) 

I will look into this, thanks!

**Comment by magebarf** [comment]
Yes, this seems to be resolved, I can’t trigger the behavior in the latest version.
