### ISSUE TITLE
1.47 and 1.4.8 release sources

### ISSUE THREAD

**Issue by scribblemaniac** [keepassium/KeePassium#331]
**Description**
I've noticed that the code for versions 1.47 and 1.48 have not been published. While it's not unusual to see a few days delay between an update in the App Store and a release here on GitHub, it has now been over 3 weeks since the KeePassium 1.47 release. Can we please get access to the source or get an update on when it will be shared?

**Comment by keepassium** [comment]
Hey, I'm glad someone actually cares to see the code :) I will push it later this week, thank you for the nudge.

**Comment by keepassium** [comment]
Done!

**Comment by scribblemaniac** [comment]
Thanks!
