### ISSUE TITLE
Support custom wordlists in passphrase generator

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#335]
Passphrase generator should be able to use custom, user-provided wordlists. EFF lists are English-only, which makes them suboptimal in non-English speaking countries.

[Thanks, J.D.]

**Comment by ccooll** [comment]
Hello, I would like to add on this request.  Being a French speaker, having French word would make the passphrase more usable for me.

Here is an alternative wordlist that looks very interesting.  I found it on this repo : [diceware-wordlists-fr](https://github.com/mbelivo/diceware-wordlists-fr). 

- https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4d.txt
- https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4d_2.txt
- https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_4k.txt
- https://github.com/mbelivo/diceware-wordlists-fr/blob/master/wordlist_fr_5d.txt

Thank you for considering this request.
