### ISSUE TITLE
 Nitrokey3 support

### ISSUE THREAD

**Issue by ObiWahn** [keepassium/KeePassium#339]
Hi,

it would be great if you could support the Nitrokey3. It has already been implemented in keepassxc.
This is the related PR: https://github.com/keepassxreboot/keepassxc/pull/9631

**Comment by keepassium** [comment]
Thank you, @ObiWahn. This won't be priority in the nearest future, but let it sit on the queue to see how many people need this.

**Comment by keepassium** [comment]
Nitrokey just [confirmed](https://github.com/Nitrokey/nitrokey-3-firmware/issues/540#issuecomment-2399851979) that KeePassXC-style challenge-response is impossible via NFC. 

So that's a no for Nitrokey 3 support…
