### ISSUE TITLE
Add ability to launch keepassium from system tray icon

### ISSUE THREAD

**Issue by ezamelczyk** [keepassium/KeePassium#342]
It would be a really nice improvement if we could just expand keepassium from the system tray icon on macOS as it would eliminate the need to switch back and from fullscreen apps.

**Comment by keepassium** [comment]
I'm afraid this is an enhancement for such a far future that it would be more honestly described as "not planned" at the moment…

**Comment by ezamelczyk** [comment]
Really? I'm not an expert on Mac development but upon skimming through documentation this seems like a fairly simple task. I'd do it myself but I know you don't accept contributions.

**Comment by keepassium** [comment]
> this seems like a fairly simple task

Yes, it probably is. 

But there are dozens of other tasks in the "nice to have" queue. Which, in turn, follows the "must have" and "do it yesterday" queues (both with some rather massive tasks). Considering the team size, it would take _years_ before we reach this task in the queue. At this time scale, I think it is more appropriate to label it as not planned and revisit the issue in a few years, should there be demand.
