### ISSUE TITLE
Some storage providers are "blocked by your organization"

### ISSUE THREAD

**Issue by michaeluhl** [keepassium/KeePassium#346]
**Description**
I keep copies of my database in a `git` repository in order to sync it with computers on my local network.  I use the Working Copy app as a `git` client on iOS, and until now, I have been able to access my databases in KeePassium via storage made available by Working Copy.  As of Version 1.49 of KeePassium, I now get a message on the "Databases" screen that reads, "Access to this storage is disabled by your organization." 

**How to reproduce**
1. Create a .kdbx database
2. Add to a git repository
3. Clone repository in Working Copy
4. In iOS Files app, make sure that Working Copy is enabled under locations
5. On the KeePassium Databases screen, tap "+" and select Open Database
6. Browse to the storage provided by Working Copy and select the database from the appropriate repository
7. See error

**Expected behavior**
An error message should not be displayed.

**Screenshots**
![IMG_0272](https://github.com/keepassium/KeePassium/assets/2721001/59b137d7-9e68-44da-8f5a-1837ed4b433f)
![IMG_0273](https://github.com/keepassium/KeePassium/assets/2721001/6ebef882-23e1-42d5-8f40-2722af0bc436)

**Environment:**
 - Device: iPhone SE 3rd Gen (2022)
 - OS: iOS 17.3.1
 - App Version: 1.49.145
 - Subscription: Annual

**Comment by michaeluhl** [comment]
I suspect that this is related to the changes in f350ded, based on the message that I'm seeing.

**Comment by keepassium** [comment]
Thank you, @michaeluhl. 

Indeed, this is a bug in 1.49. Without any MDM involved, the app is supposed to allow all storage locations — but currently defines "all" as "[all known to the app](https://github.com/keepassium/KeePassium/blob/master/KeePassiumLib/KeePassiumLib/files/FileProvider.swift)". 
The update is coming up in a day or two, as soon as Apple approves it.

**Comment by keepassium** [comment]
The updated v1.50 is now in the App Store.
