### ISSUE TITLE
[iOS/Safari] Empty Username clears field rather than not typing anything

### ISSUE THREAD

**Issue by jcarius** [keepassium/KeePassium#347]
**Description**

There are situations in which I prefer to only store the password (or only the username) of an account in my database. Let’s say the username is left empty. Now when logging into a webpage in Safari, I type the username by hand, then select the password field and pull up KeePassium to autotype the password. What happens is that the empty username from the database clears my previously typed username. The password is autotyped as expected.

I would prefer if it did not clear the username, but instead does not type anything if the corresponding database field is empty/not stored in the database. 

**How to reproduce**
1. Create an entry with empty username and random password
2. Navigate the corresponding website login field with username and password
3. Type the username by hand.
4. Select the password field and perform keypass auto type
5. observe the username field being cleared.

**Expected behavior**
Do not auto-type empty fields.

**Environment:**
 - Device: iPhone 14 Pro
 - OS:  iOS17.3
 - App Version:  1.48.142

**Comment by keepassium** [comment]
> What happens is that the empty username from the database clears my previously typed username. The password is autotyped as expected.

I'm afraid this is managed by the system and KeePassium has no control of the actual field-filling process. The AutoFill module is required to return a username and a password (possibly empty), but the rest is done by the system.

You might want to submit this as an enhancement suggestion to Apple: https://www.apple.com/feedback/

**Comment by jcarius** [comment]
Oh, I see, thank you for the quick response and explanation, anyways!
