### ISSUE TITLE
No search with autofill

### ISSUE THREAD

**Issue by CrysK** [keepassium/KeePassium#348]
If you open the app (on iOS) and a kdbx file, the groups in the file are displayed nicely and you can easily navigate to the desired password.
However, if you press the "Password" button (above the keyboard) and no clearly matching password is found, then you get to an absolutely useless search function and unfortunately have no way of displaying the handy groups in the file.

If you press the "Password" button, you should also be able to switch to the group view!

**Comment by keepassium** [comment]
This is by design. The purpose of the app is to view, edit and rearrange groups and entries. In contrast, the AutoFill dialog has a much narrower purpose: find one entry. No viewing, no editing, no rearranging, no groups — just find one entry.

If you believe groups are necessary in AutoFill, I would appreciate a more detailed description of why this is important for you.

**Comment by CrysK** [comment]
An example: 
I have to open my page example.com via IP 192.168.178.2. The IP is not stored in the kdbx file. 
If I now open the page (on my mobile phone) and press the password button, KeePassium is opened and nothing is displayed! Because it finds nothing.
Now I have to manually open KeePassium twice and manually copy the username and password.

If I find more examples, I will update them.

**Comment by keepassium** [comment]
> If I now open the page (on my mobile phone) and press the password button, KeePassium is opened and nothing is displayed! Because it finds nothing.

Why not add the IP to the relevant entry? If this is not an option, why not find the entry by a few letters of its title?

**Comment by CrysK** [comment]
I have now looked again very carefully and I have never noticed the magnifying glass symbol on the right-hand side before. That solves the problem, of course 🙃

Thank you very much!

**Comment by keepassium** [comment]
You can also pull down the list slightly to reveal the search field. This is a standard iOS gesture, it works in many apps (Notes, Reminders, Messages, Mail, even Settings).
