### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by Stromos** [keepassium/KeePassium#35]
With iOS 13 around the corner it’s going to be that feature that will be asked a million times over in a few months!

**Comment by keepassium** [comment]
Oh yes it will be :) 

But I would have to wait for a stable release of Xcode 11 first. Don't really want to mess up the working setup on the only MacBook...

**Comment by keepassium** [comment]
Dark mode has just been added in v1.02.35. 

Eventual bugs in the color scheme are best reported to #56. Thanks!
