### ISSUE TITLE
Make NFC YubiKeys available in iOS AutoFill

### ISSUE THREAD

**Issue by LavermanJJ** [keepassium/KeePassium#355]
**Describe the feature you'd like**
After [make Lightning YubiKeys available in iOS AutoFill](https://github.com/keepassium/KeePassium/commit/02018cd119ff6d15f7bef50a9d556db2a158d6ae), it would be great to also add support for NFCS YubiKeys to be available in iOS Autofill.

Having the possibility to secure the database with a hardware key is great, however, missing out on the usability of  iOS Autofill reduces convenience. As there is always the conflict between convenience and security, adding this feature, would make the world yet a little more secure 😉

**Comment by keepassium** [comment]
Yeah, it might look like an incremental step, but unfortunately NFC in AutoFill is a whole different kind of beast. More precisely, one which is [explicitly blocked by Apple](https://developer.apple.com/documentation/corenfc):

> Core NFC isn’t available for use in app extensions

Until they lift this limitation (if ever), NFC in AutoFill just won't work…
