### ISSUE TITLE
Password Generator separator breaks ui

### ISSUE THREAD

**Issue by Ironwally** [keepassium/KeePassium#360]
**Description**
The Gui of the password generator is completely filled with a password and scrolling is no longer possible making it impossible to change the password generator settings anymore.

**How to reproduce**
1. Open App
2. Open Password Generator
3. Open Password Generator Settings
4. Go to Passphrase mode
5. Put amount of words on max
6. Set separator to something very VERY long. (long enough for the password to cover your entire screen), remember it is repeated the amount of words - 1
7. Voilà, your screen should now be filled with one big password and the setting to change this can no longer be reached.

**Expected behavior**
No matter how big password, screen is still scrollable and therefore settings to change it are still reachable.

**Screenshots**
![IMG_1903](https://github.com/keepassium/KeePassium/assets/62899274/3a7720d0-e6f6-4015-8f6d-4cd3a8729f2d)
![IMG_1904](https://github.com/keepassium/KeePassium/assets/62899274/e16ca491-faf6-48aa-96f4-2a70a150c1d9)

**Environment:**
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS17.3.1]
 - App Version: [e.g. 1.54.147]

**Comment by keepassium** [comment]
> Set separator to something very VERY long.

But why?

**Comment by Ironwally** [comment]
I wanted to see how far I could push the entropy

**Comment by Ironwally** [comment]
Maybe the possibility to reset the password generator settings from the app settings, could work as an easy fix agains any problems that come up with the password generator.

**Comment by keepassium** [comment]
Thank you for the clarification. As a general rule, "just avoid holding it in that way" :)

I have also limited the max height of the password label to 50%. This is more of a guardrail, though. The text gets truncated without any indication, which may cause confusion. Doing this properly would require either a scrollbar or a gradient, but this is too much complexity for such a rare edge case. Basically, the app will just leave enough of controls visible that the user can return to more sensible settings :)

**Comment by Ironwally** [comment]
thanks for the fix 🙏
