### ISSUE TITLE
Password does not hide correctly after locking iPhone

### ISSUE THREAD

**Issue by FlightMS** [keepassium/KeePassium#362]
**Description**
If you lock your phone, unlock again with opened Kepassium and visible password, you're able to still see the password when you swipe up to leave the app. It's also visible in the task manager. When you swipe up without locking the phone, the screen "blurred" correctly.

**How to reproduce**
1. Open Keepassium and show password
2. Lock phone and unlock again
3. Swipe up to close the app

**Expected behavior**
Screen gets blurred to keep all informations and passwords safe.

**Screenshots**
![IMG_3997](https://github.com/keepassium/KeePassium/assets/82420268/398d16d8-699b-482b-a096-8b967464eb76)

**Environment:**
 - Device: iPhone 15 Pro
 - OS: 16.4.1
 - App Version: 1.51.147

**Additional context**

**Comment by keepassium** [comment]
This can happen if you minimize the app within a second or two after the Face ID prompt. 
For now, this is in "known limitation" category: https://github.com/keepassium/KeePassium/issues/330
