### ISSUE TITLE
Option for keeping the window open during new entry

### ISSUE THREAD

**Issue by richarddribeiro** [keepassium/KeePassium#365]
Every time I need to make a new entry in the vault using the Firefox extension I have quite a hard time, as the window from Bitwarden extension is kept open as long as I keep it on the focus. If I click outside that window I lose everything I have typed until that moment. You can ask, why I would click outside that window, well... usually to grab some extra information that it is not captured automatically, like some info to include in the Note box.

The reason why I would like to keep it open until I click Save is because it will make easier for me (and maybe others) to input data in new entries (or editing old ones).

I would be glad if you consider the possibility.

Cheers!

**Comment by keepassium** [comment]
It looks like you posted to a wrong repo?

**Comment by richarddribeiro** [comment]
Sorry! My mistake. Feel free to delete this thread.
