### ISSUE TITLE
Cant fill in any password in Safari

### ISSUE THREAD

**Issue by Fischmuetze** [keepassium/KeePassium#374]
KeePassium is configured for password management
I can select KeePassium in a password field as password supplier
I can login in the KeePassium password db
I can select an Item 
but the password will not filled in in the password field of the website

**Expected behavior**
Put the password of the selected entry in the password field of the website

**Environment:**
macOS Sonoma 17.5, 
Safari 17.5 (19618.2.12.11.6)

**Comment by Fischmuetze** [comment]
this seems to be affected to single field forms like the Fritzbox Login page

**Comment by keepassium** [comment]
Unfortunately, this is a system issue. Closing as duplicate of https://github.com/keepassium/KeePassium/issues/259
