### ISSUE TITLE
Selectable path for backup files

### ISSUE THREAD

**Issue by Fischmuetze** [keepassium/KeePassium#375]
**Describe the feature you'd like**
Selectable path for backup files

And *why* you need it — that is, how it would make your life better.
I would like also to synchronise the backup files with my cloud and/or have the backup files to another drive

**Comment by keepassium** [comment]
Thank you for the suggestion, but this is not planned.

KeePassium is a password manager, it is not supposed to be a backup solution. The main purpose of in-app backups is to be a last-resort defense from data corrupting bugs (like https://github.com/keepassium/KeePassium/issues/130). For this reason, KeePassium creates a backup copy on _every_ save — and this is a lot of files. 

For a mobile app, syncing all this to a cloud would become a problem very quickly: 
- Mobile data connections are slow, especially outside of cities
- Battery life is small regardless of geography
- iOS really likes to interrupt long background operations

This means that uploading backups to a cloud would be slow, battery-draining and unreliable. The only benefit would be protection against _simultaneous_ data corruption and device loss, which is a rather unlikely event.

 So I would suggest to simply keep your database in a cloud, and make periodic offline backups using dedicated backup software. In case of device loss, your latest database remains in the cloud. In case your cloud database gets corrupted/missing, you have local backups in your backup software and in KeePassium. And device battery life remains good :)

**Comment by Fischmuetze** [comment]
Sorry, my post was a bit inaccurate as I didn't realise that the Github issue board is global for all platforms ... it was a specific request for the macOS version, as other password managers offer the possibility to configure the path of the backup files. Of course backup files protect against corrupt files, but they are at the same time like a version backup. Since the option to configure the backup path is also available in many other password managers, I thought it wouldn't be a big deal.

**Comment by keepassium** [comment]
Thanks for the details. Yes, I guessed the macOS context from your other ticket. 

The thing is, KeePassium is a mobile-first app, the desktop version pretty much only follows the mobile one. (Admittedly, this shows, and not in a good way.) I don't mind to fine-tune a thing or two for better desktop experience, but adding this kind of setting for one platform is not worth the additional maintenance. 

As a workaround, you can move the backup directory to the desired location and then replace the original with a [hard link](https://stackoverflow.com/questions/80875/what-is-the-unix-command-to-create-a-hardlink-to-a-directory-in-os-x) to the new location. The backup directory is `/Users/your_name/Library/Group Containers/group.com.keepassium/Backup`.
