### ISSUE TITLE
widgets?

### ISSUE THREAD

**Issue by Thunder33345** [keepassium/KeePassium#38]
I am not sure, i am thinking of for TOTP 1 click copy/view
maybe a account list: view/copy for a folder inside a db??
need more ideas to refine this suggestion

gist of it is to do something with widgets
practicality wise though: i see some problems like, how the db would probably be always locked thus, needing masterkey making it as good as just opening the app
account list might just be pointless as ios has built in password filling to begin with
TOTP might be less useless since one can argue they wanted to use that for another device like pc

anyone have any idea if a totp widget would be helpful?

**Comment by Thunder33345** [comment]
maybe related to https://github.com/keepassium/KeePassium/issues/8

**Comment by keepassium** [comment]
Thanks. I'm sorry, I struggle to parse your idea :) How is it different from #8?

**Comment by Thunder33345** [comment]
sorry for begin such verbose but i am going to do that to ensure we are on the same page here:
basically, when you pull down notification center, then swipe right, you can see widgets 
that's what i meant by widgets
as for differences, the widget would basically say only show TOTP and no more, think of it like a quick access you can use without opening the app

as for usefulness, that debate is up in the air
would appreciate if others chime in

**Comment by keepassium** [comment]
Ok, after 50 days it seems there is not much demand for widgets :) Personally, I also think TOTP widgets are too far from what KeePassium should be doing (at least in its current state).

I would propose to close this, if you don't mind?

**Comment by Thunder33345** [comment]
sure it's mostly a guess at what others might want
i'll close this until the situation in the future changes
