### ISSUE TITLE
Direct in-app / native support for SFTP

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#382]
**Describe the feature you'd like**
Native support for SFTP

And *why* you need it — that is, how it would make your life better.
Currently we use external apps to sync, but often the syncing app is turned off. User forgets to turn on the sync app. However they think that sync app is turned on. So I need to explain every time when sync does not happen that they need to re-connect.

It would be great if SFTP could be implemented natively in Keepassium. The user cannot forget to turn on the external sftp app this way.

**Comment by keepassium** [comment]
Thank you for the suggestion. Unfortunately, this won't be worked on in any time soon…

The current WebDAV/OneDrive/Dropbox/GoogleDrive integrations are basically a thin layer over HTTP, which is natively supported by the system with a stable and well-documented API. 

In contrast, SFTP is a whole different beast, without native system support and with serious complexity. So it will require an external library. And those are some dark waters: most SFTP libraries for iOS are 5-10 years old and abandoned, with age-related issues piling up without answers. There are some updated forks with newer pre-compiled binaries of `libssh2`, which is _not suspicious at all_. And in any case, there seem to be no active maintainers in any of them.

Considering the above, plus the fact that SFTP is a rather niche requirement, I can only suggest to use WebDAV over HTTPS wherever possible…
