### ISSUE TITLE
Filter for expired entries

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#383]
**Describe the feature you'd like**
It would help if you could filter expired entries.

And *why* you need it — that is, how it would make your life better.
In large databases with many entries it would help if there was a filter available for expired entries. When turning on this filter, you can see all expired entries.

**Comment by keepassium** [comment]
Thanks, will do.

**Comment by keepassium** [comment]
Added in 1.53.154 (now in beta) with `is:expired` search condition (de939932cf7c3b28f8877d283510245ed9f2d979). 

If you check for expired entries frequently, a [smart group](https://support.keepassium.com/docs/smart-groups/) will save you the typing :)

**Comment by latvia234** [comment]
Thank you for adding this.

> If you check for expired entries frequently, a [smart group](https://support.keepassium.com/docs/smart-groups/) will save you the typing :)

I'll absolutely try smart groups; thank you!
