### ISSUE TITLE
macOS: clicking the URL doesn't copy it to the clipboard

### ISSUE THREAD

**Issue by jpweytjens** [keepassium/KeePassium#384]
**Description**
Clicking the URL on the desktop MacOS version of KeePassium doesn't copy the URL to the clipboard. Once clicked, the "Copied" screen appears, but the URL isn't copied.

**How to reproduce**
1. Go to a password entry
2. Click on the URL

**Expected behavior**
I expect the URL to be in the clipboard, similarly to clicking the username or password.

**Environment:**
 - Device: MacBook M3 Pro
 - OS: MacOS Sonoma 14.5 (23F79)
 - App Version: v1.53.153 (dmg version downloaded from GitHub)

**Additional context**
The problem has existed for a few version of KeePassium. I vaguely remember a related issue, but couldn't find it.

**Comment by keepassium** [comment]
Fixed in 1.53.154 (now in beta) via 7012d301df4e37c1695598fd83fec3375a3146b8.
