### ISSUE TITLE
Separate email and username

### ISSUE THREAD

**Issue by Ironwally** [keepassium/KeePassium#388]
**What can be improved?**
Manz websites have separate username and emailaddress. Some websites want username, some want email.

**The solution you'd like**
Have a separate field for email and username.

**Alternatives you've considered**
Leave unchanged and use additional field for email/username

**Additional context**
none.

**Comment by keepassium** [comment]
Thank you, @Ironwally . I just don't quite see the difference between

>Have a separate field for email and username.

and 

> use additional field for email/username

Using an additional field means there would be separate fields, right?

**Comment by Ironwally** [comment]
True, sorry.What I mean is that you can't decide if autofill will use the email or username. It's a convenience thing. I got this feature from Dashlane, if you want to take a look. If you save the email in an additional field, then you can't use it for autofill right?Am 30.09.2024 um 11:14 schrieb KeePassium ***@***.***>:﻿
Thank you, @Ironwally . I just don't quite see the difference between

Have a separate field for email and username.

and

use additional field for email/username

Using an additional field means there would be separate fields, right?

**Comment by keepassium** [comment]
> If you save the email in an additional field, then you can't use it for autofill right?

Correct. This is likely to improve in the future — in KeePassium, but probably not KeePass/KeePassXC. So in the interest of interoperability, just consider the "Username" field as "login", be it actually a username or an email.

**Comment by Ironwally** [comment]
Ah, ok. That makes sense, yea. Oki.I suppose that closes this then.Am 01.10.2024 um 13:44 schrieb KeePassium ***@***.***>:﻿

If you save the email in an additional field, then you can't use it for autofill right?

Correct. This is likely to improve in the future — in KeePassium, but probably not KeePass/KeePassXC. So in the interest of interoperability, just consider the "Username" field as "login", be it actually a username or an email.
