### ISSUE TITLE
Folder reordering support

### ISSUE THREAD

**Issue by Thunder33345** [keepassium/KeePassium#39]
like for example keepassxc can do

**Comment by keepassium** [comment]
Got it, thanks.

**Comment by craigo-** [comment]
Glad to see this is on the roadmap, have just upvoted. Hoping that this extends to entries as well, not just folders 😄

**Comment by keepassium** [comment]
Implemented in 1.53 (now in beta) via f1ae47235fe9b648a3129b4f439f499199139f24.
