### ISSUE TITLE
macOS: unlock database > no hardware key > usb not available > learn more article

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#393]
**What can be improved?**
<img width="608" alt="afbeelding" src="https://github.com/user-attachments/assets/76656bab-1a22-4e3b-afde-1a1443a438a0">

First – thanks for creating the new knowledge base on https://support.keepassium.com/

Maybe because of the kb update, learn more redirects to https://support.keepassium.com/kb/yubikey/

I expected a short explanation why USB is not available. Instead it redirects to the main article without explanation.

**The solution you'd like**
After clicking on learn more, I would like to see a small explanation why USB is not available. And I would like to know how to install the native macOS app.

**Comment by keepassium** [comment]
Thanks for the feedback!

The "Learn more" button refers to the whole dialog, perhaps this is more evident in its longer/mobile version:

<img width="400" alt="hardware-key-picker01" src="https://github.com/user-attachments/assets/e913b43a-883b-4865-84c8-25a1853a6da0">

The premise is that most people opening this dialog don't know what YubiKey is, why they need it, how to start using it, etc. Hence the link goes to an intro page with links to in-depth KB articles.

> I expected a short explanation why USB is not available. 

That's the purpose of the two lines already on the screen… :) 

Following this issue, I have also added a paragraph about native and non-native app to http://support.keepassium.com/kb/yubikey-compatibility/
