### ISSUE TITLE
Please consider making Quick Autofill a free feature

### ISSUE THREAD

**Issue by mak448a** [keepassium/KeePassium#394]
**What can be improved?**
Quick Autofill is a free feature on StrongBox, so when I switched, I missed it a bit. I know KeePassium needs paid features to support development, so it's okay if you keep it paid.

**The solution you'd like**
Please consider making quick autofill a free feature. Like I said earlier, it's fine if you don't make it free. But please consider it.

**Alternatives you've considered**
Just using the free version.

**Additional context**
N/A

**Comment by keepassium** [comment]
The difference between [standard AutoFill](https://support.keepassium.com/kb/autofill-setup-ios/) (free) and [Quick AutoFill](https://support.keepassium.com/kb/autofill-quick/) (premium) is 1-2 screen taps — that is, max 1-2 seconds of time saving. 

Is this difference really that significant? Or it just sounded like AutoFill is paywalled completely?

**Comment by mak448a** [comment]
No, that's it. Should I close the issue?

**Comment by mak448a** [comment]
:+1:
