### ISSUE TITLE
Database on OneDrive breaks when updated

### ISSUE THREAD

**Issue by MVS** [keepassium/KeePassium#395]
**Description**
I have a KeePassXC database that I am sharing with my iPhone on OneDrive.  Whenever the database is updated on another device, KeePassium breaks and can no longer be updated unless you remove the database and add it again.

I saw #387 which has similar conditions, but I think it is a different issue (this is a personal drive and is not shared). Feel free to merge or close if you disagree.

**How to reproduce**
1. Create a KeePassXC database on another device with a master password and a key file
2. Store the kdbx file on OneDrive
3. On KeePassium, go to Open Database
4. Navigate to OneDrive and locate the kdbx file
5. Unlock it using the master password and key file
6. Update the database using KeePassXC on the other device and save it. Make sure OneDrive syncs the changes.
7. Sync OneDrive on the iPhone using either the Files app or the OneDrive app
8. Open KeePassium and refresh the databases
9. An error message is shown: `Couldn't communicate with a helper application.` The error message never goes away, so you can continue using an old copy of the database, but there is no way to update it without removing it entirely.

**Expected behavior**
The database should refresh and show the updated data.

**Screenshots**
<img width="375" alt="IMG_921C6E0F15A2-1" src="https://github.com/user-attachments/assets/a8289bda-f362-4921-8d41-33ce9c943d1f">

**Environment:**
 - Device: iPhone SE 2022
 - OS: iOS 17.7
 - App Version: 1.53.154

**Comment by keepassium** [comment]
Hmm, this is an interesting case… 

> Couldn't communicate with a helper application

This is a well-known iOS issue that has nothing to do with KeePassium. It has a dedicated troubleshooting article: [If KeePassium couldn’t communicate with a helper application](https://support.keepassium.com/kb/helper-application-unresponsive/)

The interesting part is that the issue occurs after editing the database with KeePassXC. This is a typical symptom of another issue, which usually ends up showing "[File doesn't exist](https://support.keepassium.com/kb/database-does-not-exist/#repeating)". I wonder if OneDrive handles the surprise differently and ends up unresponsive instead…

Out of curiosity, try changing KeePassXC settings as described over the second link, and try to reproduce the issue. If it works out without errors, I would be happy to add the solution to OneDrive's troubleshooting page.

Should the issue repeat anyway, the only reliable solution is to switch to [direct OneDrive connection](https://support.keepassium.com/kb/sync-onedrive/#direct).

**Comment by MVS** [comment]
Yes, that solved it. I made the changes in the second link, and everything is working perfectly now. Thank you!
