### ISSUE TITLE
Add support for ProtonDrive

### ISSUE THREAD

**Issue by daniE43** [keepassium/KeePassium#402]
ProtonDrive is the cloud storage solution by Proton. In a try to get rid of some Google in my life, I found their storage solution quite nice and usable. 

I can already select the Proton Files as a database source, however I keep having issues with synchronization. It would be nice to have support for ProtonDrive & therefor another alternative for storing and sharing your database file.

**Comment by keepassium** [comment]
KeePassium uses a standard API to work with all storage providers via system integration. So from our side, Proton Drive was supported from day one. 

Now, _the reliability_ of Proton Drive's sync on iOS is a whole different question. iOS does make it challenging, but in either case, it is PD's responsibility; we cannot fix PD on KeePassium's side. One option could be connecting to Proton Drive directly from KeePassium, as we do with some other clouds. But Proton Drive does not offer a public API, so this is not possible, either.

All in all, this is a good issue for Proton to address.
