### ISSUE TITLE
[feat. req] Change folder of entry

### ISSUE THREAD

**Issue by jpweytjens** [keepassium/KeePassium#410]
**Describe the feature you'd like**
I would like the ability to change the folder (group) of an existing entry, via either the `Edit` interface or via dragging and dropping into the new desired folder.

**Why**
Nearly every website and tools requires a log in these days. To organize this growing list of passwords, it's nice to have some folders and the ability to move entries from one to the other.

Related request: https://github.com/keepassium/KeePassium/issues/400

**Comment by keepassium** [comment]
One can already right-click (or long-tap) the entry and select Move from the menu. Is this what you mean?

**Comment by jpweytjens** [comment]
I wasn't aware of this, my apologies. That's exactly what I was looking for.
