### ISSUE TITLE
Feature Request: Enhanced URI Handling with Multi-Line Display and Clickable Links 

### ISSUE THREAD

**Issue by bb955** [keepassium/KeePassium#411]
Hello KeePassium developers,

I am a user of KeePassium and I appreciate your work in creating this great password management application. However, I have encountered an issue with how the app handles URI links, which impacts user experience.

Currently, KeePassium merges all URI links in a single entry into one field, making them indistinguishable. This prevents users from directly clicking on links to access the corresponding web pages. Users are required to manually copy and paste these links, which is inconvenient, especially when there are multiple links.

I would like to suggest a way to enhance the URI field, making it more convenient to use:

    Support Multi-Line Display of URIs: Each URI link should be displayed on a separate line for easy viewing and distinction.

    Enable Clickable Links: Users should be able to directly click on the links to navigate to the corresponding web pages, without needing to manually copy and paste.

I believe such improvements would greatly enhance KeePassium's usability, especially for users who manage multiple web accounts. This would lead to increased productivity and decreased manual operation.

Here are some ideas on how this could be implemented:

    Adopt a UI Similar to Other Applications: Display each link on a separate line with a clickable functionality.

 

    Add a Specific URI Field Type: Create a dedicated “URI” type field, which the system can recognize and display as clickable links.

I look forward to seeing these improvements in KeePassium's future updates. Thank you for your hard work and dedication!

**Comment by keepassium** [comment]
> Currently, KeePassium merges all URI links in a single entry into one field, making them indistinguishable. 

According to [screenshots on Reddit](https://www.reddit.com/r/KeePassium/comments/1hn8wss/uri_identification_problem/), your `URL` field contains several URLs merged into a single comma-separated string. I can only assume this happened when you converted your data from another password manager. KeePassium does not do such things, because this is not how it is supposed to work.

In a KeePass database, the `URL` field is intended for one URL only. If you need several URLs in the entry, you would need to create a separate field for each. Field names are not important: as long as field value contains a valid URL with a common scheme (`https`, `http` and a couple more) — it will be recognized and handled as a URL. And then they are shown on separate lines, and can be easily clicked and copied.

**Comment by bb955** [comment]
> > Currently, KeePassium merges all URI links in a single entry into one field, making them indistinguishable.
> 
> According to [screenshots on Reddit](https://www.reddit.com/r/KeePassium/comments/1hn8wss/uri_identification_problem/), your `URL` field contains several URLs merged into a single comma-separated string. I can only assume this happened when you converted your data from another password manager. KeePassium does not do such things, because this is not how it is supposed to work.
> 
> In a KeePass database, the `URL` field is intended for one URL only. If you need several URLs in the entry, you would need to create a separate field for each. Field names are not important: as long as field value contains a valid URL with a common scheme (`https`, `http` and a couple more) — it will be recognized and handled as a URL. And then they are shown on separate lines, and can be easily clicked and copied.

Hello, thank you for your reply.

I understand what you said about my issue possibly stemming from previous data imports, where URLs in some entries might have been merged into a single field. I also understand KeePass's design principle of one URL per field.

My previous post might not have been clear enough. My real need is not about "merging URLs," but rather about having a more convenient way to display and click multiple URLs within an entry in KeePassium. For example, I now need to create a separate custom field for each URL, which does allow independent clicks, but when an entry needs to manage many URLs, it feels a bit inconvenient because I can only see all the URLs in edit mode, and clicking them is not very efficient.

Could you please tell me if there are any other more convenient ways to handle multiple URLs in KeePassium, besides creating a separate field for each URL? Or, have you considered providing a more user-friendly way to display and click URLs in future versions? I understand that you might think the current way is sufficient, but I believe that a good user experience can greatly enhance KeePassium's practicality and appeal.

Additionally, regarding the "separate field feature" you mentioned, I still have some questions that I hope you can clarify:

1.  **What is the "standard" for adding multiple URLs that KeePassium recommends?** If each URL needs to be placed in a separate custom field, how can I conveniently view and click all the URLs of an entry in actual usage? Are there any related examples or recommended best practices?

2.  **Does KeePassium support various short, custom URL schemes?** For example, can KeePassium correctly recognize and support clicking URLs like `androidapp://com.sina.mail.free`, which is a short URL that doesn't start with HTTP/HTTPS? I would like to confirm KeePassium’s support for such URL schemes in order to better assess its suitability.

Thank you again for your work and reply! I look forward to your further response.

**Comment by keepassium** [comment]
> What is the "standard" for adding multiple URLs that KeePassium recommends? 

Please refer to the second paragraph of my previous response.

> For example, I now need to create a separate custom field for each URL, which does allow independent clicks, but when an entry needs to manage many URLs, it feels a bit inconvenient because I can only see all the URLs in edit mode, and clicking them is not very efficient.

I think it is worth noting that KeePassium is a password manager, not a bookmark manager. If you need to add many different URLs to one entry, you are probably "[holding it wrong](https://www.theguardian.com/technology/blog/2010/jun/25/iphone-reception-problems-solved)". Every web service should have a separate account, with its own password, stored in a separate entry — and pretty much a single URL.

If you do absolutely need to use the same account on different web services, create a separate entry for each webservice and link the username/password to some "main" entry using [field references](https://support.keepassium.com/docs/field-references/).

> Does KeePassium support various short, custom URL schemes?

No. All iOS apps must [declare](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/plist/info/LSApplicationQueriesSchemes) the URL schemes they plan to use and eventually open. If an app tries to open a URL with an undeclared scheme, the system will ignore the call. 

So KeePassium recognizes and displays as URLs only those, for which the system confirms it will open them. So far these are: `https`, `http`, `ftp`, `mailto`, `itms-apps`. We can add a few other common schemes, if necessary, but nothing custom.
