### ISSUE TITLE
Search bar not showing on iOS 13 beta

### ISSUE THREAD

**Issue by shad0whawk** [keepassium/KeePassium#46]
The search bar doesn’t display when I first open a database even with “Start with Search” enabled. I try pulling down in the screen and that has no impact. If I go into a folder or open the preferences window and then go back to the previous screen, it will show up. If I drill down one folder level, it exhibits the same behavior with no search bar until I drill down one more level and then go back up one.

**Comment by keepassium** [comment]
Thank you! It is worth mentioning this happens only on iOS 13 beta.

I am planning to wait until iOS 13 reaches the release candidate phase, to see if this is a transient system bug or a new reality the apps have to adapt to.

**Comment by shad0whawk** [comment]
Fair enough.  I should have checked it on iOS 12 to confirm but it didn’t cross my mind.

Marc Burris
303.809.8149
marc.burris@gmail.com

________________________________

**Comment by keepassium** [comment]
Reported to still happen on public beta 6. It seems, this will need some fixing on my side...

**Comment by martin-bussieres** [comment]
Also testing with iOS 13, The search bar doesn't appear at first load of DB but if you navigate to settings "cog icon" and come back and pull down then the search box will be available

**Comment by keepassium** [comment]
The issue remains in iOS 13 GM. I'm working on it.
