### ISSUE TITLE
Feature Request:  AutoFill should search for URLs in custom fields

### ISSUE THREAD

**Issue by Dragonblitz10** [keepassium/KeePassium#47]
**Describe a feature you'd like**
- the ability to add multiple urls to an entry (some websites have multiple login places)
- the ability to move or clone an entry

**Additional context**
most websites either have multiple login pages or Keepassium does not recognise the login page but does recognise other pages

it would be useful to clone an entry if you have multiple logins on a service or you need to move them into folders

**Comment by keepassium** [comment]
> the ability to add multiple urls to an entry (some websites have multiple login places)

You can already add custom fields with URLs, and they will be properly shown as URLs. AutoFill already searches in custom fields for possible domain name matches. I will make sure to search for the full URL, too. Thanks!

> the ability to move or clone an entry

I have moved this to #48. Please try to keep separate requests in separate issues, it makes them much easier to track. Thanks!
