### ISSUE TITLE
Copy/move entries to other groups

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#48]
It should be possible to move or copy an entry to another group.

(Initially requested by @Dragonblitz10 in #47.)

**Comment by igorkulman** [comment]
Any chance of this will get implemented?

**Comment by keepassium** [comment]
Yes! Currently, this is the third [most requested feature](https://github.com/keepassium/KeePassium/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). 

At the moment I am busy working on the first two (hardware keys and TOTP setup). Once done, I'll get to this one — probably in January, given the upcoming holiday season.

**Comment by igorkulman** [comment]
Speaking about features, can I make a PR with some code? Because I noticed this repo is a bit "strange" with no PR and a bit of "hidden" development.

**Comment by keepassium** [comment]
Thank you for the offer, Igor. Unfortunately, I cannot accept code contributions. 
Due to the [conflict between GPL and App Store terms](https://www.fsf.org/news/2010-05-app-store-compliance), Apple does not allow GPL-licensed apps on the App Store. So, I have to grant them a special license to distribute the app. And this is possible only as long as I have full copyright on the app. To accept contributions, I would have to ask you to sign copyright transfer forms, which is no fun for anyone involved and would quickly kill the mood anyway...

Regarding the non-public development, you are right. Finding the right balance between transparency and commercial viability is not easy, and that's what I ended up with. For the sake of transparency, the project is open: anyone can audit the code and compile it. For the sake of commercial viability, commits are squashed and comments are stripped — this is intended to deter unfriendly forks, yet maintain the transparency. There are more details in #26.

**Comment by craigo-** [comment]
> It should be possible to move or copy an entry to another group.

This has my upvote. Hoping that this will also provide the ability to simply duplicate an entry (as is provided in KeePass and StrongBox) - perhaps by copying to the same/existing group.

**Comment by keepassium** [comment]
This is coming soon, in the next beta.

**Comment by keepassium** [comment]
Hmm, it seems I forgot to mention this in the commit message. The feature has just been released in 1.09.49.

**Comment by TBugReporter** [comment]
I can't find this.  Did you make it a premium feature?  Is it in the iOS version?

**Comment by keepassium** [comment]
@TBugReporter , long-press the entry → Move.
