### ISSUE TITLE
Ability to move databases/key files to app private directory

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#49]
**Describe a feature you'd like**
Currently, local databases and all key files can be accessed from the Files app. It would be useful to add an option to make them accessible only from the app. (For example, move to a private directory in the app sandbox.)

Would this be useful?

[Thanks, T.]

**Comment by TechGuy2000** [comment]
Yes, absolutely! I consider this an essential feature (along with the ability to lock access to the app with a PIN and/or Touch ID/Face ID.

**Comment by keepassium** [comment]
Five years later, v1.53.154 makes it possible to mark files as hidden (via 257177c0506c4978c8f452654a79aa8362643a50). This is pure security-through-obscurity feature, but it does hide files from curious eyes and iOS Files app. Private directory is no longer planned, because it would not protect from attackers knowing device PIN anyway.

The real security is still in encryption and a strong master key.
