### ISSUE TITLE
DateFormatter locale should be set

### ISSUE THREAD

**Issue by marpies** [keepassium/KeePassium#5]
When parsing the [ISO 8601](https://github.com/keepassium/KeePassium/blob/master/KeePassiumLib/KeePassiumLib/db/util/Date%2Bextension.swift#L16) date, the formatter locale should be set as described in [Technical Q&A QA1480](https://developer.apple.com/library/archive/qa/qa1480/_index.html).

Without the locale set, the date conversion may fail for users in some regions.

```swift
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
```

**Comment by keepassium** [comment]
Good point, thanks!
