### ISSUE TITLE
Feature request: Add QuickType AutoFill support 

### ISSUE THREAD

**Issue by raymond127** [keepassium/KeePassium#50]
First of all KeePassium looks great, I appreciate your work!

Perhaps you could refine the workflow of the Autofill in Safari.
Currently you have to press the “password” Button, enter the Keychain or use Touch/Face-ID, tap the button of the suggested account and press Login.

Most Password-Manager show Accountdetails like the URL and the username for the Website instead of the “Password” Button. In addition to that you only need to tap this button, use Touch-ID/ Face-ID (if enabled) and for Websites with mobile view it automatically locks in.
For this process the Apple Keychain only saves the Information about the URL respectively the username, not the password.

This would simplify the log in and save some time for people who log in very often.

**Comment by keepassium** [comment]
Thanks!

Yep, this is on my list and will be done.

**Comment by tunger** [comment]
Would love to see this feature as well!

**Comment by ospring** [comment]
I am interested in this ehancement too

**Comment by keepassium** [comment]
It's been a (long) while, but QuickType AutoFill is now available in [beta](https://keepassium.com/beta)!
