### ISSUE TITLE
Files not synchronizing

### ISSUE THREAD

**Issue by NKYAggie** [keepassium/KeePassium#53]
I use my KeePass database across 3 devices:
- iPhone running iOS 13 Beta and using KeePassium beta
- MacBook running MacOS beta and using KeePassXC
- Windows 10 laptop running KeePassXC

I store my database in iCloud so it syncs across all 3 devices. Previously, if I changed or added an entry on any device, the changes all synchronized correctly. Now, if I make a change on either laptop, KeePassium does not pick up the changes. Instead, it holds on to the old file which is renamed with a number. (Keepass 1, Keepass 2, etc.)

If I make a change or add an entry in KeePassium, that change is synchronized correctly to my other 2 devices.

My guess is that this is related to the earlier permissions issue with iOS 13 where we couldn't open the databases at all. It would seem the file provider changes in iOS 13 are interfering with the ability to synchronize the database files, or with Keepassium just being able to detect the "file changed" event and loading the new file instead of a clone being created.

**Comment by keepassium** [comment]
This sounds like something that might be caused by the "Safely save database files" setting in KeePassXC (Settings - General - File Management). Does the issue remain if you toggle that option?

**Comment by NKYAggie** [comment]
Nice callout. I completely forgot about that option.

I disabled it on both my MacBook and my Windows PC. I was able to make edits in both, and they were reflected in KeePassium without cloning the file.

Thanks!!

-- 
Matt

**Comment by keepassium** [comment]
I'm happy it worked. Thanks for confirming!

**Comment by quinncomendant** [comment]
I noticed this issue today also. I'll add some more info in case it helps people find this issue.

When the KeePassXC option, *“Safely save database files (may be incompatible with Dropbox, etc)”* option is enabled, KeePassXC does an "atomic save": it moves the old database file aside, and creates a new database file with the original name. It appears you are using the same DB file, but by recreating it after every save, cloud-sharing systems get confused, and the old DB file appears missing.

If I use iCloud with the *“Safely save database files”* enabled, I get this error in KeePassium, “The file doesn't exist”:

![IMG_1782](https://user-images.githubusercontent.com/6884276/70580641-1fb2e800-1b7a-11ea-8ec0-aa63d61387c3.PNG)

When I go to the list of databases, there is a "ghost" file named `?`, and the error, “The file doesn't exist”:

![IMG_1783](https://user-images.githubusercontent.com/6884276/70580686-483ae200-1b7a-11ea-8b74-4e9b3d16c4d0.PNG)

The solution is to disable *“Safely save database files”* when using iCloud (or other cloud file sync services, presumably).

**Comment by subnoodle** [comment]
Dear keepassium, i've got the very same situation with MacBook (KeepassXC), iPhone 12 and KeePassium 2.7.9, synced by shared folder in my Synology: 

- I change an entry in KeePassXC: The change is not reflected
- I change an entry in Keepassium: The change causes KeepassXC to be reloaded and displayed.

I fiddled arround quite often with KeePassium, completely removing the database from the app, then closing the app, reopening the app and then the database file again. It did not help.

Then i discovered this entry and tried to find this option in the german ui.

It it this? 
![KeePasium](https://github.com/user-attachments/assets/96c22284-3000-42dd-9ac1-53ecd375708e)
I cannot really find this option in the german language ui, and maybe another version.
I quote sure it's it, but the 2nd option should be "direct" or "via temporary file"? (direct did not work until now)

Thank you, Thomas

**Comment by keepassium** [comment]
Hello Thomas, yes, those are the options. For future reference, here is the guide: https://support.keepassium.com/kb/database-does-not-exist/

And since you use Synology, [connecting via WebDAV](https://support.keepassium.com/kb/sync-synology/#direct) would be more reliable. (It also solves the "File doesn't exist" problem, as a side effect.)
