### ISSUE TITLE
custom field titles can overwrite default values without warning

### ISSUE THREAD

**Issue by mstarke** [keepassium/KeePassium#54]
**Describe the bug**
Missing checks for using default values as user values resulting in potential data loss.

**To Reproduce**
1. Click on an entry
2. Click Edit
3. Click Add Field (+)
4. Set the field name to a default key (e.g. UserName, Password, Notes, Title…)
5. Set a value
6. Close the database
7. Open the database
8. Entry now has the newly created field as the default value and is missing the previous value

**Expected behavior**
A warning that the chosen key is not allowed in line with the warning when a already used custom key is in use.

**User Information (please complete the following information):**
 - Device:  iPhoneSE
 - OS: 12.4.
 - App Version: 1.01.32

**Comment by keepassium** [comment]
Yeah, I check for duplicate custom fields, but completely missed the fixed ones...

Thanks, Michael! (Also for MacPass :)

**Comment by mstarke** [comment]
Tell me about those "D'oh" moments. There were and still are a lot happening to me as well. And thank **you** for adding another client to the KeePass universe. I feel like the format is on the rise again.
