### ISSUE TITLE
Delete items from entry history

### ISSUE THREAD

**Issue by A13BioniciOS6** [keepassium/KeePassium#58]
Hello I have more than 5 history on some entries.

But I don't want to have them anymore and delete them. Unfortunately I found no function in KeePassium (1.01).

**Comment by keepassium** [comment]
Thanks, will do.

**Comment by keepassium** [comment]
Was done in v1.25.89 (via 7bfd1d1978f9197b2f69424fc9076042721472d6) but mislabeled as #56.
