### ISSUE TITLE
Add an option to delete backup files without confirmation

### ISSUE THREAD

**Issue by A13BioniciOS6** [keepassium/KeePassium#59]
Hello,

I have activated the automatic backup function. Which is very good. But I have too many backups over 100.

I don't want to delete all of them and keep only the last 10. Unfortunately you can't select multiple times to delete them.

Can you add "select multiple"?

**Comment by keepassium** [comment]
Mmm, I think I'm missing the point of multiple selection...

If you could select `1 day`, `1 week` and `1 month`, the app would be deleting backups older than either of these three values. But `1 day` already implicitly includes the other two criteria, so what's the benefit of selecting `1 week` and `1 month`?

**Comment by A13BioniciOS6** [comment]
I always use "forever" as time.

Because sometimes there are moments where I make more than 30 small changes in 30 minutes or 2 hours = more than 30 backups.

and would rather decide manually which backups I want to delete in the last hours.

if i now deleted it every hour (automatically). then all of them would be gone.

**Comment by A13BioniciOS6** [comment]
i have been abroad for several months and forgot to take my iOS device with me. or if it should happen that i have a sudden accident and should sleep in a coma for 10 years in the hospital. :D:D

result:

i like to write down very small things (so small notes).

i would come back home and have over 100 backups at KeePassium. But where I don't have a memory anymore, which can be deleted now.

i just look through every backup and if there is nothing special i delete it. step by step. and then continue tomorrow with the next ones. if the automatic function would have been active all backups would have been deleted.

so i like the manual function. with multiple select would help me even more.

**Comment by A13BioniciOS6** [comment]
> I am a bit reluctant to switch the database list into a mass-editing mode, as that would complicate the UI for 99% of users who don't need this. How about an option to delete backup files without confirmation? So you would just swipe left the backup file and it is gone?

That's a good idea. No confirmation and would still be significantly faster than now.

You can add an option. I could imagine users who have very few backup files. Could accidentally delete it or are not so familiar with iOS system because they are new user.

**Comment by keepassium** [comment]
Closing as part of housekeeping. There were no other requests about selective backup deletion since 2019, so I think it is safe to close as not planned.
