### ISSUE TITLE
Localization issue in Xcode 11 GM

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#60]
**Describe the bug**
Localization seems to be broken in Xcode 11 GM. 

When the project is compiled and run from Xcode 10.2, everything is translated correctly. When exactly the same project is built and run from Xcode 11 GM, some translated strings show up in English.

**To Reproduce**
1. Checkout v 1.02.34
2. Build in Xcode 11 GM
3. Run either on device or in simulator, either iOS 12.2 or 13.0 GM
4. Open app settings

**Screenshots**

Built in Xcode 10.2, everything is translated:
![Simulator Screen Shot - iPhone SE - 2019-09-16 at 14 04 21](https://user-images.githubusercontent.com/38399598/64957914-453b9880-d88e-11e9-8d0a-aef1d128714a.png)

Built in Xcode 11 GM: "Premium Version", "AutoFill Passwords", "App Protection" and some other strings appear in English:
![Simulator Screen Shot - iPhone SE - 2019-09-16 at 13 21 35](https://user-images.githubusercontent.com/38399598/64957963-5d131c80-d88e-11e9-931b-9198a7462a27.png)

**User Information (please complete the following information):**
 - Device: iPhone SE + iPhone SE simulator
 - OS: iOS 12.2 / 13 GM
 - App Version: 1.02.34

**Additional context**

A similar issue was reported on StackOverflow: [Xcode 11/iOS 13 Localization issue](https://stackoverflow.com/questions/57905965/xcode-11-ios-13-localization-issue)

This seems to affect only `UITableViewCell` with standard styles. Custom cells, other views and NSLocalizedString in code all seem to work fine.

This is blocking the iOS 13 update, so I could use some help solving this...

**Comment by A13BioniciOS6** [comment]
A user just wrote, maybe this will help you?
https://stackoverflow.com/a/57959312

**Comment by keepassium** [comment]
I ended up subclassing problematic labels and translating them in the code. Hopefully, this workaround won't have to stay long.

**Comment by keepassium** [comment]
The workaround [breaks](https://github.com/keepassium/KeePassium/issues/56#issuecomment-532414390) English UI 🤦‍♂️

**Comment by keepassium** [comment]
This was an Xcode bug, fixed in [Xcode 11.1 GM seed 1](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_1_release_notes):

> UITableViewCell labels in storyboards and XIB files do not use localized string values from the strings file at runtime. (52839404)
