### ISSUE TITLE
Add Support for MagentaCloud App

### ISSUE THREAD

**Issue by makaanneo** [keepassium/KeePassium#62]
**Describe a feature you'd like**
Support for https://apps.apple.com/de/app/magentacloud/id312838242 as file provider.

**Additional context**
It would be nice if it is possible to select as well data from the magenta cloud app for key databases.

**Comment by keepassium** [comment]
Hi, thanks for the feedback! KeePassium should already work with any file provider that is properly registered with the system. 

As far as I can see in MagentaCloud description, they already integrate with the iOS Files app. (Although the user reviews state the integration could be done better.) So, theoretically MagentaCloud should already work. Can you describe what does not work?

(Normally I would just install and check it myself, but apparently it's not available for Luxembourg.)

**Comment by keepassium** [comment]
Ok, it seems we're good here...
