### ISSUE TITLE
iOS (13) upgrade drops existing file permissions

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#63]
**Describe the bug**
After going through the upgrade to iOS 13, existing file permissions seems to have been revoked.

**To Reproduce - will be a nightmare to attempt multiple times**
1. Have existing iOS 12 setup with KeePassium, kdbx files (stored in remote syncing service, outside App Sandbox) and possibly key files (stored inside App's sandbox)
2. Upgrade to iOS 13
3. Launch KeePassium (I did the first launch to the Autofill extension, may have affected things - especially access to the key file inside the app's sandbox)
4. The files previously accessible by existing permissions are now flagged red with warnings about missing permissions

**Expected behavior**
This may be the intended behavior from Apple, to revoke permissions and make users re-enable them after each major iOS upgrade, to be able to adjust privacy and integrity settings and how they're applied. If so, I guess the best way would be to see if a the major iOS version has increased since last time app was opened, and give a heads up that this may affect file permissions?

If this is not supposed to happen, and permissions should survive an upgrade, I guess it is an actual bug.

**Screenshots**
![IMG_0724](https://user-images.githubusercontent.com/3879511/65286424-d5eccf80-db3f-11e9-8d4d-efdc74445eb3.PNG)
![IMG_0723](https://user-images.githubusercontent.com/3879511/65286425-d5eccf80-db3f-11e9-8437-68d331a04c6d.PNG)

**User Information (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.4.1 -> 13.0
 - App Version: 1.02 (36)

**Comment by magebarf** [comment]
Probably can be closed as duplicate of #22

**Comment by keepassium** [comment]
Yeah, they've changed something in the permissions system. In the simulator, I cannot open any files at all. 

But this might as well be my bug. Today I [learned](https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories#overview) that one should call `startAccessingSecurityScopedResource` before bookmarking the URL. It used to work just fine without, but the new OS might be more thorough in its checks...

Just to better understand the scale of the problem:

- Were local key files also affected?
- If you re-add the files, do they work or still show the permission error?

**Comment by magebarf** [comment]
Local files were affected in the Autofill context, but seemed to work fine in the standalone app.

After re-add, everything works nicely.

If adding the same file you've lost permission to before removing the existing bookmark you actually get an up dated bookmark with the filename now showing (before it was only a blank), but trying to open the old bookmark will still give you permission errors. Opening the new bookmark while the old non-working one was still left in place also seemed to work okay.

**Comment by keepassium** [comment]
Thanks, Patrik!

Ok, so the local files are not affected, and the external ones work after re-adding. That’s different from #22, because there re-adding did not help. 

I will try to get some time for several jumps between 12.4 and 13.0, to see if this issue is caused by the missing `startAccessingSecurityScopedResource` I mentioned before. Mostly for learning — the existing users will probably still have to re-add the files...

**Comment by keepassium** [comment]
Nope, even if I call `startAccessingSecurityScopedResource` before bookmarking the file, there is still a permission error after upgrading 12.4 to 13.0. 

Having no better idea, I will probably add a suggestion to re-add affected files. However, that will be only in the next version...

**Comment by magebarf** [comment]
As long as everyone is seeing the same behavior as me, that re-adding things solves the issue, I wouldn't be too worried. It could probably be helpful with a nudge in the right direction, and possibly a "shortcut" to wipe clean and start over in case all of your bookmarked files suddenly end up with permissions issues, but I think it'll probably be until next major iOS version till we see something similar again.

**Comment by keepassium** [comment]
Just to add detailed resolution steps, in case somebody needs them:

- Open the list of databases: Press `< Databases` (or `< Back`) 
- Remove the affected database: Swipe left on the file, then press `Remove`
- Re-add the database again: Press the `+` button, `Open Database`, then select your database file
- If you use key files in AutoFill, repeat the same procedure for them.

After that, everything should work again.

**Comment by keepassium** [comment]
The issue can be reproduced by going to device settings — `Privacy` — `Files and Folders`, and turning off KeePassium's switch. After that, all previously added external files/databases in KeePassium return a permission error.

Interestingly, adding any new database to the app turns on the switch in the settings again, but does not return the previously reset permissions. 

I guess the introduction of this "Files and Folders" app permission was the main cause of this issue...

**Comment by jpweytjens** [comment]
I had the same issue after upgrading from iOS 12.4 to 13.1.3 on my iPhone XR. with Keepassium 1.06. Deleting the database and readding it via iTunes hasn't worked for me.

Is there any other information I can provide about the issue?

**Comment by keepassium** [comment]
@jpweytjens, after copying the database via iTunes, did you have the permission issue only in AutoFill or also in the main app?

**Comment by jpweytjens** [comment]
Just like above, the app itself works perfectly, only the AutoFill suffers from the "file couldn't be opened" issue.

**Comment by keepassium** [comment]
Yep, for the app itself the database is inside the sandbox, so the app has full access to it. However, the AutoFill is a separate process with its own sandbox, so it needs a permission to access files inside the main app. (That's why you have to add databases to AutoFill separately, when you install the app.)

The solution is the same as [above](https://github.com/keepassium/KeePassium/issues/63#issuecomment-542999847):

- Open AutoFill
- Press `< Back` or `< Databases` to get to the list of databases.
- Remove the affected databases (swipe left on the file)
- Press `+`, navigate to "On My iPhone / KeePassium" and add the database again
- If you use key files, you'll need to re-add them to AutoFill, too.

This way, you give AutoFill a permission to access the database inside the main app's sandbox. I'm not sure whether this permission will remain valid once you replace the file via iTunes, though...

**Comment by jpweytjens** [comment]
I didn't know that the database had to be added seperately in the AutoFill popup from Keepassium. Everything is working perfectly again, thanks.

**Comment by keepassium** [comment]
Yeah, this split personality of the app is very confusing (KeePassium is an app, but there is a main app component and the AutoFill component, they look and behave almost the same, but run as separate apps with independent permissions). I wish I could integrate them more seamlessly.

Anyway, I'm happy everything works fine now :)
