### ISSUE TITLE
Inconsistent font size on iOS 13.1 beta

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#65]
**Describe the bug**

Font size varies in the settings (and likely other tables) on devices running beta iOS 13.1. On iOS 13.0, everything seems fine.

**Screenshots**

Text labels near switches is smaller than others.

![](https://user-images.githubusercontent.com/6074105/65087048-67f2ad80-d971-11e9-8fea-0203fa79017e.png)

![](https://user-images.githubusercontent.com/6074105/65087049-688b4400-d971-11e9-92ac-bd2140879c47.png)

**User Information (please complete the following information):**
 - Device: iPhone 8 and XSMax.
 - OS: iOS 13.1 beta 3
 - App Version: 1.02.36

**Additional context**
This is likely a transient iOS beta bug, but it's good to keep track of it anyway.

Initially [reported](https://github.com/keepassium/KeePassium/issues/56#issuecomment-532441995) as part of #56. Thanks, @shad0whawk!

**Comment by keepassium** [comment]
I cannot reproduce this on iOS 13.1 release (iPhone SE). Possibly due to small screen?

 @shad0whawk, assuming you've updated, do you still see this?

**Comment by shad0whawk** [comment]
Ironically I just checked this a moment before you posted this message. Yes it’s still an issue on 13.1 final on both 6.5” and 4.7” screens if that matters.

**Comment by shad0whawk** [comment]
FEIW the larger font seems out of place while the smaller font seems like it fits the app and screen better.

**Comment by keepassium** [comment]
Thanks! I guess I'll need a bigger phone :) or to wait for 13.1 simulator...

**Comment by shad0whawk** [comment]
Another example from an iPhone 8
![46535C6B-28D3-41E2-8DA3-B95C480E7B62](https://user-images.githubusercontent.com/6074105/65555806-d6dc8300-deea-11e9-8afc-a54e367d94c6.png)

**Comment by keepassium** [comment]
@shad0whawk, do you still see this on the latest iOS release? 

For me it seem to be fine now (6.1" screen, iOS 13.2.3): 
![IMG_0002](https://user-images.githubusercontent.com/38399598/69486787-add76080-0e4f-11ea-9f19-1e82efe71a99.PNG)

**Comment by keepassium** [comment]
Ok, let's consider this closed.
