### ISSUE TITLE
Warn when screen is being captured

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#67]
**Describe a feature you'd like**
Doing a screen recording for demonstration of a bug, it struck me that there is no indication the screen is being captured.

For the case of screen recording, I guess it's not that big of a deal, as whoever may do the recording must already know your password to produce a video of it, and could then just as well use that straight up.

A more troublesome case would be if forgetting AirPlay mirroring on, which could lead to unwanted people seeing you enter your password, or view passwords from entries in your database.

Both of the cases does come with a colored overlay bar at the top status bar (definitely screen recording, but I haven't tried AirPlay mirroring since iOS 11 or so), so that itself may be indication enough.

**Additional context**
Best lead/suggestion I have in Apples API documentation is to this Technical Q&A: https://developer.apple.com/library/archive/qa/qa1970/_index.html#//apple_ref/doc/uid/DTS40017687

**Comment by keepassium** [comment]
The screen capture indicator is the system's responsibility. 

![Screen recording indicator on iPhone X and earlier devices.](https://media.idownloadblog.com/wp-content/uploads/2018/06/iPhone-X-recording-indicator-vs-768x358.jpg)
[[source](https://www.idownloadblog.com/2018/06/12/silentrecorder-hides-the-red-status-bar-indicator-during-active-screen-recordings/)]

For AirPlay mirroring, these indicators turn blue. (According to [this video](https://youtu.be/rGniF02F4_4?t=204).)

Admittedly, on newer iPhones the indicator is rather minimalistic, but that's up to Apple... I'm not sure it would be useful to duplicate these indicators in the app. After all, anyone qualified to start screen recording/mirroring is automatically assumed to know what they are doing :)

**Comment by KizzyCode** [comment]
On macOS, it is possible to set the [sharing type](https://developer.apple.com/documentation/appkit/nswindow/sharingtype) on windows. And since Netflix etc. are able to prevent screenshots and screen sharing etc., maybe it's possible to set a similar setting on iOS?

**Comment by keepassium** [comment]
> And since Netflix etc. are able to prevent screenshots and screen sharing etc., maybe it's possible to set a similar setting on iOS?

This seems to be enabled for DRM videos. For a normal app, this would require [converting the UI into a video](https://stackoverflow.com/a/48228319/1671985), which will likely make the UI laggy (at best).

Besides that:
1) The system already shows a screen capture/AirPlay indicator (see above). 
2) The password entering process is not visible on recording (tested onboard screen recorder and QuickTime Player mirroring): the password field appears empty and keyboard taps are not shown either.

That is, the system pretty much addresses any accidental sharing. So, I don't really see the point. Am I missing something?

**Comment by KizzyCode** [comment]
Ah, ok; that the password field appears empty was not always the case. E.g. there were attacks where kids used the screen-recording function to capture the screen time code.
In general it’s problematic if people can use some stress situation to capture your input; the screen-recording attack was a perfect example for such a social engineering attack.

However since this has been patched it’s not important anymore; and obviously it’s not solution to convert the screen to a DRM-protected video^^

**Comment by keepassium** [comment]
Since there were no other concerns about screen sharing/AirPlay indicators, I guess the system ones are sufficient. Therefore, closing.
