### ISSUE TITLE
Creation of new database lands you in double levels of the Unlock database UI

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#68]
**Describe the bug**
Upon creation of a new database, you get two segues into the same Unlock database UI, and you have to backtrack twice to get back to the file selection screen.

**To Reproduce**
1. Go to the database list
2. Tap on the top right + sign
3. Select create database
4. Enter a password and tap the "Save database" button
5. In the save dialog, select "On my phone" and the KeePassium folder, and tap save in the top right corner
6. Watch the "double bounce" to the same UI twice.
7. The dialog you end up on has a top left label of "Close", tap here
8. The second dialog, same as the first, has a label of "Databases"

**Expected behavior**
Only one level of the unlock database dialog should be open, and upon pushing "Close" or "Databases" you should be back at the database list.

**Screenshots**
Will email a link to video reproduction

**User Information (please complete the following information):**
 - Device: iPhone XR
 - OS: 13.1
 - App Version: 1.03.37

**Additional context**
Experienced while testing out new language, in case localization may affect anything.

**Comment by keepassium** [comment]
Thanks, Patrik! I've seen this a couple of times, seems to occur when file creation takes more than split-second. 

I plan to refactor (well, rewrite) the "database list — unlock — view group" workflow, so this will probably be solved as part of refactoring.
