### ISSUE TITLE
Autofill with no match does not focus search field

### ISSUE THREAD

**Issue by tunger** [keepassium/KeePassium#69]
**Describe the bug**
When using autofill, and keepassium does not find matching entries (thus showing all of them), it fades in the search bar. However, there is no textbox focus on the search bar, so in order to type in search tokens you need to tap on the search box.

**Expected behavior**
The search box should be focused so that the keyboard is shown.

**User Information (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.1.2
 - App Version: v1.04.38

**Additional context**
Is it supposed to use the setting "show searchbar on start" (or however it is called in English, I am using German version)?

**Comment by keepassium** [comment]
Thanks! I also see this, will fix in the next update.
