### ISSUE TITLE
AutoFill keeps locking up with a Face ID prompt

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#74]
**Describe the bug**

In version 1.07.43, AutoFill keeps showing a Face ID prompt. After a successful scan, it shows the app content for a moment and locks up again. 

**Workarounds**
- Set AppLock timeout to at least 3 seconds [thanks, Robin]
- Alternatively, look away from the screen, so that Face ID scan fails. Then unlock the app using PIN/passcode.

**To Reproduce**

1. Enable AppLock with Face ID.
2. Open any login page in the browser and press "Passwords" to open KeePassium AutoFill.
3. Look at the Face ID prompt.
4. AutoFill unlocks, then immediately locks up again.
5. Go to step 3.

**Expected behavior**
AutoFill unlocks and remains unlocked.

**User Information**
 - Device: any with Face ID biometrics
 - OS: iOS 13.2.3 (previous iOS versions seem to be ok)
 - App Version: 1.07.43

Thanks to everyone who reported this.

**Comment by keepassium** [comment]
Hmm, I cannot reproduce this in 13.1 simulator and my iOS devices have only Touch ID...

If someone has this issue, I would appreciate some help:

- Open AutoFill
- Make a couple of loops through Face ID
- Unlock using the passcode
- Long-press the top-left button in AutoFill. This will show the diagnostics log.
- Copy the log to clipboard and send it to me (either here or via email).

Thanks!

**Comment by robimac04** [comment]
It works fine if you set the Timeout for App Protection from "Immediately" to at least 3secs.

HTH

**Comment by keepassium** [comment]
@robimac04, that's a great workaround, thanks!

**Comment by keepassium** [comment]
I've got a Face ID device for testing and reproduced the bug. It seems to happen only in the browser, not in apps. Will get it fixed over the weekend.

**Comment by keepassium** [comment]
The fix has just been published on the App Store (v1.08.48)

**Comment by keepassium** [comment]
iOS 13.1.3 is also affected, so the fix should activate on earlier iOS 13 versions, too.
