### ISSUE TITLE
Feature request: Add quicktype support

### ISSUE THREAD

**Issue by igorkulman** [keepassium/KeePassium#75]
**Describe a feature you'd like**
I would like the app to have QuickType support, just like say 1Password does. QuckType means showing credentials right over the keyboard:

![image](https://user-images.githubusercontent.com/4746070/69579377-a42a3600-0fd2-11ea-8238-4c3677019bdf.png)

**Comment by keepassium** [comment]
Igor, thanks for the succinct description!

Yeah, this is a popular feature request and there is already an earlier issue (#50). It could use a more informative title, however. I will take yours, if you don't mind.
