### ISSUE TITLE
Feature request: Add support for field references

### ISSUE THREAD

**Issue by mrhedstrom** [keepassium/KeePassium#77]
**Describe the bug**
In KeePass you can duplicate entries and replace the username and password by references. That means that the value of user will be:
`{REF:U@I:<UUID of the entry>}`
And the Password:
`{REF:P@I:<UUID  of the entry>}`
You can even have references combined with other data. Very useful for domain login where you have one username / password entry but also an entry for user login including Domain. i.e
`MYDOMAIN\{REF:U@I:<UUID of the entry>}`

This is not supported by KeePassium. It will result in the actual reference string when typing or copying the value.

**To Reproduce**
1. In keePass create an entry with username and password
2. Right click the entry and chose Duplicate Entry...
3. Tick the "Replace user names and passwords by references"
4. Autotype the new duplicated entry in KeePass (This works)
5. Autotype the new duplicated entry in KeePassium (does not work)

**Expected behavior**
The expected behavior is that the reference string will be decoded recursively until no references are left in the value. This should be done when copying or auto-typing the entry.

**User Information (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS13.2.3
 - App Version: 1.07

**Comment by keepassium** [comment]
You are right, field references don't work (yet). However, this is not a bug — this is a missing feature :) I have them on my list and they will be implemented.
