### ISSUE TITLE
Feature request: Add Diceware password generator

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#78]
It should be possible to generate [Diceware passphrases](https://en.wikipedia.org/wiki/Diceware), not just random passwords.

**Comment by msimkunas** [comment]
Isn't using a real dice as the entropy source the whole point of the diceware method? I'm no cryptography expert, but it feels like the virtual dice kind of defeats the purpose of diceware.

**Comment by keepassium** [comment]
@msimkunas, as I understand, the main benefit is that passphrases are more human-friendly: easier to type and to memorize, should one need to. At least, this seems to be the consensus of [this extensive discussion](https://security.stackexchange.com/questions/6095/xkcd-936-short-complex-password-or-long-dictionary-passphrase/) on StackExchange.

The source of randomness is probably less important, as long as we use a [cryptographically secure random number generator](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator) (which KeePassium does).

**Comment by basbebe** [comment]
Having different wordlists to choose from (EFF long, Different languages, etc) would be a nice benefit.
