### ISSUE TITLE
Feature Request: OTP Overview

### ISSUE THREAD

**Issue by noudAndi** [keepassium/KeePassium#8]
I'd love to have an overview over all saved OTP Tokens in a file. (Maybe an option to add favorite OTPs to this overview.)

Just like a standard Tool Like "Google Authenticator" does.

My use-case is, having to login to a VPN each day, which requires OTP. It would be much easier for me, having the tokens in an easy accessible overview.

**Comment by keepassium** [comment]
Thanks for the idea!

I am a bit reluctant to create a separate screen for OTP overview... KeePass' philosophy is more about "find that one entry fast", rather than overview. 

One possibility would be to show entries with TOTP when you search "TOTP" (this does not work yet, just thinking aloud).

For your use case, maybe AutoFill + #7 would be a better solution?

**Comment by noudAndi** [comment]
Hi,

I can understand, that you don't want an additional screen and I am also fine with a search word.

I've read #7 , but it's no real option to me, as I need to type in the OTP on a PC/Mac, while having the OTP on the iPhone.

So it would be great, if you could add the search option :)

**Comment by keepassium** [comment]
You are right, I got too focused on iOS and forgot the good old "just type it" scenario :) Let's start with the TOTP-specific search, and then see how to improve it.

Saving last searches would actually be great! I just realized that every day I am typing the same query in KeePassXC...

(These will take some time, though...)

**Comment by keepassium** [comment]
Now you should be able to find OTP entries by searching "otp" or "totp". 

Does this work for your use case, or can be better? (how? :)

**Comment by Thunder33345** [comment]
maybe appending otp code to the right of the entry?(if they have totp)
there seems to be some free space anyways
this would appear in basically everywhere the entry was seen

for privacy concern it could be hidden(like rn), tap to show, always show beside

**Comment by keepassium** [comment]
Hmm, ok. I'll see what I can do without overloading the UI. Thanks.

**Comment by Thunder33345** [comment]
if you concern about overloading, maybe make it explicitly only show when "totp" is searched or else it would be hidden as an option

**Comment by noudAndi** [comment]
The otp/totp search pattern works. Thanks.

I like the idea, of being able to see/copy the totp in this view, but now sure, what a good way might be.

**Comment by keepassium** [comment]
@noudAndi, thanks for confirming. I think that showing TOTP-related UI elements conditionally only when searched for (as suggested by @Thunder33345) might work. Will need to play with this to find the best way...

**Comment by jakimzou** [comment]
Can you provide URL to search database totp.  For quick opening of totp without manual input

**Comment by keepassium** [comment]
Well, this took two years but the update is finally on the App Store. You can view OTP codes in the list of entries. By default, KeePassium hides them behind a button: after all, the user likely needs only one code at a time, there is no reason to expose the others...

**Comment by keepassium** [comment]
A user just explained me a valid use case for a list of TOTP codes in large font (like Google Authenticator). [Thanks, Adam.]

So reopening this feature request in @noudAndi 's original form.

**Comment by keepassium** [comment]
Well, it's about time… 
Implemented in 1.53.154 (now in beta) via [smart groups](https://support.keepassium.com/docs/smart-groups/) with `otp:*` condition (de939932cf7c3b28f8877d283510245ed9f2d979).
