### ISSUE TITLE
Add support for TOTP codes based on HMAC-SHA256/512 functions

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#81]
**Describe a feature you'd like**
Currently the TOTP generator is hard-coded to use the HMAC-SHA1 function. However, according to the [RFC 6239](https://tools.ietf.org/html/rfc6238#section-1.2), some implementations may also use HMAC-SHA256 and HMAC-SHA512.

**Comment by Nu11u5** [comment]
For compatibility, adding that the otpauth:// uri format for this uses the query parameter `algorithm=SHA1|SHA256|SHA512`

https://github.com/google/google-authenticator/wiki/Key-Uri-Format
