### ISSUE TITLE
macOS builds

### ISSUE THREAD

**Issue by donn** [keepassium/KeePassium#82]
**Describe a feature you'd like**
I would like you to start offering binaries for macOS Catalina.

While there are other KeePass solutions for Mac, me spending the 10 minutes it took to compile using Catalyst has resulted in something better than MacPass. I'm now using this binary, but would prefer if you can like add an official binary or something.

I'm aware it's not a native macOS citizen (and it doesn't look the part either,) but I'll gladly sacrifice that for Touch ID.

**Additional context**
I did have to add a minor modification to `KeePassiumLib/KeePassiumLib/premium/PremiumManager.swift`:

```swift
#if !targetEnvironment(macCatalyst)
    public func paymentQueue(
        _ queue: SKPaymentQueue,
        shouldAddStorePayment payment: SKPayment,
        for product: SKProduct
        ) -> Bool
    {
        return true 
    }
#endif
```

**Comment by keepassium** [comment]
Wow, that's impressive! I am surprised how easy it was to get it running on Catalina.

I am considering to release KeePassium on MacOS using Catalyst, — but not right now.

- Catalina/Catalyst will likely remain work-in-progress for a few months. Every OS update will break the app in surprising ways. This will need urgent analysis/user support/fixing. And I'm already quite busy doing this with frequent iOS 13 updates...

- The quick conversion makes about 80%-functional app. However, fine-tuning the other 20% will take much longer (for example, KeePassium was 80% ready back in October 2018 :) This would slow down the development of the iOS version. So everyone would be stuck with two incomplete apps...

- I cannot release the app without support, it kinda comes with the package :) If number of support requests doubles, obviously there will be less time for improving the app...

So, I think it is a bit too early to expand to MacOS just yet. But I'll be happy to once both Catalyst and KeePassium/iOS are more mature.

**Comment by donn** [comment]
Ah, well. That's understandable.

I'll still use it though. Beats having to type my password into MacPass every time. :P 

<img width="901" alt="Screen Shot 2019-12-05 at 00 24 10" src="https://user-images.githubusercontent.com/12652988/70186909-9de43a00-16f5-11ea-9f46-c8ecb87b7790.png">

**Comment by yacob841** [comment]
@donn I'm curious how you got it working. I attempted to just do the modification you stated but after me first few clicks it no longer accepts input but the major issue is it won't let me add an existing database, when I click on it nothing happens. Does this happen with you?

**Comment by donn** [comment]
Nope. KeePassium was mostly functional to me.

**Comment by yacob841** [comment]
Does yours use the default KeePass icons instead of KeePassium icons as well? I'd like to change them to KeePassiums but don't know how.

**Comment by keepassium** [comment]
@yacob841, [Password AutoFill](https://developer.apple.com/documentation/security/password_autofill) is only available on iOS...

As for the icons — yes, the repository contains the standard Nuvola icons. I cannot share the original KeePassium icons for two reasons:

1) They are a competitive advantage for the commercial side of the app. 
2) They are partially based on a RoundIcons set, and [its license](https://roundicons.com/usage-license/) is not exactly GPL-compatible.

**Comment by yacob841** [comment]
Ah, gotcha, makes sense. Thanks anyways! And again, amazing app, keep up the great work!

**Comment by keepassium** [comment]
Hurray! First Mac Catalyst beta is out, feedback is welcome :)

https://github.com/keepassium/KeePassium/releases/tag/1.22.84

**Comment by donn** [comment]
Fastest I've ever clicked.

Works well! Imported my database and Touch ID unlock works. What more can I ask for. :)

**Comment by keepassium** [comment]
@donn, thanks for confirming! I was not sure if it is signed/notarized correctly and launches only on my machines :)

**Comment by keepassium** [comment]
I guess this can be closed now. For any issues with the macOS version, feel free to create new issues and add the "macOS" label. Thanks!

**Comment by Guntriaske457** [comment]
@keepassium 
Hello,

the KeePassium Mac Catalyst version works for macOS 10.14 and higher? It is not possible to support for macOS 10.13 and lower or maybe possible?

**Comment by keepassium** [comment]
@Guntriaske457, Mac Catalyst was introduced in macOS Catalina (10.15), so it cannot run on previous versions. 

But even on 10.15 KeePassium has some odd coloring and visual issues. On 11.0 the same build looks and behaves much better. So while the source code will build and run on 10.15, the distribution file requires at least 11.0.
