### ISSUE TITLE
Suggestions on searching for TOTP

### ISSUE THREAD

**Issue by jakimzou** [keepassium/KeePassium#83]
Can you provide URL to search database totp?  Quickly open all totp without manual input #8

**Comment by keepassium** [comment]
Hi, thank you for the suggestion!
Can you please clarify how it is different from #8?

**Comment by jakimzou** [comment]
No different. A suggestion based on this

It ’s like ‘keepassium: // ***’. It can open a database. Can I add a search term afterwards? This way you can rely on the URL to go directly to TOTP

For example, "keepassium: // *** TOTP" can go directly to the TOTP page of the *** database. Rather than opening the database and entering TOTP manually

I don't know if this is feasible

**Comment by keepassium** [comment]
Mmm, I'm not sure I understand... Do you want to open KeePassium using a custom URL, so that the app opens the specified database and pre-fills the search field with a specified query?
If yes, how that URL would be called? (Is this a thing for Siri Shortcuts?)

**Comment by jakimzou** [comment]
Yes.Shortcuts can use URL
