### ISSUE TITLE
Steam TOTP settings fields not recognized

### ISSUE THREAD

**Issue by Nu11u5** [keepassium/KeePassium#85]
Per https://keepassium.com/articles/how-to-setup-totp/ I've created the fields "TOTP Settings" and "TOTP Seed" in the entry, however KeePassium is not showing any line for a TOTP generated code.  I only see those two values, plus User Name, Password, URL, and Recovery Code (my custom field).

Secondly, a request to support Steam TOTP in otpauth:// uri format, such as describe in https://github.com/keeweb/keeweb/issues/564#issuecomment-535221800

**Comment by Nu11u5** [comment]
![steam-otp](https://user-images.githubusercontent.com/617690/71652799-d32c7980-2ced-11ea-8f82-3aeaa587b980.jpg)

**Comment by Nu11u5** [comment]
Noting that your documentation says that for the TOTP Seed that "spaces and capitalization don't matter", however in the case of Steam TOTP the shared secret is base64 encoded in which case capitalization ***very much*** matters.

**Comment by Nu11u5** [comment]
Ok, so it looks like the TOTP secret is supposed to be in base32 encoding, but Steam Desktop Authenticator is storing the key in base64 encoding.  I was able to get the key in base32 encoding and set TOTP Seed to this value, however it is still failing to recognize and display the TOTP code.

**Comment by Nu11u5** [comment]
Ok, so it looks like the TOTP Seed is supposed to be in base32 encoding, but Steam Desktop Authenticator is now saving the seed as base64 in the maFile (which means that the [linked instructions](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication#getting-shared-secret-from-steam-desktop-authenticator-windows) are wrong).  I was able to get the seed in the correct base32 encoding (from the otpauth:// uri also saved in the file) but the feature is still not working.

**Comment by Nu11u5** [comment]
So I got this to finally work by deleting several fields from the entry and starting over.

I'm going to attribute this issue partially to a conflict with KeeWeb.  That application will take the TOTP Settings and TOTP Seed fields and create a new otp field with a generic otpauth:// uri using those values.  This generic uri is missing the Steam identifiers so neither app recognize it correctly.

This could probably be most easliy resolved by having KeePassium recognize Steam TOTP using the otpauth:// uri.

**Comment by keepassium** [comment]
Thank you for such a detailed feedback!

I agree, supporting the URI format for Steam TOTP seems like the most logical things to do. The change was quick to implement, it will be included in the next update.

Also swapped the TOTP Seed/Settings fields in the documentation and clarified that Steam seed should be in base32 format.

Thanks again!
