### ISSUE TITLE
Password Generator Character Blacklist and Whitelist

### ISSUE THREAD

**Issue by yacob841** [keepassium/KeePassium#86]
I mentioned this on reddit a long time ago but figured I should post here so it doesn’t get forgotten and has a log.

Sometimes websites don’t allow specific symbols or only allow certain symbols. This always creates an issue when generating passwords. For me, most of the time it ends with my unchecking the symbols option and manually adding in characters. It would be nice if you had a section in the Password Generator where you can type characters to blacklist or whitelist (blacklist all symbols besides the listed characters).

**Comment by keepassium** [comment]
Hi, thanks for posting! I keep track of feature requests in a private list (cool features are a competitive advantage :) Both #87 and this one are there. 

I understand that having a simple enhancement hanging in the task list for months is annoying. It is annoying for me, too. As much as I'd like to work on KeePassium full time, currently this is not feasible, so I have to prioritize the development time: 

1. bug fixes first (iOS 13 took its toll there)
2. then, most needed features (by number of email requests and GitHub reactions), 
3. then, blocking features (e.g. YubiKey: it's either supported or not, there's no workaround possible), 
4. then, non-blocking features: those that have workarounds (like #87: it would be more convenient to add an entry via AutoFill, but one can still use the main app to get the task done.)
5. finally, nice-to-haves (unless they need only a couple of minutes for implementation)

Password generator needs a major redesign, customizable character set and Diceware passphrase generator (#78). However, it does already generate strong passwords, so this redesign has 4th priority. Surely, it will get done, but might hang around in the task list for a few months first...

**Comment by vit9696** [comment]
This can be partly connected to https://github.com/keepassium/KeePassium/issues/106 as it can be a way to do it automatically.
