### ISSUE TITLE
Cannot create database in simulator

### ISSUE THREAD

**Issue by capitanx9** [keepassium/KeePassium#89]
По нажатию на кнопку **save** происходит переход к пустой таблице, где должна создаваться папка с расширениям .kdbx, как в приложении с AppStore.

![Снимок экрана 2020-02-05 в 16 37 47](https://user-images.githubusercontent.com/24793669/73846780-25edd980-4836-11ea-9773-e3ad807c887d.png)

> DocumentManager] Failed to create FPSandboxingURLWrapper for file:///Users/xxx/Library/Developer/CoreSimulator/Devices/EFDBFE8F-A829-4111-9CD3-098B1CD6B107/data/Containers/Data/Application/9FF52732-D56A-4B03-884D-3A07C6B0C86D/(A%20Document%20Being%20Saved%20By%20KeePassium%2022)/MyPasswords.kdbx. Error Domain=NSPOSIXErrorDomain Code=22 "couldn't issue sandbox extension com.apple.app-sandbox.read for '/Users/xxx/Library/Developer/CoreSimulator/Devices/EFDBFE8F-A829-4111-9CD3-098B1CD6B107/data/Containers/Data/Application/9FF52732-D56A-4B03-884D-3A07C6B0C86D/(A Document Being Saved By KeePassium 22)/MyPasswords.kdbx': Invalid argument" UserInfo={NSDescription=couldn't issue sandbox extension com.apple.app-sandbox.read for '/Users/xxx/Library/Developer/CoreSimulator/Devices/EFDBFE8F-A829-4111-9CD3-098B1CD6B107/data/Containers/Data/Application/9FF52732-D56A-4B03-884D-3A07C6B0C86D/(A Document Being Saved By KeePassium 22)/MyPasswords.kdbx': Invalid argument}
> 2020-02-05 16:38:58.445664+0200 KeePassium[33696:284673] [UIDocumentLog] UIDocumentPickerViewController : didPickDocumentURLs called with nil or 0 URLS

**Comment by keepassium** [comment]
This is a [bug in Xcode 11/iOS 13 simulator](https://stackoverflow.com/questions/57807670/uidocumentbrowserviewcontroller-error-cannot-create-urlwrapper-for-url-on-ios1) when running on macOS Mojave: 
The solution is either to upgrade to macOS Catalina or to downgrade to Xcode 10.2/iOS 12.

---

Это баг симулятора Xcode 11/iOS 13 при работе на macOS Mojave. Немало нервов он мне потрепал... Решается или обновлением до macOS Catalina, или откатом на Xcode 10.2/iOS 12.

P.S. Репозиторий международный, поэтому лучше по-английски. Если это не вариант, можно по почте. Спасибо за понимание :)
