### ISSUE TITLE
AutoFill: Add button to clear automatic suggestions and start manual search

### ISSUE THREAD

**Issue by Dragonblitz10** [keepassium/KeePassium#9]
i added a couple entries...
1 x email
3 x general

when i login or try to on a website only the email one is displayed, maybe offer an option to display all saved passwords despite condition's etc

**Comment by keepassium** [comment]
I assume you are talking about AutoFill? Its automatic filtering is a bit hit-and-miss at the moment, and will need some fine-tuning based on specific cases.

In this case, a "Show all" button would indeed be a quick and easy solution. In the meanwhile, as a workaround you can swipe down on the list to start manual search.

Please let me know if I understood you correctly. Thanks!

**Comment by Dragonblitz10** [comment]
understood fine, thank you for the quick response

**Comment by keepassium** [comment]
I will reopen: this is a valid feature that many people will find useful. Also, it is easy to implement :)
