### ISSUE TITLE
Allow overwrite of database when shared from another app

### ISSUE THREAD

**Issue by FlxVctr** [keepassium/KeePassium#91]
**Describe a feature you'd like**
If sharing a database from another app, it should be possible (after a warning dialogue) to overwrite the existing database.

**Additional context**
This comes in handy for file sharing apps that are not supported/do not support the iOS Files app (e.g. Cryptomator).

**Comment by FlxVctr** [comment]
For convenience, the password should stay stored in KeePassium despite the overwrite.

**Comment by FlxVctr** [comment]
Ok, I just realised that it is possible to share it with the files app and save to the local KeePassium folder. So I consider this a matter of taste/UX improvement. Just close this in case you don't agree.

**Comment by keepassium** [comment]
You are absolutely right, it's a long-standing UX issue. It should be fixed in the app, and I have postponed it long enough...
