### ISSUE TITLE
Extension and app stuck on loading when offline

### ISSUE THREAD

**Issue by igorkulman** [keepassium/KeePassium#92]
**Describe the bug**

When you are offline and try to open a vault in Dropbox or Box in the app or use the extension to fill in a password (typical use case trying to log in to the router to see what is going on) opening the vault gets stuck and needs to be killed

**To Reproduce**
1. Go offline
2. Try to open a vault in the app
3. See the app stuck, needing to be killed

**Expected behavior**
Get some kind of error message, or even better just work.

**Screenshots**
![IMG_750B735E962A-1](https://user-images.githubusercontent.com/4746070/77412517-452cd000-6dbe-11ea-8641-84e9d61f91b5.jpeg)

**User Information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3.1
 - App Version: 1.10

**Comment by keepassium** [comment]
Thanks, Igor.

Yeah, this seems to be a very common issue. Back in iOS 12 days, [resolving a URL bookmark](https://developer.apple.com/documentation/foundation/nsurl/1572035-urlbyresolvingbookmarkdata) used to be a fail-fast procedure: it either worked quickly, or quickly returned an error. In iOS 13, resolving a bookmark can take infinitely long and KeePassium does not handle this well...

I had hoped this was a system bug, but it seems to be the new iOS reality to deal with. It might not be possible to just make it work (the request gets stuck deep in the system), but I will certainly add a timeout and make the loading message more informative. (Once the schools open again, that is...)

By the way, did you try to mark the database as "available offline" in Dropbox/Box? Does this change anything?

**Comment by igorkulman** [comment]
When I marked the vault file for offline access in Box, it seem to have helped when tested in airplane mode (which might be different than on Wifi with no internet access).

**Comment by keepassium** [comment]
I would keep it open, if you don't mind... Even if marking the database as available offline works as a workaround, these delays should be better handled by KeePassium itself (responsive UI + timeout).

**Comment by keepassium** [comment]
This was fixed in [1.14.63](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#11463---2020-06-21), but I forgot to reference this issue. Closing finally :)
