### ISSUE TITLE
YubiKey 5C support on iPad Pro?

### ISSUE THREAD

**Issue by jeinwag** [keepassium/KeePassium#94]
Hi,
just a quick question: is the YubiKey 5C supported by KeePassium on the iPad Pro (since it has USB-C instead of a Lightning port)?

If it isn't, are there an plans to support it?

**Comment by keepassium** [comment]
According to Yubico, [iOS devices don't support USB-C accessories](https://github.com/Yubico/yubikit-ios#q8-are-the-usb-c-type-ios-devices-supported-by-the-yubikey-5ci):

> The USB-C type iOS devices, such as the iPad Pro 3rd generation, have limited support when using the YubiKey 5Ci or another type of YubiKey with USB-C connector. The OS is not officially supporting external accessories on these devices. However these devices support external USB keyboards, so the OTP functionality of the key will work and the key can be used to generate Yubico OTPs and HOTPs.

So it seems you can use the YubiKey 5C to enter the master password, but not in challenge-response mode. 

Whether this is likely to change any time soon, is a good question for Apple / Yubico...

**Comment by jeinwag** [comment]
Thanks for the quick heads up! That's a bummer, since none of the iPads have NFC.

**Comment by keepassium** [comment]
I just tested YubiKey [5Ci](https://www.yubico.com/lu/product/yubikey-5ci/) (the one with Lightning connector, not 5C): it works on iPad Pro via the new [USB-C to Lightning adapter](https://www.apple.com/shop/product/MUQX3AM/A/usb-c-to-lightning-adapter). This can be an expensive upgrade, but at least not a dead end anymore.
