### ISSUE TITLE
Question : Does Keepassium store keyfile in iCloud backup ?

### ISSUE THREAD

**Issue by Jingjok86** [keepassium/KeePassium#97]
If iCloud backup is enabled (the automatic device backup function by iCloud, not the database backup by Keepassium), then KeePassium is by default added to the backup, like any other application, although it can be manually de-selected in the iCloud backup configuration in the device setup.

My question is, if iCloud backup for KeePassium is enabled, will it also back up the key file that has been manually copied into Keepassium to iCloud ? 
If yes, then this should be disabled by default, as it is a security concern. The keyfile would have been leaked to iCloud without the user's knowledge and someone who gains access to the iCloud storage could retrieve the keyfile from the backup.

There was a similar issue with MiniKeePass :
https://github.com/MiniKeePass/MiniKeePass/issues/400

**Comment by keepassium** [comment]
Currently, all local files are treated equally. If iCloud backup for KeePassium is enabled, it will backup both databases and key files.

And you are right, if the user want databases included in backup — this does not necessarily apply to key files. (Depends on the user, though...) I will add a switch to the settings. Thank you for raising this issue.
