### ISSUE TITLE
Password extention keeps crashing with a large database

### ISSUE THREAD

**Issue by philippmayrth** [keepassium/KeePassium#99]
**Describe the bug**
The AutoFill extention keeps crash

**To Reproduce**
- Create a fairly large database with KeePassXC on latest macOS (~20 MiB).
- Set DB settings to use AES or ChaCha20
- Set hash algo to Argon2 with 10 iterations and 10 MiB memory usage _(already lowered a few times to the minumum config Im comfortable with after crashes of KeePassium)_ or AES-KDF with 25657895 iterations (auto set by KeePassXC).
- Only use password no keyfile
- Sync via iCloud Drive

**Expected behavior**
Eiter unlock the database without crashing or clear message which hash config is available as well as how much memory is availabe to the extention for performing the hashing taking the database size into account.

**User Information (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 13.4.1
 - App Version: 1.11 (latest from AppStore)

**Additional context**
- Dont know if this helps but Im using the fully unlocked version of the app.
- Unlocking a database with just ~ 10 KiB in size works with AES and Argon2
- Unlocking works in the app (not the AutoFill extention) regardless how big the database is

**Comment by keepassium** [comment]
Hi Philipp, thank you for the report.

This is not exactly a bug, this is a system limitation...  

By default, .kdbx databases are gzip-compressed. So a 20 MiB database file is likely to occupy much more than 20 MiB once decompressed. The AutoFill extension, in turn, can use only about 120 MiB for everything. (The main app does not have this limit.)

There is more info in the FAQ: [AutoFill memory limits (“Not enough memory to continue”)](https://keepassium.com/articles/autofill-memory-limits/).

**Comment by philippmayrth** [comment]
Ah I did not consider compression or other apps reducing the availabe 120 MB makes total sense now.
I removed a bunch of attachments and the database is down to ~7 MiB. It works very well now.
Tahnk you.
